### ISSUE TITLE
[Question] Inheritance with BuilderApi?

### ISSUE THREAD

**Issue by DoCode** [natemcmaster/CommandLineUtils#102]
It's possible to use inheritance when using the Builder API?

E.g., a unique option for some different commands.

**Comment by natemcmaster** [comment]
Options can be inherited. Is this what you had in mind?

https://github.com/natemcmaster/CommandLineUtils/blob/2e576c856f55d74796cce332037c34bdc6159a42/test/CommandLineUtils.Tests/CommandLineApplicationTests.cs#L404-L431

**Comment by DoCode** [comment]
When you have hints for that task, feel free to share with me 😉, but for now the root question is resolved. I close this for now.

**Comment by natemcmaster** [comment]
Try recursively searching through [CommandLineApplication.Commands](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html#McMaster_Extensions_CommandLineUtils_CommandLineApplication_Commands) and use [.GetOptions()](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html#McMaster_Extensions_CommandLineUtils_CommandLineApplication_GetOptions)
