### ISSUE TITLE
DefaultCultureCanBeChanged tests can fail due to timezone offset mismatches

### ISSUE THREAD

**Issue by liamdawson** [natemcmaster/CommandLineUtils#104]
**Describe the bug**
_On my machine_, the unit tests for `DefaultCultureCanBeChanged` fail in

* `CommandLineUtils | test | McMaster.Extensions.CommandLineUtils.Tests | ValueParserProviderCustomTests <.NETCoreApp-v2.0>`
* `CommandLineUtils | test | McMaster.Extensions.CommandLineUtils.Tests | ValueParserProviderCustomTests <.NETFramework-v4.6.1>`

due to a timezone mismatch:

```
McMaster.Extensions.CommandLineUtils.Tests.ValueParserProviderCustomTests.DefaultCultureCanBeChanged(property: "DateTimeOffset", test: "03/30/2017 3:03:03", culture: "en-US")

Assert.Equal() Failure
Expected: 2017-03-30T03:03:03.0000000+10:00
Actual:   2017-03-30T03:03:03.0000000+11:00
   at McMaster.Extensions.CommandLineUtils.Tests.ValueParserProviderCustomTests.DefaultCultureCanBeChanged(String property, String test, String culture) in W:\CommandLineUtils\test\CommandLineUtils.Tests\ValueParserProviderCustomTests.cs:line 147
```

**To Reproduce**
I'm not even sure how I'd say to reproduce this. My machine's native timezone is `Australia/Melbourne`, in Unix TZ parlance.

**Expected behavior**
Tests should pass.

**Comment by liamdawson** [comment]
I think the chances are that `2017-03-30` was during DST in my timezone, and thus when you hydrate a time in my timezone on that date, it comes out with a different offset. 🕐

**Comment by atruskie** [comment]
Hi @liamdawson. This seems like a fine fix but I wonder if it might be better to just specify the timezone offset information explicitly in the tests? Either way, it's a relatively minor change. Thanks for fixing my mistake!

```
         [Theory]
         [InlineData(nameof(DateParserProgram.DateTimeOffset), "03/30/2017 3:03:03 +04:00", "en-US")]
         [InlineData(nameof(DateParserProgram.DateTimeOffset), "2017年03月30日 3:03:03 +04:00", "zh-CN")]
         public void DefaultCultureCanBeChanged(string property, string test, string culture)
         {
            var expected = new DateTimeOffset(2017, 3, 30, 3, 3, 3, TimeSpan.FromHours(4));

```

**Comment by liamdawson** [comment]
I'm easy, that also solves it, guess it also tests less things at once. I should be able to implement that change in the next couple of days, but if one of the maintainers wants to make the change instead, I'm also happy with that. 👍

**Comment by liamdawson** [comment]
@atruskie Technically, the PR is now all your work 😆. Ready for re-review.

**Comment by atruskie** [comment]
thanks (I don't have write privledges though)
