### ISSUE TITLE
Unable to search the natemcmaster/CommandLineUtils codebase on GitHub

### ISSUE THREAD

**Issue by bbrandt** [natemcmaster/CommandLineUtils#11]
# The Problem
Try searching for [ResponseFileParser](https://github.com/natemcmaster/CommandLineUtils/search?q=ResponseFileParser&type=Code&utf8=%E2%9C%93).
```
Sorry, forked repositories are not currently searchable.
You could try searching the parent repository.
```
# Details
https://github.com/blog/1381-a-whole-new-code-search
"Repository forks will not be searchable unless the fork has more stars than the parent repository."

# Suggested Solutions
## Get More Stars
We can advertise and be awesome, then maybe we can get more stars than [aspnet/Common](https://github.com/aspnet/Common).  But then we have to continue to get more stars as the more and more people find and star `aspnet/Common`.  Seems like it could be a battle as `aspnet/Common` has a free advertising mechanism, being connected to Microsoft.

## Contact GitHub Support to Unlink the Projects
StackOverflow knows all things. 
https://stackoverflow.com/a/16052845/5167537
"You can [contact github support](https://github.com/contact) and ask them to switch your repository to "normal mode".

On [this page](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork), "Commit was made in a fork" paragraph, it is explained that one has to go through support to switch. Therefore, it is likely that there is no way to do that by yourself (unless you destroy and recreate your repo which is explained before... if you do so be careful if you have tickets or a wiki attached to your project as they will be deleted!)." -- Thomas Moulard

**Comment by natemcmaster** [comment]
Hmm, interesting problem. What would happen to aspnet/Common if we had more stars? Would that repo become unsearchable?

**Comment by bbrandt** [comment]
No.  `aspnet/Common` is the original, so is and always will be indexed.  

My preference is more towards the "Contact GitHub Support to Unlink the Projects".

**Comment by natemcmaster** [comment]
Ok. I sent GH support a note. I like that it shows up as a 'fork', but I'm okay dropping that association to fix this and a few other annoying fork-repo behaviors. For example, the new pull request page defaults to merging back to aspnet.

**Comment by natemcmaster** [comment]
Done.
