### ISSUE TITLE
Option attribute based upon enum does not allow to override validation behaviour 

### ISSUE THREAD

**Issue by stefandevo** [natemcmaster/CommandLineUtils#120]
Maybe not a bug, but I have this enum for an option, and when provided with an invalid enum, I do see the standard error message.
However, I want to be able to provide or:
- my custom validation message
- ShowHelp()

Please note that in my case I just run `CommandLineApplication.Execute<GeneratorCommand>(args);` so I have to access to the `CommandLineApplication` instance to subscribe to `ValidationErrorHandler`

**Comment by natemcmaster** [comment]
It will be a little bit of work to override this particular error message, but you can still do it. You can provide your own parsers by using [`CommandLineApplication.ValueParsers`](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html?q=CommandLineApplication#McMaster_Extensions_CommandLineUtils_CommandLineApplication_ValueParsers). For example,
```c#
class MyEnumParser : IValueParser<MyEnumType>
{
  // implement. See https://github.com/natemcmaster/CommandLineUtils/tree/master/src/CommandLineUtils/Internal/ValueParsers for examples
}

// ...
app.ValueParsers.Add(new MyEnumParser());
```

**Comment by stefandevo** [comment]
Ok thanks, but instead of throwing an exception, there is no option to execute the ShowHelp method?

**Comment by natemcmaster** [comment]
Not from inside the parsers. There is no application in the context of IValueParser.Parse. The expected way to implement this API is to parse or throw FormatException.

If you want to call ShowHelp, I'd recommend catching `CommandParsingException` at the top level. Give this a try:
```c#
var app = new CommandLineApplication<GeneratorCommand>();
app.Conventions.UseDefaultConventions();
try
{
   app.Execute(args);
}
catch (CommandParsingException ex)
{
  Console.Error.WriteLine(ex.Message);
  app.ShowHelp();
}
```

As you can see in the implementation, `CommandLineApplication.Execute<T>(args)` doesn't do much more than this. 
https://github.com/natemcmaster/CommandLineUtils/blob/ecfc8bc3992f9ee899115622dcb851d0274f3557/src/CommandLineUtils/CommandLineApplication.Execute.cs#L51-L64

**Comment by stefandevo** [comment]
Great! Thanks for this quick feedback!
