### ISSUE TITLE
Validator access to other options for cross validation

### ISSUE THREAD

**Issue by mtwoodbury** [natemcmaster/CommandLineUtils#121]
I have related options on a sub-command. When in the validation method for one option, it would be helpful if there was a way to examine the other options.

My solution is to forgo the validation method and process the cross validation in the command.OnExecute.

I've looked through the examples and tests and didn't find something like I've described. If I've missed something, please let me know. I'm using the API code.

For example, type and subtype are related. Due to existing constraints I can't combine them.
```
$ clicommand create trans --type:auto --subtype:convertible
$ clicommand create trans --type:boat --subtype:sail
```

**Comment by natemcmaster** [comment]
You can implement `ICommandValidator` and add this to [`CommandLineApplication.Validators`](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html#McMaster_Extensions_CommandLineUtils_CommandLineApplication_Validators)

**Comment by mtwoodbury** [comment]
Thanks I will check that out. Feel free to close this as pilot error.
