### ISSUE TITLE
Q: How to configure DI container based on parsed command line options?

### ISSUE THREAD

**Issue by skolima** [natemcmaster/CommandLineUtils#122]
I'm migrating a command line application over to using `CommandLineUtils`. I'm struggling how to handle options that would influence what/how I inject into my container - namely, how to configure the logger.

As this is for a dotnet global tool, I'm trying to follow what the command line does, in terms of options, quite closely.

I've got this on my `CommandBase`:

```
[Option(CommandOptionType.SingleValue,
  ShortName = "v", LongName = "verbosity",
  Description = "Sets the verbosity level of the command. Allowed values are quiet, minimal, normal, detailed.")]
protected LogLevel Verbosity { get; } = LogLevel.Normal;
```
Now, previously, I would parse the command line first, then build my container based on this, then start the command to run.

```
// settings coming from old parsing logic
var container = ContainerRegistration.Init(settings);
var app = new CommandLineApplication<Program> {ThrowOnUnexpectedArgument = false};
app.Conventions.UseDefaultConventions().UseConstructorInjection(container);
return app.Execute(args);
```
I can invert it for most things, but I'm lost how to configure logging.

Any suggestion how to register IoC objects based on CommandLineUtils parse results?

(I think https://github.com/natemcmaster/CommandLineUtils/issues/103 might be a partial option for me, but not sure how to get access to the container in the base command?)

**Comment by natemcmaster** [comment]
If I understand correctly, this is a chicken and egg problem. You’re trying to have CLU initialize your Program type based on the value of a property on that instance about to be created. This isn't possible.

**Comment by skolima** [comment]
It is definitely a chicken and egg problem, if parsing and command construction can not be separated. But is it possible to get the parsed option values before the command is created, or by calling the parsing pipeline separately?

**Comment by natemcmaster** [comment]
You'll need to call the parsing pipeline separately.

**Comment by skolima** [comment]
I'll dig into this - and also check reconfiguring the logger from my `CommandBase`, this might be cleaner. Thank you!
