### ISSUE TITLE
Guidelines for testing against `IConsole`

### ISSUE THREAD

**Issue by tlycken** [natemcmaster/CommandLineUtils#123]
While working on [a PR for a project using this package](https://github.com/jerriep/dotnet-outdated/pull/49) I wanted to write tests for some code using `IConsole` to write out stuff to the screen. It felt like it should be reasonably easy, given that it's code written against an interface, but I still couldn't really wrap my head around how to do it.

Are there any guidelines, recommendations or such for writing tests against code that uses `IConsole`?

**Comment by natemcmaster** [comment]
If you are using xunit, here's one example: https://github.com/natemcmaster/CommandLineUtils/blob/master/test/CommandLineUtils.Tests/Utilities/TestConsole.cs

**Comment by tlycken** [comment]
Thanks, that's very helpful!
