### ISSUE TITLE
Option to skip using = or : when passing values to options

### ISSUE THREAD

**Issue by stefandevo** [natemcmaster/CommandLineUtils#126]
When specifying a value for an option, it is now needed (to my knowledge) to specify `=` or `:`

`--source=My Source`

If would be nice to have a way of putting

`--source MySource` instead.

This is in line with for example the dotnet cli where this is a standard way of passing values to options.

**Comment by natemcmaster** [comment]
This should already work. Are you encountering trouble getting this to work?

**Comment by stefandevo** [comment]
Ah, tried it again, and it does work, however, when using the `CommandOptionType.SingleOrNoValue` it doesn't work. Maybe this is by design?

**Comment by natemcmaster** [comment]
Yes, by design. It's required for unambiguous syntax. See API docs: https://github.com/natemcmaster/CommandLineUtils/blob/c723427e82899d161e2825295b9cf2e0fe3da4c4/src/CommandLineUtils/CommandOptionType.cs#L34-L47

**Comment by stefandevo** [comment]
Ok clear!
