### ISSUE TITLE
Default command

### ISSUE THREAD

**Issue by AnthonySteele** [natemcmaster/CommandLineUtils#127]
I would like an optional default command to be selected if no command is specified.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

In `NuKeeper` we want to have a default command. i.e. if the user just runs `NuKeeper` with no command, it should run the `inspect` command as a sensible default read-only demo.

**Describe the solution you'd like**

I was looking for options on the `Subcommand` attribute, e.g.

` [Subcommand("inspect", typeof(InspectCommand), IsDefault=true)]`

**Describe alternatives you've considered**

We had this working before using this commandLineUtils package. Would like to replicate with this package.

**Additional context**

**Comment by natemcmaster** [comment]
Does your inspect subcommand take options? Also, what about the root command object? Does it take options/args?

**Comment by AnthonySteele** [comment]
We are not clear on the distinction between `Command` and `Subcommand`. Not sure if it's relevant.
All of the commands have options, but for the `Inspect` command none are obligatory, all have sensible defaults.

**Comment by natemcmaster** [comment]
The reason I ask is that I wonder if you could solve it like this.

```csharp
[Command(Description = "Automagically update nuget packages in .NET projects")]
[Subcommand("inspect", typeof(InspectCommand))]
public class Program
{
	public void OnExecute()
	{
		new InspectCommand().OnExecute();
	}
}

[Command(Description = "Inspects stuff")]
public class InspectCommand
{
	public void OnExecute()
	{
	}
}
```

Btw, `[Command]` is used to add details about a command, such as help text and some parsing options. This can be used on all commands, whether they are the root command or a subcommand. `[Subcommand]` maps the relationship between parent and child commands.

**Comment by AnthonySteele** [comment]
So that kind of works - it has to be a bit more complex because of DI into the command:
```csharp
 var cmd = new InspectCommand(_container.GetInstance<LocalEngine>(),
     _container.GetInstance<IConfigureLogLevel>());
 await cmd.OnExecute();
````
That's fine, but then I do `dotnet run --age 12h` the `age` option is not recognised. although `dotnet run inspect --age 12h` works fine.

**Comment by skolima** [comment]
`--age` is defined on `CommandBase` (hierarchy: `CommandBase`->`LocalCommand`->`InspectCommand`, `Program` is outside this hierarchy), along with other options - running `inspect` like this will result with default options for every parameter. We'd need to move them all up, and I'm not sure this is a good idea. Leaning towards the "just print the help options when no command specified" behaviour :-|

**Comment by natemcmaster** [comment]
Were you able to find a solution to your problem? Or do you still think there are changes needed in the CLU library to support your scenario?

**Comment by skolima** [comment]
For NuKeeper we've changed the "default - no parameters" behaviour to show the help listing. So, 
gave up on the workaround, to be honest, as not getting the options parsed would be even more surprising behaviour.  https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper/Program.cs#L45

**Comment by natemcmaster** [comment]
Ok. I'm going to close this since I don't plan on making changes to support this scenario. I don't think it's a common enough.
