### ISSUE TITLE
Command alias

### ISSUE THREAD

**Issue by AnthonySteele** [natemcmaster/CommandLineUtils#128]
Allow more than one string for the same command.

**Is your feature request related to a problem? Please describe.**

In `NuKeeper` we have the command `organisation` which is problematic as it is long and has variant spellings. We would like to abbreviate to `org` while keeping the longer version of the command. Similarly `repo` for `repository`.

**Describe the solution you'd like**

Specify more than one name in the subcommand attribute.

**Describe alternatives you've considered**

You can add the same command more than once, e.g.
````
    [Subcommand("org", typeof(OrganisationCommand))]
    [Subcommand("organisation", typeof(OrganisationCommand))]
````

However this produces repetitive help text as if these are two independant commands, which they are not.

**Comment by natemcmaster** [comment]
This is definitely something I've been thinking about doing. Was waiting for someone to say they wanted it. Let's do this for 2.3.0, which I'm hoping to finish up in a few weeks.
