### ISSUE TITLE
Parse options and commands simultaneously.

### ISSUE THREAD

**Issue by hpractv** [natemcmaster/CommandLineUtils#130]
**Is your feature request related to a problem? Please describe.**
When I specify an option and a command, the option is ignored at arg parsing time.
Example. I'm am trying to do `app.exe --Verbose true ExecCmd -Option 1` but the verbose argument isn't getting set.

**Describe the solution you'd like**
I'm not sure if this is by design or a bug, but I'd like to parse the option flag as well as the command args.

**Describe alternatives you've considered**
N/A

**Additional context**
This is because there are some options that are applicable to all the command like verbose, debug, or some other root level argument.  It would be great to be able to set this at the parent class/attribute level, instead of having to add this to every class and subcommand class.

**Comment by atruskie** [comment]
@hpractv can you post an example of your program?

Here's an example from the samples folder that should be similar to what you're trying to achieve

https://github.com/natemcmaster/CommandLineUtils/blob/master/docs/samples/subcommands/inheritance/Program.cs

**Comment by hpractv** [comment]
Here is sample code for what I am seeing:

```
void Main()
    {
    
        var args = new string[] {
            "-v", "Print", "-s", "Hello World!"
            };
        CommandLineApplication.Execute<Settings>(args);
    
    }
    
    [HelpOption]
    [Command,
        Subcommand("Print", typeof(PrintSomething))]
    class Settings
    {
        [Option("-v", Description = "Verbose")]
        public bool Verbose { get; }
    
        public class PrintSomething{
            [Option("-s", Description = "The thign to print.")]
            public string Something { get; }
    
            public void OnExecute()
            {
                Console.WriteLine($"Something: {Something}");
            }
        }
    
    
        public void OnExecute()
        {
            Console.WriteLine($"Verbose: {Verbose}");
        }
    }
```

I would have expected this as the results:
```
Verbose: True
Something: Hello World!
```

But only `Something: Hello World!` is coming back.  The OnExecute for the `Settings` class is never being hit.  Particularly it looks like we should be able to call `application.exe [option] [command]` rather than `application.exe [option|command]`.

**Comment by natemcmaster** [comment]
I see. You're expecting inheritance behavior. Like @atruskie suggested, a full sample of this behavior can be seen here: https://github.com/natemcmaster/CommandLineUtils/blob/master/docs/samples/subcommands/inheritance/Program.cs. CLU doesn't do inheritance automagically for you, so your sample should be adjusted like this to get inheritance behavior.

```
void Main()
    {
    
        var args = new string[] {
            "-v", "Print", "-s", "Hello World!"
            };
        CommandLineApplication.Execute<Settings>(args);
    
    }

	[Subcommand("Print", typeof(PrintCommand)]	
	class Settings : CommandBase
	{ }
    
    abstract class CommandBase
    {
        [Option("-v", Description = "Verbose")]
        public bool Verbose { get; }  
    
        public virtual void OnExecute()
        {
            Console.WriteLine($"Verbose: {Verbose}");
        }
    }

    
    class PrintCommand : CommandBase
	{
        [Option("-s", Description = "The thign to print.")]
        public string Something { get; }
    
        public override void OnExecute()
        {
			base.OnExecute();
            Console.WriteLine($"Something: {Something}");
        }
    }
```

**Comment by hpractv** [comment]
Hmmm...it's not the pattern I was hoping to implement, but it's not too bad to work around.  Thank you.

**Comment by natemcmaster** [comment]
@lunim have you looked at this sample? https://github.com/natemcmaster/CommandLineUtils/blob/master/docs/samples/subcommands/inheritance/Program.cs

**Comment by lunim** [comment]
@natemcmaster Thanks for the link to the sample.  I was able to get something working, it might be useful to have some automatic handling in the future.

Thanks again!

**Comment by eBerdnA** [comment]
I need to attach to this thread because somehow parsing commands and options in combination with inheritance doesn't seem to work the way I expected or the example suggests.

To demonstrate my issue I created a simple gist: https://gist.github.com/eBerdnA/e181e28e918a0ba0d98bb5fb2e2d18a0

Using __-v__ as the first argument doesn't work in combination with a command. Using __-v__ after a command works.

Am I overlooking something?

**Comment by natemcmaster** [comment]
Thanks for the repro @eBerdnA. This looks like a bug in the parser. These should be equivalent in the example you provided:
```
"-v", "Print", "-s", "Hello World!"
"Print", "-v",  "-s", "Hello World!"
```

**Comment by natemcmaster** [comment]
So, took a closer look. What is happening is correct, but not intuitive. It think we can make a tweak to the library to better match expectations.

Here is what happens, and what I think is unexpected behavior. Given:

```c#
	[Subcommand(typeof(PrintCommand))]	
	class Settings : CommandBase
	{ }
    
    abstract class CommandBase
    {
        [Option]
        public bool Verbose { get; }  
    
        public virtual void OnExecute()
        {
        }
    }

    
    class PrintCommand : CommandBase
	{
        public Settings Parent { get; }

		public override void OnExecute()
		{
			Console.WriteLine($"this.Verbose        = {this.Verbose}");
			Console.WriteLine($"this.Parent.Verbose = {this.ParentVerbose}");
		}
    }
```

The result:
```
> "-v", "Print" 
this.Verbose        = false
this.Parent.Verbose = true
```

```
> "Print", "-v" 
this.Verbose        = true
this.Parent.Verbose = false
```

To fix this, the `OptionAttribute` convention is going to need to understand the hierarchy of types and inherit values. I would expect this behavior:

```
> "-v", "Print" 
this.Verbose        = true
this.Parent.Verbose = true
```

```
> "Print", "-v" 
this.Verbose        = true
this.Parent.Verbose = false
```

```
> "-v", "Print", "-v:false" 
this.Verbose        = false
this.Parent.Verbose = true
```
