### ISSUE TITLE
How to Create A Standalone Command/Application

### ISSUE THREAD

**Issue by rohan-buchner** [natemcmaster/CommandLineUtils#14]
I know this isn't really the forum for this, but currently I am using this project my small CLI util. But so far I can only find resources online, that indicate that when I want to run a dontet console app, I need to invoke it as such:

`dotnet my-data-loader.dll --foo bar` or during debug/dev `dotnet run -- --foo bar`

Are there any docs / resources online that use this project (either in its current or prior states), that explain how to go from the examples above to something like:

`my-data-loader --foo` .

Thanks in advance :)

**Comment by natemcmaster** [comment]
Yup, there are docs for this. This one has step-by-step examples of how to do this: https://docs.microsoft.com/en-us/dotnet/core/deploying/.
