### ISSUE TITLE
Support counting of bool/flag variables

### ISSUE THREAD

**Issue by lunim** [natemcmaster/CommandLineUtils#143]
I am looking to get a count of a specific flag.  For example, I would like to support the ability to specific -v, -vv, -vvv (etc) and get a count of that.

I have tried to specify the following, but this is not supported:

`        [Option("-v", "Verbose", CommandOptionType.NoValue)]
        public bool[] Verbose { get; }`

`        [Option("-v", "Verbose", CommandOptionType.MultipleValue)]
        public int Verbose { get; }`

**Comment by natemcmaster** [comment]
I'd accept a PR for this.

**Comment by natemcmaster** [comment]
Usage:
```
[Option("-v", "Verbose")] public bool[] Verbose { get; }
```
You should be able to use `Verbose.Length` to see how many times the flag was specified.
