### ISSUE TITLE
Is CommandLineApplication.Parse supposed to trigger validation?

### ISSUE THREAD

**Issue by thomaslevesque** [natemcmaster/CommandLineUtils#149]
I'm using CommandLineUtils to parse command line options, but I don't want to use the library's execution engine, because I don't want to refactor the existing code to fit that model. So I'm using the `Parse` method like this:

            var app = new CommandLineApplication(throwOnUnexpectedArg: false);
            var configurationOption = app.Option<string>(
                "-c|--configuration",
                "The build configuration",
                CommandOptionType.SingleValue,
                option => option.Accepts(builder => builder.Values("Debug", "Release")));
            app.Parse(args);
            var configuration = configurationOption.HasValue() ? configurationOption.Value() : "Release";

However, `option.Accepts(builder => builder.Values("Debug", "Release"))` seems to have no effect. It looks like validation isn't run. Is this the expected behavior? If not, how could I achieve what I'm trying to do?

I know I could just check the value manually, but I was hoping to take advantage of CommandLineUtils' validation mechanism.

**Comment by natemcmaster** [comment]
Yes, this is the expected behavior. If you want to run validation manually, you can do this:
```c#
var parseResult = app.Parse(args);
var validationResult = parseResult.SelectedCommand.GetValidationResult();
```

FYI checkout what CommandLineApplication.Execute does: https://github.com/natemcmaster/CommandLineUtils/blob/2753a1cb77617cfd0022b0a74d1e98a101322daf/src/CommandLineUtils/CommandLineApplication.cs#L695-L712

**Comment by thomaslevesque** [comment]
Thanks!

**Comment by ai-fwd** [comment]
@natemcmaster / @thomaslevesque  GetValidationResult() is internal so it's not accessible. Am I missing something?

**Comment by natemcmaster** [comment]
That's a very good point. Do you need to run validation manually?

**Comment by ai-fwd** [comment]
@natemcmaster yes ideally I do. I'm doing something a little non-standard in that I'm using your library to build out a Slack App. Essentially in my scenario the command line is Slack. Commands need to be parsed and validated before being added to a queue for processing.
