### ISSUE TITLE
small feature: Add app.Use<TCommand>() syntax via extensions

### ISSUE THREAD

**Issue by t-smirnov** [natemcmaster/CommandLineUtils#15]
Simple fancy feature that allows working with util as with WebHostBuilder for ex.

**Comment by natemcmaster** [comment]
@t-smirnov to clarify, are you asking for this so you can use attribute binding on a type like this?

```c#
var app = new CommandLineApplication();
app.Use<MyCommand>();
app.Execute(args);

class MyCommand
{
   [Option]
   public string MyOption { get; set; }
}
```

**Comment by natemcmaster** [comment]
Closing as I'm not really sure what the ask was here. We can re-open and discuss more if you can clarify the ask.
