### ISSUE TITLE
Prompt.GetString is limited to 254 characters

### ISSUE THREAD

**Issue by leastprivilege** [natemcmaster/CommandLineUtils#150]
**Describe the bug**
I need to paste in a large string into Prompt.GetString(). The input is capped at 254 character.

I looked at the source code, and you using plain Console.ReadLine - so I am wondering if I can control the "buffer" somewhere more generally in .NET - any ideas?

thanks!

**Comment by leastprivilege** [comment]
OK - further investigation brings up this

> A line is defined as a sequence of characters followed by a carriage return (hexadecimal 0x000d), a line feed (hexadecimal 0x000a), or the value of the Environment.NewLine property. The returned string does not contain the terminating character(s). By default, the method reads input from a 256-character input buffer. Because this includes the Environment.NewLine character(s), the method can read lines that contain up to 254 characters. To read longer lines, call the OpenStandardInput(Int32) method.

https://docs.microsoft.com/en-us/dotnet/api/system.console.openstandardinput?view=netframework-4.7.2#System_Console_OpenStandardInput_System_Int32_

**Comment by leastprivilege** [comment]
I will try to do a PR in the coming days...

**Comment by TheConstructor** [comment]
Could not reproduce using .NET Core 2.1.403 (2.1.5) on Mac OS X. Would otherwise probably try to copy the TextReader-implementation of reading single characters to a StringBuilder. OpenStandardInput works ok with redirected STDIN, as well as Read while ReadKey will throw an exception.
