### ISSUE TITLE
Prompt User (ReadLine) if EXE Run Without Command Arguments

### ISSUE THREAD

**Issue by aherrick** [natemcmaster/CommandLineUtils#152]
I have a basic `subcommand ` structure App.

What I want is if the executable is run without parameters, I want the App to essentially `ReadLine `and allow the user to input the commands.

Is this possible with a flag perhaps?

See below for my basic App structure:

```
		public static int Main(string[] args)
		{
			var app = new CommandLineApplication();

			app.HelpOption(inherited: true);

			// Invite User
			app.Command("invite", inviteUserCmd =>
			{
				var tenantName = inviteUserCmd.Argument("username", "Users name.").IsRequired();

				inviteUserCmd.OnExecute(async () =>
				{
						// do work here
					});
			});

			// register user
			app.Command("register", registerUserCmd =>
			{
				registerUserCmd.OnExecute(async () =>
				{
						// do work here
					});
			});

			app.OnExecute(() =>
			{
				Console.WriteLine("Specify a command");
				app.ShowHelp();
				return 1;
			});

			return app.Execute(args);
		}
```

**Comment by aherrick** [comment]
Hey Nate yep exactly. So I just have the EXE output or run it from VS. No parameters whatsoever. 

I do believe its similar to #141. However I'm thinking prompt for all sub commands as well. 

Prompt all the way down.

**Comment by natemcmaster** [comment]
Ok, I'm going to leave this separate then. We can use #141 to discuss prompting for required, empty parameters. Prompting for subcommands is a separate thing I'll have to think about. I'm not sure what the user experience for that would like. Can you flesh out what you would expect the user interaction to look like?

**Comment by juan-carlos-diaz** [comment]
Hey Nate, I just implement something I call "interactive session" where you get into a loop collecting and executing commands and this can be used in case no args are pass to the app, like this:

        public static void Main(string[] args)
        {
            if(args.Length == 0)
                CommandLineApplication.ExecuteInteractive<Git>();
            else
            {
                // Regular execute call goes here
            }
        }

I create a PR for your consideration #159

**Comment by aherrick** [comment]
@juan-carlos-diaz this is exactly where my head was at... cool!

**Comment by natemcmaster** [comment]
This is the behavior of a REPL. I think adding an API for building a REPL is a great idea, but I don't think this should be part of `CommandLineApplication`. The space of opportunity (and problems to address) is big enough that I think we should design a `ReplApplication` API for this. I also don't think this will fit into the timeframe I had in mind for the 2.3 release. Can we spec out this feature a little more? Before I commit to putting this in a particular release?

The way I see it, there are 4 main areas that a good design will need to address.

R - (read). How to take user input and translate to meaningful commands. We can re-use some of the syntax parsing code used by `CommandLineApplication` for this, but we can't re-use all of it. We'll need new code to handling things like quotes, escape characters, multi-line input, etc. We get that all for free from the operating system when the command line app is directly invoked, but we don't get it in a REPL interaction.

E - (eval). `CommandLineApplication`, `CommandOption`, and `CommandArgument` are currently designed for a single evaluation. They store state, and are not really suitable for re-used in a looping evaluation environment. We can look into abstracting the state-less part of those commands into a new API that could be shared with the REPL. (Example, `CommandOption.Description` is stateless, `CommandOption.HasValue()` is not.) This could be done by splitting the current API into classes that define commands, parameters, etc., and another API which stores results of running commands.

We also need to think about how to evaluate commands. Users designing an app that can be a REPL or directly invoked may want to share a set of subcommands between the too. But they will also want an additional set of commands for the REPL environment. For example, "quit" or "exit".

P (print) - I think it's reasonable to expect a base set of functionality from a REPL interaction. Up-arrow to retrieve commands, escape to clear a line, shift+enter for multi-line input. An API for this could be called something like `ConsoleShell` and would handle the "UI" for this app.

The last part, L (loop) - users may wish to customize the looping behavior. We can include sensible defaults, of course, like an "exit" command and/or CTRL+D. But, users building their apps should still have the ability to define how this works.

I realize what I'm saying amounts to lots of work. I'm all for doing this feature, but let's just make sure we're on the same page before we dive into writing code. I'd like to make a good API that lets people build powerful REPLs using .NET.

Thanks,
Nate

**Comment by juan-carlos-diaz** [comment]
I'm for doing this feature too. The REPL idea is exactly what I has thinking.

I agree with the points in your post, and I'm ready to add some more ideas around the REPL core.

Let me know how can we continue.

Thanks,

JC

**Comment by natemcmaster** [comment]
@juan-carlos-diaz that's great! Since this is going to be a decent amount of work, I think the first thing to do is plan to work on the `feature/repl` branch together. This will likely take a few rounds of design and changes before it's ready. Also, the bar for merging stuff to this branch is pretty low, so party away.

I think the next step is to stub out the public API. We can do this over PRs. To get this started, this is the simple case I had in mind.

Shortest form:
```c#
public static int Main(string[] args)
{
    if (args.Length == 0)
        return ReplApp.Run<Git>();
    else
        // ...
}
```
As we start to think through the scenarios listed above, I expect advanced usage will start to look like this. (Just brainstorming, not a polished idea)
```c#
public static async Task<int> Main(string[] args)
{
    var app = new ReplApp();
    app.ConfigureOptions<Git>(); // uses the same conventions as CommandLineApplication
    app.AddCommand(new ClearHistoryCommand());
    app.SetExitCommand("exit", "quit", "q");
    app.HistoryManager.PersistHistoryToFile(Environment.GetEnvironmentVariable("HOME") + "/.myapphistory");
    app.ConsoleManager.RegistryKeyHandler(ConsoleKey.U, ConsoleModifiers.Control, (state) => dosomething());
    var cts = new CancellationTokenSource();
    app.ConsoleManager.RegisterCancelKeyHandler((state) => cts.Cancel());
    return await app.RunAsync(cts.Token);
}
