### ISSUE TITLE
Add Async Methods on CommandLineApplication that accept CancellationToken

### ISSUE THREAD

**Issue by bloudraak** [natemcmaster/CommandLineUtils#153]
**Describe the bug**
Consider the following code snippet:

```
public async Task<int> ExecuteAsync<TCommand>(string[] args, CancellationToken cancellationToken = default) where TCommand:class
{
    cancellationToken.ThrowIfCancellationRequested();
    
    var app = new CommandLineApplication<TCommand>();
    try
    {
        app.Conventions
            .UseDefaultConventions()
            .UseConstructorInjection(Services);

        return app.Execute(args);
        
    }
    catch (CommandParsingException e)
    {
        await app.Out.WriteLineAsync(e.Message);
        app.ShowHelp();
        return -1;
    }
}
```

The API doesn't expose `ExecuteAsync(args, cancellationToken)`. 

**To Reproduce**
There is no ExecuteAsync method that takes a cancellation token, which in turn complicates matters when `TCommand` implements an ExecuteAsync method, which uses a cancellation token.

**Expected behavior**
The expectation is that all methods on `CommandLineApplication` exposes async methods that accepts a cancellation token, so that a long running application can be cancelled. 

**Additional context**
The need exists to signal to the instance of `TCommand` that is running asynchronously that processing should be cancelled for whatever reason, e.g. the user pressed CTRL+C.

**Comment by bloudraak** [comment]
In addition, async methods don't support passing in a cancellation token.

**Comment by natemcmaster** [comment]
Stale bot closed this, but I'm interested in adding this in 3.0. Reopening.
