### ISSUE TITLE
Add support for arguments that begin with a dash (-)

### ISSUE THREAD

**Issue by ccheetham** [natemcmaster/CommandLineUtils#154]
I'd like to be able to pass arguments that begin with `-` and not have them treated as a short opt.

A common approach to this is to stop looking for options once you've encountered double dashes (`--`).

As an example, consider the `ls` command.

```
# long-format listing of the file named `README.md`
% ls -l README.md
-rw-r--r--  1 ccheetham  staff  1431 Sep 20 14:22 README.md

# listing of the files named `README.md` and `-l`
% ls -- -l README.md
ls: -l: No such file or directory
README.md
```
I've tried various string concat and escapes but can't seem to get the option parser to ignore my what-looks-like-an-option-but-is-really-an-argument.

**Comment by natemcmaster** [comment]
Have you tried using [AllowArgumentSeparator](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html?q=AllowArgumentSeparator#McMaster_Extensions_CommandLineUtils_CommandLineApplication_AllowArgumentSeparator)? It's not well documented, but this is how to enable support for the `--` convention. Everything after the `--` is dumped into the `RemainingArgs` list.

**Comment by ccheetham** [comment]
That did indeed meet the needs, ty!
