### ISSUE TITLE
Add OnHelp method convention

### ISSUE THREAD

**Issue by thomaslevesque** [natemcmaster/CommandLineUtils#156]
**Is your feature request related to a problem? Please describe.**

I want to provide custom help text in addition to the default text. This additional text isn't static, so I can't use `ExtendedHelpText`. I'm using attributes, not the builder pattern, so I also can't use `IHelpTextGenerator` (at least I didn't find how).
Currently my solution is this:
- suppress the default help option with `[SuppressDefaultHelpOption]`
- introduce my own help option like this:
    ```csharp
    [Option("-h|-?|--help", "Show help message", CommandOptionType.NoValue)]
    public bool ShowHelp { get; } = false;
    ```
- In my `OnExecute` method, I do this:
    ```csharp
    public void OnExecute(CommandLineApplication app)
    {
        if (ShowHelp)
        {
            app.ShowHelp();
            // (show additional help text here)
            return;
        }
        ...
    ```
It works, but it's not very convenient.

**Describe the solution you'd like**

It would be nice if there were a convention similar to the one for `OnExecute`: if a `OnHelp` method exists, it's called instead of showing the default help text. Like `OnExecute`, it would be able to accept some arguments such as the `CommandLineApplication`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by natemcmaster** [comment]
Seems like a good idea. This is something I would consider doing for 3.0. Right now, I'm focused on finishing up 2.3, but plan to do a 3.0 release later this year.

**Comment by thomaslevesque** [comment]
Cool! Would you accept a PR for this? Not making any promise, but I could give it a try.

**Comment by jcaillon** [comment]
I approve the idea, I have the exact same need 👍 

@thomaslevesque , as you stated you didn't find a way to use the the `IHelpTextGenerator` with the attribute pattern, I'm writing this to give you a solution : 

I replaced : 

```csharp
public static int Main(string[] args) => CommandLineApplication.Execute<Program>(args);
```
with : 

```csharp
public static int ExecuteMainCommand(string[] args) {
       using (var app = new CommandLineApplication<Program>(new CustomHelpTextGenerator(), PhysicalConsole.Singleton, Directory.GetCurrentDirectory(), true)) {
                app.Conventions.UseDefaultConventions();
                return app.Execute(args);
       }
}
```

The thing with your solution, is that if you use a validator on one of your property and it fails, you will never execute the `OnExecute` method and just display the validator error instead of the help.

**Comment by thomaslevesque** [comment]
Thanks @jcaillon!

**Comment by thomaslevesque** [comment]
Still interested in this. I haven't found the time to send a PR yet.
