### ISSUE TITLE
How to not throw when using the attribute API

### ISSUE THREAD

**Issue by psampaio** [natemcmaster/CommandLineUtils#16]
I've looked into the code and there doesn't seem to be a way to prevent throwing when you use the attribute API. I know you can set the property on CommandLineApplication instances, but CommandLineApplication.Execute\<Program\>(args) doesn't give you such object?

The alternative would be to add the argument on the Execute static methods and pass it on the ReflectionAppBuilder?

**Comment by natemcmaster** [comment]
Most of the options available on an instance of CommandLineApplication are available on CommandAttribute. Example usage:
```c#
[Command(ThrowOnUnexpectedArgument = false)]
class Program
{
    public static int Main(string[] args)
        => CommandLineApplication.Execute<Program>(args);
}
```

**Comment by psampaio** [comment]
I'll look into it. Thanks!
