### ISSUE TITLE
Use AzureSignTool from nuget.org

### ISSUE THREAD

**Issue by vcsjones** [natemcmaster/CommandLineUtils#160]
Per https://github.com/vcsjones/AzureSignTool/issues/31, AzureSignTool is now available via NuGet as a global tool. Apologies for the \*checks notes\* 3 month wait.

I don't have much intention of publishing build artifacts on GitHub anymore, so nuget is now the best place to get the latest bits.

**Comment by natemcmaster** [comment]
Thanks for the update! By the way, I added your tool to this list: https://github.com/natemcmaster/dotnet-tools
