### ISSUE TITLE
Make UnrecognizedCommandParsingException public

### ISSUE THREAD

**Issue by jcaillon** [natemcmaster/CommandLineUtils#161]
Hello,

First of all, thank you very much for maintaining this repository, you are awesome 👍 

**Is your feature request related to a problem? Please describe.**

I like the feature enabled with the parser setting `MakeSuggestionsInErrorMessage`, it sets the `NearestMatch` property when throwing a `UnrecognizedCommandParsingException`.

However, this exception `UnrecognizedCommandParsingException` is internal so the end user can't normally access the computed `NearestMatch` property. And this property is only used in the static `CommandLineApplication.Execute<TApp>(CommandLineContext context)` method; which I'm not using.

**Describe the solution you'd like**

When using a `CommandLineApplication` instance and the `Execute` method, we can only catch the high-level `CommandParsingException` exception. It would be nice to be able to catch `UnrecognizedCommandParsingException` instead and make use of the `NearestMatch` computed.

Maybe you already considered to make this public and thought this was a bad idea?

```csharp
try {
    using (var app = new CommandLineApplicationCustomHint<MainCommand>(HelpTextGenerator, console, Directory.GetCurrentDirectory(), true)) {
        app.Conventions.UseDefaultConventions();
        app.ParserSettings.MakeSuggestionsInErrorMessage = true;
        return app.Execute(args);
    } 
} catch (UnrecognizedCommandParsingException ex) {
    System.Console($"nearest match .... {ex.NearestMatch}")
} catch (CommandParsingException ex) {
    System.Console(ex.Message)
}
```

**Describe alternatives you've considered**

Re-implementing the closest match algo

**Additional context**

N/A

**Comment by natemcmaster** [comment]
I made it internal because I was still unsure about the naming and API. Now that I've had time to think about it, I'm okay making it public after one change: I want to make `UnrecognizedCommandParsingException.NearestMatch` a list of strings instead. The algorithm could return the top 2 or 3 matches. I'd be happy to take a PR with this change.

**Comment by jcaillon** [comment]
Sure thing, will do it as soon as possible.

**Comment by natemcmaster** [comment]
Thanks!
