### ISSUE TITLE
Help text generates inaccurate list of options

### ISSUE THREAD

**Issue by MrOnosa** [natemcmaster/CommandLineUtils#163]
Let's say I'm expecting an argument called Host. I might do it like this

```
[Option(Description = "client host", ShortName = "h")]
public string Host { get; }
```

Now, one of the default help options no longer works.
```
>dotnet doThing.dll -h
Specify --help for a list of available options and commands.
Missing value for option 'h'
```

But if I use the `--help` function, it says I could have used `-h` by default.
```
>dotnet doThing.dll --help
Usage: doThing [options]

Options:
  -h|--host <HOST>             client host
  -?|-h|--help                 Show help information
```

_Note: I am aware one can change the default help options manually, which is great! I'm suggesting this should occur automatically if one chooses not to override the default help options._

**Comment by atruskie** [comment]
From a different perspective: perhaps an exception should be thrown? In other cases where there are duplicate short options I believe an exception  is thrown:

https://github.com/natemcmaster/CommandLineUtils/blob/f498cc7383b27730fd24486510573ab61ccab9d6/test/CommandLineUtils.Tests/OptionAttributeTests.cs#L72-L92

**Comment by natemcmaster** [comment]
I'm gonna mark this as a bug. I think the help text generated here is wrong.

My thinking on a a non-throwing default help option was (1) avoid breaking existing users -- this wasn't added until 2.2 and (2) most users expect `--help` to just work. I could be convinced in 3.0 that the default help option should _only_ by `--help`, not `-?|-h|--help`.
