### ISSUE TITLE
Can I use config file for the global command?

### ISSUE THREAD

**Issue by w371987114** [natemcmaster/CommandLineUtils#170]
I create a command,and it neet a path; In the first time i can search all the drive and find the path
But it is not necessary to search all drive ever when i use the command 

so I neet to use config file to read the path convenient to the command
or is there a good way to realize my wishes?

or can i get the path where i excute the command?

**Comment by natemcmaster** [comment]
I'm not sure I understand the question. Can you share sample code demonstrating what you're trying to do?

**Comment by w371987114** [comment]
```
[Command(Name = "change", Description = "...")]
    [HelpOption("-h|--help")]
    [Subcommand(nameof(DataBase),typeof(DataBase))]
    public class Change
    {
        private int OnExecute(IConsole console)
        {
            console.Error.WriteLine("请输入具体的命令，输入 --help 以获得更多的信息.");
            return 1;
        }
        [Command(Name = "database", Description = "...")]
        [HelpOption("-h|--help")]
        private class DataBase
        {
            private int OnExecute(IConsole console)
            {
                var dicPath=new Dictionary<string,string>();
				
				//foreach the drive and find the xxx.config file
				//dicPath=xxx.config.path
				
				//load connection string from the dicPath
				var connectionStr=Utils.GetConnectionStrFromXMLPath(dicPath);//If there is a good way to save the dicPath,ever when i execute the command i can read the path from the good way instead of searching all drive to find the config path
             

                return 1;
            }
        }
    }
```
I want to save and get the dicPath from a config for the global  CommandLineUtils,or maybe I can use [regedit](https://www.nuget.org/packages/Microsoft.Windows.Compatibility) to realize the demand

**Comment by natemcmaster** [comment]
CommandLineUtils doesn't support config files. I'd recommend using [Microsoft.Extensions.Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/) to read config files. [Microsoft.Extensions.Configuration.Xml](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1#xml-configuration-provider) can parse XML files for you, and there are also providers for JSON, Azure Key Vault, and more.
