### ISSUE TITLE
System.ObjectDisposedException when trying to run with McMaster.Extensions.Hosting.CommandLine

### ISSUE THREAD

**Issue by TheConstructor** [natemcmaster/CommandLineUtils#177]
Every time, after successfully completing my program a System.ObjectDisposedException is thrown. 

The stack-trace points to [this line](https://github.com/natemcmaster/CommandLineUtils/blob/e81decdc29a474f0dbac5533854655947154e8f8/src/Hosting.CommandLine/HostBuilderExtensions.cs#L47) where the ExitCode is retrieved.

The problem seems to be, that host.RunAsync also calls host.WaitForShutdownAsync and hence the host is already being shutdown. As `state` is injected as object, a possible solution is to not retrieve it as a service, but to just use the local variable again.

Should you need more information, just ask me and I'll try to provide it.

**Comment by natemcmaster** [comment]
Let's see if https://github.com/natemcmaster/CommandLineUtils/commit/dface2ab96603ef130f8fbfdff68caf1416ae1af fixes this. A build with this change should be available on MyGet soon. https://www.myget.org/feed/natemcmaster/package/nuget/McMaster.Extensions.Hosting.CommandLine

**Comment by TheConstructor** [comment]
@natemcmaster seems fixed. Thank you!
