### ISSUE TITLE
Lacking documentation - RunCommandLineApplicationAsync

### ISSUE THREAD

**Issue by Allann** [natemcmaster/CommandLineUtils#180]
**Describe the bug**
In you documentation "CommandLineUtils/docs/docs/advanced/dependency-injection.md" in the GenericHost implementation it is invoked via the method RunCommandLineApplicationAsync.  I can't find how this method is implemented and was wondering if you could shed some light on this.

Or have I completely misunderstood this section, I assumed GenericHost was the new host in 2.1 (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1)

I am happy to update your doco with the answer.

**Expected behavior**
Be able to follow the documentation without errors.

**Additional context**
Using VS2017 15.9.2 and your latest nuget "McMaster.Extensions.CommandLineUtils" Version="2.2.5"

**Comment by natemcmaster** [comment]
I haven't released a version of support for generic host yet to nuget.org. This will require using a new package. This is something we should document before the 2.3 release.
