### ISSUE TITLE
"Anonymous" arguments

### ISSUE THREAD

**Issue by fleed** [natemcmaster/CommandLineUtils#184]
How should I specify an "anonymous" argument? Typically, the filename that it is used as input. E.g.:

```
mycli command subcommand <mytargetfile>
```

I'm currently using the `RemainingArguments` property, but it looks like a workaround and not a proper solution.

**Comment by natemcmaster** [comment]
So, something like this? Sample usage is `fake-npm config set <keyname> <keyvalue>`
https://github.com/natemcmaster/CommandLineUtils/blob/df0d28b57e51264b1bb2fdfe5e3211e77523f206/docs/samples/subcommands/builder-api/Program.cs#L17-L42

**Comment by fleed** [comment]
That was trivial, but for some reason I was confusing commands and arguments.. 😅

Thank you
