### ISSUE TITLE
Gracefully handle a parsing error?

### ISSUE THREAD

**Issue by vcsjones** [natemcmaster/CommandLineUtils#187]
Hopefully this is my last question.

If I have an attribute of type `int?` how do "gracefully" handle parsing failures? e.g.

```csharp
internal sealed class SignCommand {
  [Option("-mdop | --max-degree-of-parallelism", "The maximum number of concurrent signing operations.", CommandOptionType.SingleValue), Range(1, int.MaxValue)]
  public int? MaxDegreeOfParallelism { get; set; }
}
```

if I then do:

```
dotnet run -- sign -mdop cats!
```

I get:

>Unhandled Exception: McMaster.Extensions.CommandLineUtils.CommandParsingException: Invalid value specified for max-degree-of-parallelism. 'cats!' is not a valid number. ---> System.FormatException: Invalid value specified for max-degree-of-parallelism. 'cats!' is not a valid number.

Printed to the console. Is there a way to handle this more like a validation error that I am missing instead of printing a stack-trace to the console?

**Comment by natemcmaster** [comment]
You can catch `CommandParsingException` and print its message. Example: 

https://github.com/natemcmaster/CommandLineUtils/blob/895d9a8bb8446bf1a444d8a39df7825430c1a69e/src/CommandLineUtils/CommandLineApplication.Execute.cs#L52-L73

**Comment by TheConstructor** [comment]
This is not as easy if you use HostBuilderExtensions. Currently there every parsing error throws an uncatchable exception.

**Comment by natemcmaster** [comment]
I think https://github.com/natemcmaster/CommandLineUtils/pull/192 should make it easier to handle exceptions. This unwraps TargetInvocationException and makes improvements to exception handling in generic host.

@vcsjones let me know if you have more questions.
