### ISSUE TITLE
Unrecognized option error message - clustering?

### ISSUE THREAD

**Issue by VaclavK** [natemcmaster/CommandLineUtils#189]
**Describe the bug**
Unrecognized option '-a' error message seen with short named arguments being used - these are non flags (non Booleans)  and including multi character short name argument

based on the behaviour, it seems clustering is being applied but I am under the impression it should not have

**To Reproduce**
with 2.3 beta when running this argument set up

```
            [Option(
                Description = "name of the application to generate the POCO for",
                ShortName = "an",
                LongName = "appName",
                ShowInHelpText = true)]
            [Required] 
            public string AppName { get; set; }

            [Option(
                Description = "optional namespace to use for generated POCOs",
                ShortName = "n",
                LongName = "namespace",
                ShowInHelpText = true)]
            [Required]
            public string Namespace { get; set; }
```

and when invoking the app with -an blah -n namespace we get the error message as above
this is avoided when running with long name for app name --appName as in --appName blah -n namespace

it was not clear to me how to disable clustering as this was suggested in the original enhancement ticket

we run a 2 level command subcommand structure here e.g. (dotnet esw) keyvault generatePOCOs --appName a -n namespace .....

so at those levels I had (in OnExecute)

            app.ClusterOptions = false;

but that did not have the desired effect

**Expected behavior**

no error message displayed

**Comment by TheConstructor** [comment]
OnExecute is too late, as parsing is already done by the time it is invoked. How are you initializing the CommandLineApplication?

**Comment by TheConstructor** [comment]
Problem seems to be that you first long short-option is nested in a sub-sub-command and only command and sub-command are currently evaluated. If you want to stick with `CommandLineApplication.Execute<Program>(args)` you currently would need to add a long-short-named-option to e.g. Program (and set it to hidden).

**Comment by TheConstructor** [comment]
Judging by the ToDo-comment in https://github.com/natemcmaster/CommandLineUtils/blob/895d9a8bb8446bf1a444d8a39df7825430c1a69e/src/CommandLineUtils/Internal/CommandLineProcessor.cs#L40 I am uncertain that the workaround or #191 are permanent fixes however. Maybe @natemcmaster can tell you if at least setting `ClusterOptions = false` will be supported starting with 3.0.

**Comment by natemcmaster** [comment]
The TODO represents a tentative plan to make `ClusterOptions = true` the default always and required you to opt-out via `ClusterOptions = false`. I haven't committed to it yet thought.

Thanks for fixing this @TheConstructor. #191 is the right fix for now.

**Comment by TheConstructor** [comment]
Thank you for the clarification! I was uncertain about the "always" part.
