### ISSUE TITLE
Any plans to help with argument validation?

### ISSUE THREAD

**Issue by georgiosd** [natemcmaster/CommandLineUtils#19]
First and foremost required arguments (non-null/empty)?

Thanks :)

**Comment by natemcmaster** [comment]
Started to have a conversation on https://github.com/natemcmaster/CommandLineUtils/issues/12 about this subject. I'm open to suggestions, but haven't begun to implement anything yet.

**Comment by georgiosd** [comment]
Great, closing here, continuing there :)
