### ISSUE TITLE
Rename pkg just "CommandLineUtils"?

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#2]
Because shorter is better. 

I chose "McMaster.Extensions.CommandLineUtils" because it was very similar to the original "Microsoft.Extensions.CommandLineUtils". I don't really love that my name is in the title though. Plus long package names are annoying to type out all the way.

cc @ScotiaBaker

**Comment by ebekker** [comment]
How about `dotnet-cli` (or -clu) in keeping with the short and simple names of your other projects.  As far as actual namespace, I think you should own it!  :-)  Nobody will really have to type it out anyway, thanks to intellisense.

**Comment by natemcmaster** [comment]
`dotnet-cli` might be a confused with "dotnet.exe" itself.

Another idea: "Microsoft.Extensions.CommandLineUtils.**Contrib**". SEO and package search will match this name, but hopefully the .Contrib part would make it clear that it's not msft official.

cc @PinpointTownes - I've seen that you work on aspnet-contrib work a lot. Is there a good convention for "contrib" stuff?

I'm half tempted to named it "ICanHazCommandLine" just because naming stuff is hard.

**Comment by ebekker** [comment]
Excellent point -- forget my suggestion.  I also am not crazy about the .Contrib idea as that makes it kinda sound like it's a set of contributions to an abandoned project.

"All Your CLI Belong to Us"?  People may hate putting quotes around the package name to capture all the spaces though...
`CLISharp`?  `CLI#`?
`CommandLine.NET`?
`CommandLineUtils`?  Oh wait, didn't we start there?  Maybe that's the winner!

**Comment by natemcmaster** [comment]
Good point about .Contrib. Yeah, I tend to think of those as "experimental". This project is not experimental. It's a fork of a discontinued API.

I think "CommandLineUtils" might be a winner. CommandLine.NET is good too, but already taken on NuGet.org

**Comment by PinpointTownes** [comment]
> cc @PinpointTownes - I've seen that you work on aspnet-contrib work a lot. Is there a good convention for "contrib" stuff?

If there's one, I haven't found it yet 😅 

When I started working on aspnet-contrib (in 2014/2015), I simply adopted the same naming scheme as the one used by ASP.NET 5 - minus the `Microsoft.` prefix, of course - (e.g `AspNet.Security.OpenIdConnect.Server`).

Unfortunately this approach doesn't make much sense for the `Microsoft.Extensions.*` packages as you'd end up with something like `Extensions.XYZ` (which would be a terrible name... extensions of what? 😱)

Not being able to find a good name is one of the main reasons why I usually refuse contrib projects for "extensions" packages.

**Comment by natemcmaster** [comment]
> Unfortunately this approach doesn't make much sense for the Microsoft.Extensions.* packages as you'd end up with something like Extensions.XYZ

Yup, that's what I prefix it with my last name.

Well, I attempted to rename to just CommandLineUtils, but apparently NuGet.org won't let me snag that package id.

> The ID of your package, 'CommandLineUtils', is similar to the title of an existing package, which can cause confusion with our users. Please modify the ID of your package and try uploading again.

I guess that settles it. McMaster.Extensions.CommandLineUtils it is.
