### ISSUE TITLE
Replace parser with System.CommandLine

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#201]
The .NET team is working on creating a parsing library tentatively called System.CommandLine. See https://github.com/dotnet/command-line-api. 

I am considering replacing the parser in this library with System.CommandLine. It would be a substantial breaking change, but this parser has a much richer API for parsing along with some other nice features that I don't want to re-invent on my own.

This change needs more investigation.

**Comment by TheConstructor** [comment]
So I guess this depends in part on https://github.com/dotnet/command-line-api/issues/356. What would this project become? Configuration-infrastructure (I believe they currently don't have annotation support) and helpers?

**Comment by natemcmaster** [comment]
I gave this some more thought over the last few weeks. At this point, I'm not planning to make this change. (see also #206 for my thoughts on what will become of this project)
