### ISSUE TITLE
Allow subcommands to access parent models using Attribute API

### ISSUE THREAD

**Issue by ebekker** [natemcmaster/CommandLineUtils#205]
**Is your feature request related to a problem? Please describe.**
When using the Attribute API, and defining subcommands with distinct classes corresponding to each subcommand such as the [nested-types example](https://github.com/natemcmaster/CommandLineUtils/blob/master/docs/samples/subcommands/nested-types/Program.cs), is there a way for the *child* class corresponding to the subcommand invocation to get a reference to the outer/parent class model?  The parent class model represents common options that are applicable to all subcommands and should be accessible by all subcommand handlers.

**Describe the solution you'd like**
Intuitively, I assumed that you could get access to the parent model by declaring it the child subcommand `OnExecuted` method, something along the lines of:

```csharp
[Subcommand(typeof(Sub1), typeof(Sub2)]
class Cmd
{
    [Option]
    public bool CommonVerboseOption { get; }

    [Command("sub1")]
    class Sub1
    {
        [Option]
        public bool Sub1SpecificOption { get; }

        private void OnExecute(IConsole console, Cmd parent)
        {
            /* have access to this.* options and parent.* options */
        }
    }

    [Command("sub2")]
    class Sub2
    {
        [Option]
        public bool Sub2SpecificOption { get; }

        private void OnExecute(IConsole console, Cmd parent)
        {
            /* have access to this.* options and parent.* options */
        }
    }
}
```

**Describe alternatives you've considered**
For the time being, an alternative that seems to work well enough is to *capture* the instance of the parent model during its construction in a global variable that all subcommand handlers can access, but this seems wrong and violates a few different principles.  Example from above code:

```csharp
[Subcommand(typeof(Sub1), typeof(Sub2)]
class Cmd
{
    public static Cmd LastInstance { get; private set; }

    public Cmd() => LastInstance = this;

    [Option]
    public bool CommonVerboseOption { get; }

    [Command("sub1")]
    class Sub1
    {
        [Option]
        public bool Sub1SpecificOption { get; }

        private void OnExecute(IConsole console)
        {
            var parent = Cmd.LastInstance;
            /* have access to this.* options and parent.* options */
        }
    }

    [Command("sub2")]
    class Sub2
    {
        [Option]
        public bool Sub2SpecificOption { get; }

        private void OnExecute(IConsole console)
        {
            var parent = Cmd.LastInstance;
            /* have access to this.* options and parent.* options */
        }
    }
}
```

**Comment by natemcmaster** [comment]
> is there a way for the child class corresponding to the subcommand invocation to get a reference to the outer/parent class model? 

Yes, you can do this already. Add a property on subcommand types named 'Parent'. Here is a sample:

https://github.com/natemcmaster/CommandLineUtils/blob/2c1b7b8466997ef1286b5bb3aff3b624beacbdd5/docs/samples/subcommands/inheritance/Program.cs#L64-L85

**Comment by ebekker** [comment]
Ah, thank you, missed this in the samples.  Looks like the trigger for this `PropertyConvention` is both the property name and the type.  Thanks!
