### ISSUE TITLE
Additional command names are case-sensitive

### ISSUE THREAD

**Issue by jcaillon** [natemcmaster/CommandLineUtils#207]
**Describe the bug**

We have an option for the StringComparison used for options and arguments. But not for commands and subcommands.

Moreover, the base Name of a command is matched ignoring the case but if you define additional names, they are matched in case sensitive mode.

**To Reproduce**

Consider the following test:

```csharp
var app = new CommandLineApplication();
var cmd = app.Command("TEST", c => {
    c.OnExecute(() => 5);
});
cmd.AddName("TE");

app.OptionsComparison

var result = app.Execute("test");
Assert.Equal(5, result);

result = app.Execute("TEST");
Assert.Equal(5, result);

result = app.Execute("te");
Assert.Equal(5, result);

result = app.Execute("TE");
Assert.Equal(5, result);
```

It fails on the 3rd assertion because only the Name is case-insensitive, the additional names are not.

**How to solve the issue**

The issue is actually already pinned in a `TODO` here: https://github.com/natemcmaster/CommandLineUtils/blob/f2818351025b7800bdfe043fea4462dda575b1c1/src/CommandLineUtils/CommandLineApplication.cs#L1006

I suggest to:

- Create a property `public StringComparison CommandsComparison { get; set; }`
- Make it case insensitive by default since this is the actual behavior for the `Name` of a command
- give it the same purpose as `public StringComparison OptionsComparison { get; set; }`
- fix the name match in `src/CommandLineUtils/CommandLineApplication.cs`

@natemcmaster If you agree, I will do the merge request.

**Comment by natemcmaster** [comment]
Let's fix this in 2.3.2
