### ISSUE TITLE
CommandLineApplication.ExecuteAsync is inherently synchronous

### ISSUE THREAD

**Issue by rlvandaveer** [natemcmaster/CommandLineUtils#208]
**Describe the bug**
ExecuteAsync is not asynchronous. This seems related to bugs #153 and #196.

All of the ExecuteAsync methods eventually call the method below in CommandLineApplication.Execute.cs.

```c#
        public static Task<int> ExecuteAsync<TApp>(CommandLineContext context)
            where TApp : class
            => Task.FromResult(Execute<TApp>(context));
```

As you may well know, this method uses Task.FromResult to wrap a slew of synchronous calls in a task. This is inherently synchronous and effectively just deceives the consumer into thinking that their commands will execute asynchronously. 

**Expected behavior**
Instead of wrapping synchronous code, the asynchronous execution should have its own separate async path.

I've logged this as a bug because the methods exist, but I realize that with the amount of work necessary to remediate, this is likely a feature request.

**Comment by natemcmaster** [comment]
The library was originally written before async main was a thing C# supported. Async methods were retrofitted to the original API. I've tried hard to avoid breaking changes, but this one comes up enough that I think it's time to address it.Fixing this requires a breaking change. Now that I'm done with 2.3, I would consider taking a PR to fix this. If your willing to do the work, let me know (see https://github.com/natemcmaster/CommandLineUtils/issues/206).

cc @TheConstructor

**Comment by TheConstructor** [comment]
I a currently a bit busy, but may have a look at adjusting #196. In a way I would like to have a choice between sync and async and surely the library should behave appropriately.

**Comment by natemcmaster** [comment]
Stale-bot closed this, but I'm reopening because I think this is worth fixing.

**Comment by rlvandaveer** [comment]
Oddly enough, I just read your Deep-dive into .NET Core primitives a few days ago and it reminded about this issue (author, not subject matter). I'm glad you took it on.
