### ISSUE TITLE
GetPassword should return a SecureString

### ISSUE THREAD

**Issue by demosdemon** [natemcmaster/CommandLineUtils#21]
https://github.com/natemcmaster/CommandLineUtils/blob/1a843bd4db8d536e54f9d7ae9b58ebf53f16b521/src/CommandLineUtils/Utilities/Prompt.cs#L90

As title suggests, GetPassword should return a `SecureString` object instead of a plain string.

**Comment by natemcmaster** [comment]
I'd be open to a PR that adds a new method for this, but I'm not convinced that I should change the return type on the existing method. `SecureString` isn't available in .NET Standard 1.6, so .NET Core 1.x users need the `string` version.
```c#
public static SecureString GetPasswordAsSecureString(string prompt, ConsoleColor? promptColor = null, ConsoleColor? promptBgColor = null)
```

**Comment by demosdemon** [comment]
See #22
