### ISSUE TITLE
Unable to use SingleOrNoValue with MultipleValue

### ISSUE THREAD

**Issue by CraigSelbert** [natemcmaster/CommandLineUtils#213]
**Unable to Use `SingleOrNoValue` with `MultipleValue` Option**
For my command line application I added a option of `CommandOptionType.MultipleValue` with another option of `CommandOptionType.SingleOrNoValue`. Then when running the application it will never find the `SingleOrNoValue` option.  My workaround for this issue right now is to change `SingleOrNoValue` to `SingleValue` which allows this to work as expected and the method `HasValue()` works, so I am not sure  what to think here. 

Here is my code exactly

       var syncronizerCommandOption = commandLineApplication.Option<Syncronizers>("-s|--syncronizers <Aspera,Locale,Rating,Tag,Portal,Product,Content,Track,License>", "What syncronizers to run.", CommandOptionType.MultipleValue);
        syncronizerCommandOption.Accepts().Enum<Syncronizers>();

        var productSyncCommandOption = commandLineApplication.Option<ProductSync>("-ps|--productSync <Full,LastDay,Licensed>", "What products to sync.", CommandOptionType.SingleOrNoValue);
        productSyncCommandOption.Accepts().Enum<ProductSync>();

**To Reproduce**

Here is a test that when added to the `CommandLineProcessorTests.cs` will exhibit the issue of never finding the `SingleOrNoValue` option.

    [Fact]
    public void CanParseMultipleValueAndSingleOrNoValueParameters()
    {
        var app = new CommandLineApplication();
        var opt1 = app.Option("--param1", "param1", CommandOptionType.MultipleValue);
        var opt2 = app.Option("--param2", "param2", CommandOptionType.SingleOrNoValue);
        app.Parse("--param1", "one", "--param1", "two", "--param2", "three");

        Assert.Equal(new[] { "one", "two" }, opt1.Values);
        Assert.Equal("three", opt2.Value());
        Assert.Empty(app.RemainingArguments);
    }

I also created similar test that with two `SingleOrNoValue` options that also fails.

    [Fact]
    public void CanParseSingleOrNoValueAndSingleOrNoValueParameters()
    {
        var app = new CommandLineApplication();
        var opt1 = app.Option("--param1", "param1", CommandOptionType.SingleOrNoValue);
        var opt2 = app.Option("--param2", "param2", CommandOptionType.SingleOrNoValue);
        app.Parse("--param1", null, "--param2", "three");

        Assert.Equal((string)null, opt1.Value());
        Assert.Equal("three", opt2.Value());
        Assert.Empty(app.RemainingArguments);
    }

**Location of Issue (I think)**
I believe I tracked the issue down to the [CommandLineProcessor](https://github.com/natemcmaster/CommandLineUtils/blob/f0e482674b9125e4319eca2608a4009d0f33848f/src/CommandLineUtils/Internal/CommandLineProcessor.cs#L289). SingleOrNoValue is always parsing null.

I experimented with another path here for `SingleOrNoValue` with the following, and it works but breaks an [existing test](https://github.com/natemcmaster/CommandLineUtils/blob/f0e482674b9125e4319eca2608a4009d0f33848f/test/CommandLineUtils.Tests/CommandLineProcessorTests.cs#L256). 

    else if (option.OptionType == CommandOptionType.NoValue)
    {
        // No value is needed for this option
        option.TryParse(null);
    }
    else if (option.OptionType == CommandOptionType.SingleOrNoValue)
    {
        if (!_enumerator.MoveNext())
        {
            option.TryParse(null);
        }
        else
        {
            var nextArg = _enumerator.Current;
            if (!option.TryParse(nextArg.Raw))
            {
                _currentCommand.ShowHint();
                throw new CommandParsingException(_currentCommand,
                    $"Unexpected value '{nextArg.Raw}' for option '{name}'");
            }
        }
    }

I would be more than happy to create a code fix and issue pull request, but being that I am breaking an existing test, and I am not sure how this "should" work I felt I would just submit this bug and open up a conversation.

**Comment by natemcmaster** [comment]
```
var opt2 = app.Option("--param2", "param2", CommandOptionType.SingleOrNoValue);
```

The test is asserting a behavior which is unsupported. SingleOrNoValue's only supported usage is `--param2:value2` or `--param2=value2`. Using a space to separate the option `--param2` and the value `value2` is unsupported because it is ambiguous syntax.

**Comment by CraigSelbert** [comment]
@natemcmaster - I am sorry for not reading your awesome documentation. If I would have done that I could have saved yours and mine time. 

https://natemcmaster.github.io/CommandLineUtils/unstable/api/McMaster.Extensions.CommandLineUtils.CommandOptionType.html?q=SingleOrNoValue

**Comment by natemcmaster** [comment]
No worries, happy to explain 😄
