### ISSUE TITLE
How to determine if property was bound?

### ISSUE THREAD

**Issue by ChadJessup** [natemcmaster/CommandLineUtils#214]
I'm trying to find a good way to determine if a caller provided values upon startup, and what Properties those were bound to. If a property wasn't bound, then I fill in missing values based on a local configuration file. This allows certain cli arguments to be overridden on start, and use the configuration file for everything else.
It seems like the ResponseFileHandling mechanism could potentially work if I could override the handler to handle my custom format? But, I can't find a way to do that...
I can't scan properties after parsing has completed to look for unset values, due to default values of ValueTypes.
I can see ways to get the Options/Arguments, but no way to connect those to specific Property instances on a model.

I guess my issue is, is there a way to do any of the following?:
1. Swap out/Add new ResponseFileHandler functionality?
1. Get only command line arguments/options/commands provided by caller and what Properties would be/were bound?
1. Get MethodInfo for elements that were actually bound? The IMemberConvention on an Attribute triggers even if no value is provided... :(

**Comment by natemcmaster** [comment]
> If a property wasn't bound, then I fill in missing values based on a local configuration file.

If this is the primary problem you are trying to solve, could you do something like this?

```c#
private string _color;

[Option]
public string Color
{
   get => _color ?? MyFallbackConfigFileThing.GetValue("Color");
   set => _color = value;
}
```

> I can't scan properties after parsing has completed to look for unset values, due to default values of ValueTypes.

Try nullable value types.

**Comment by TheConstructor** [comment]
Or you could define your option as

    [Option("-i|--int", CommandOptionType.SingleValue)]
    public (bool valueProvided, int value) IntOption { get; }

and can check the bool to see if an option was explicitly set.

**Comment by ChadJessup** [comment]
Thank you for responding so quickly. I (rudely) asked my question, then went on vacation. It sounds like there are several solutions to my issue here.

I feel that nullable is probably the right way to go in my case.

I'll close this out, as there doesn't seem to be any true issue here (other than maybe a sentence or two calling this as a way to detect if user provided called).

If you think any of the options I listed above would be useful for this excellent project, I'd be glad to tackle one of them.

Thanks again!
