### ISSUE TITLE
When using Commands can't use Option with short name with more than 1 letter.

### ISSUE THREAD

**Issue by axelwass** [natemcmaster/CommandLineUtils#218]
**Describe the bug**
When using Commands can't use Option with short name with more than 1 letter.

**To Reproduce**
1.Create main class:
```
    [Subcommand(typeof(SCmd1))]
    [Command(Name = "Cmd")]
    class Program
    {
        public static int Main(string[] args)
            => CommandLineApplication.Execute<Program>(args);


        public void OnExecute(CommandLineApplication app)
        {
            app.ShowHelp();
        }
    }
```
2. Create command class:
```
    [Command("SubCommand1", "SC1")]
    class SCmd1
    {
        [Option(Description = "first option", ShortName = "o1", LongName = "option-1")]
        public string Option1{ get; } = null;

        public void OnExecute(CommandLineApplication app)
        {
            ...
        }
```

3. Run command `Program SC1 -o1 whatever`
4. Get error `Unrecognized option '-o'`

**Expected behavior**
I would expect to recognize the option "o1" and to set the property "Option1" with the value "whatever".

**Screenshots**
```
>JsonSqueezer sqz
Usage: JSONSqueezer squeeze [options]

Options:
  -i|--input <INPUT_PATH>                        Input JSON file to be sqeezed (requiered).
  -cf|--custom-fields-path <CUSTOM_FIELDS_PATH>  A JSON file with a list of paths to extract to the User extraction path.


>JsonSqueezer sqz -cf EnvironementConfiguration.conf.json -i "Export.json"
Specify --help for a list of available options and commands.
Unrecognized option '-c'
```

**Additional context**
Im using version 2.3.3

**Comment by natemcmaster** [comment]
Can confirm this is a bug. Give this pre-release build a try: https://myget.org/feed/natemcmaster/package/nuget/McMaster.Extensions.CommandLineUtils/2.3.4-build.22

**Comment by axelwass** [comment]
I see 2.3.3 as the last version in my VisualStudio project. Could you create a pre-release so that I can test this change?

Thanks.

**Comment by natemcmaster** [comment]
I already created a prerelease. Follow the link I shared in the previous
comment.

**Comment by axelwass** [comment]
I did not realize it was on your own feed. 
It works as expected now.

Thanks for your help Nate and keep up with the good work!

**Comment by natemcmaster** [comment]
Thanks for confirming. I'll push an update to nuget.org in a week or so.
I'm waiting to see if anything else is needed in the next patch.
