### ISSUE TITLE
Port custom argument splitting from gsscoder commandline

### ISSUE THREAD

**Issue by ptr727** [natemcmaster/CommandLineUtils#220]
Hi, I like the async and hosting features, and I'm porting my dotnet core commandline apps from gsscoder commandline to mcmaster commandline.

A few questions and issues.

Can you please add a custom commandline processor that solves the problem of ending \ getting incorrectly parsed. I use my own parser instead of args[], but it would be neat if you could have a similar generic implementation for all platforms.
See: https://github.com/gsscoder/commandline/issues/473
And: https://stackoverflow.com/questions/298830/split-string-containing-command-line-parameters-into-string-in-c-sharp

My app takes multiple commands and options, and I have internal logic to determine if a correct combination is used. If not, I emit the standard help text and exit.
How do I emit help text on demand, or get the help text in string to emit myself?
E.g. 
```
            // At least some action must be specified
            if (!commands.Process &&
                !commands.ReMux &&
                !commands.ReEncode &&
                !commands.WriteSidecar &&
                !commands.CreateTagMap &&
                !commands.Monitor &&
                !commands.CheckForTools)
            {
                // TODO : Write commandline help output on demand
                // https://github.com/gsscoder/commandline/issues/445#issuecomment-317901624
                ConsoleEx.WriteLineError("Failed to parse commandline, missing action.");
                ConsoleEx.WriteLineError(HelpText.AutoBuild(result, null, null));
                return -1;
            }
```

**Comment by natemcmaster** [comment]
> Can you please add a custom commandline processor that solves the problem of ending \ getting incorrectly parsed.

Can you elaborate? Based on what you've described so far, it seems like the problem is very specific to your code and not a general problem...but I also don't really understand what you're asking for.

**Comment by natemcmaster** [comment]
> How do I emit help text on demand, or get the help text in string to emit myself?

[CommandLineApplication.GetHelpText()](https://natemcmaster.github.io/CommandLineUtils/v2.2/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html?q=gethelptext#McMaster_Extensions_CommandLineUtils_CommandLineApplication_GetHelpText) returns the text in a string which you can write to the console yourself. You can also call to [CommandLineApplication.ShowHelp()](https://natemcmaster.github.io/CommandLineUtils/v2.2/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html?q=gethelptext#McMaster_Extensions_CommandLineUtils_CommandLineApplication_ShowHelp) to write the text to the console directly.

**Comment by ptr727** [comment]
> > Can you please add a custom commandline processor that solves the problem of ending \ getting incorrectly parsed.
> 
> Can you elaborate? Based on what you've described so far, it seems like the problem is very specific to your code and not a general problem...but I also don't really understand what you're asking for.

Please see:
https://github.com/gsscoder/commandline/issues/473

**Comment by natemcmaster** [comment]
The issue you referenced is not an issue with .NET or this library. Rather, this is just how command prompt parses backslashes and quotes. There isn't anything actionable here for this library.

**Comment by ptr727** [comment]
The way args[] work is broken in .NET, a custom implementation is required, why not offer one as an option vs. making everybody write their own, like I did?

**Comment by natemcmaster** [comment]
Copying for context https://github.com/gsscoder/commandline/issues/473#issuecomment-481870619

> @natemcmaster: ... Windows itself does the argument splitting, and it is interpreting `\"` to mean "oh, you wanted to escape the backslash. If I remember right, you can get around this with either of these invocations:
> 
> ```
> foo.exe "W:\\" "X:\\"
> foo.exe "W:^\" "X:^\"
> ```

This is an operating system behavior. The Command Prompt shell does the parsing before it launches a new process. To illustrate this, try playing with argument splitting using a different programming language. You'll get the same result. For example, if you put this code in a file named 'test.js' and ran NodeJS...
```js
for(let i in process.argv) {
    console.log(`${i} = ${process.argv[i]}`) ;
}
```
Result
```
C:\Users\nmcmaster>node test.js a b c
0 = C:\Program Files\nodejs\node.exe
1 = C:\Users\nmcmaster\test.js
2 = a
3 = b
4 = c

C:\Users\nmcmaster>node test.js "C:\" "D:\"
0 = C:\Program Files\nodejs\node.exe
1 = C:\Users\nmcmaster\test.js
2 = C:" D:"

C:\Users\nmcmaster>node test.js C:\ D:\
0 = C:\Program Files\nodejs\node.exe
1 = C:\Users\nmcmaster\test.js
2 = C:\
3 = D:\

C:\Users\nmcmaster>node test.js C:\ "D:\\"
0 = C:\Program Files\nodejs\node.exe
1 = C:\Users\nmcmaster\test.js
2 = C:\
3 = D:\
```


![image](https://user-images.githubusercontent.com/2696087/56016373-dc357080-5cb0-11e9-962d-7cfd2a696b46.png)

**Comment by natemcmaster** [comment]
That said, if there is something that this library can do to help with the other parts of the issue you opened, please elaborate more. Apologies if I'm being dense, but I don't understand what you're asking for.

**Comment by ptr727** [comment]
My users expect "C:\", C:\Foo\", etc. to just work.
They do not care about how windows works, or about workarounds.
I care about my users, so I make sure that the processing of the input works as the user expects it, i.e. I always custom split the commandline args.
I feel that the custom splitting could be in the lib and benefit all vs. my code.
But, you can close the issue, since I think we philosophically disagree about the expected behavior.

**Comment by natemcmaster** [comment]
While I agree that the way Command Prompt splits arguments can be counter-intuitive, I'd rather have this library operate consistently with how basically every other programming language operates on Windows, including C++, Java, Python, and NodeJS. 

That said, I would be willing to add an API which does the reverse of `ArgumentEscaper. EscapeAndConcatenate` and does the `string => string[]`, quote-aware splitting. Anyone who wanted to use this instead of the operating system's argument splitting would be welcome to do this before calling `CommandLineApplication.Execute(ArgumentEscaper.Split(Environment.CommandLine))`.
