### ISSUE TITLE
Use Pager for help text option only works on top-level help

### ISSUE THREAD

**Issue by scott-vincent** [natemcmaster/CommandLineUtils#221]
**Describe the bug**
The recent change to stop using the pager when displaying help text only works for top-level help. If I do, e.g. "command subCommand -h" the pager is still used.

**To Reproduce**
1. Using this version of the library '2.3.3'
2. Change was added here: [#216](https://github.com/natemcmaster/CommandLineUtils/pull/216)
3. With these arguments 'command subCommand -h'
4. Pager is still being used when app.UserPagerForHelpText = false

**Expected behavior**
The pager should never be used if UsePagerForHelpText is false.

**Comment by natemcmaster** [comment]
I would accept a PR to fix this. The workaround is to set UsePagerForHelpText=false on subcommands as well.
