### ISSUE TITLE
Negation for FilePathExistsAttributeBase e.g. FileExists

### ISSUE THREAD

**Issue by IanG** [natemcmaster/CommandLineUtils#222]
Hi there,

the package is really useful for command-line driven apps.

I've been making use of the DataNotations/Attributes for things like:

```[Required]
[FileExists]
[Option("-t|--document-template", CommandOptionType.SingleValue, Description = "The document template to use.")]
private string Template { get; } 
````

Sometimes I want to negate the meaning of these things e.g.  I'd like to check that a file/directory/path doesn't exist if I'm about to create something as an output from my application.

It would be nice to do something like:

```[Required]
[FileNotExists]
[Option("-o|--output-file", CommandOptionType.SingleValue, Description = "The name of the output file.")]
private string OutputFile { get; } 
```

Anyone else find this useful ?  If so I've forked the repo and I will create them.

**Comment by IanG** [comment]
I just triggered a pull request as I've added these new DataNotations/Attributes:

You can use these like so:

File:

````
[FileNotExists]
public string File { get; }
````

Directory:

````
[DirectoryNotExists]
public string Dir { get; }
````

Either:

````
[FileOrDirectoryNotExists]
public string Path { get; }
````

Maybe they are useful ?

**Comment by natemcmaster** [comment]
Fixed in https://github.com/natemcmaster/CommandLineUtils/pull/230
