### ISSUE TITLE
Help does not accurately describe Arguments

### ISSUE THREAD

**Issue by SteveBenz** [natemcmaster/CommandLineUtils#223]
If you want to create an app that can support a command-line like this: "rmdir -f -s foo" and you use this library, then "rmdir -?" will yield something like this:

```
Removes directories
 Usage: rmdir [arguments] [options]

Arguments:
  Directory     The directory to remove

Options:
  -f      Forcefully remove...
```

This confuses the readers on two front, first it's not real obvious how to draw the line between "[arguments]" and "[Directory]" and finally, it implies that "rmdir foo -f -s" is the way to write the command line, which is definitely not how most people like to order things.

It'd be nicer if the help read:

```
Removes directories
  Usage: rmdir [options] <directory>

Arguments:
  directory   The directory to remove

Options
  -f ...
```

**Comment by natemcmaster** [comment]
Fixed in #224
