### ISSUE TITLE
How to capture output/validation errors when running async

### ISSUE THREAD

**Issue by lunim** [natemcmaster/CommandLineUtils#225]
Following the documentation, I am invoking my application like so: `var execResult = await CommandLineApplication.ExecuteAsync<Program>(args);`.

I don't see a way to provide OnValidationError, or other options as the CommandLineApplication class doesn't seem to have a non-static ExecuteAsync: `var app = new CommandLineApplication<Program>();`

Is there a way for me to execute async from an async Task Main app?

**Comment by natemcmaster** [comment]
Nope. Not opposed to adding this, just haven't done it. As pointed out in https://github.com/natemcmaster/CommandLineUtils/issues/208, ExecuteAsync is actually just sugar and under the hood is still running synchronously.
