### ISSUE TITLE
ArgumentEscaper should escape empty string

### ISSUE THREAD

**Issue by ejball** [natemcmaster/CommandLineUtils#227]
`ArgumentEscaper.EscapeAndConcatenate` effectively ignores empty strings. It would make more sense to escape them (as `""`), but that would be a breaking change to anyone relying on the current behavior.

For what it's worth, this would fix it: https://github.com/ejball/CommandLineUtils/commit/0ed609251f209bbaa0d5af6735b7d0e0e1b8c669

**Comment by natemcmaster** [comment]
Would be happy to accept the fix as a PR :)

**Comment by ejball** [comment]
Done. #228
