### ISSUE TITLE
How to use "dotnet run" to commit a subject parameter?

### ISSUE THREAD

**Issue by JerryLeam** [natemcmaster/CommandLineUtils#238]
I want to run the CLI outside the VisualStudio and I knock into a trouble : the subject cannot commit to the Program.
My code is very simple:
```csharp
public class Program
{
    public static int Main(string[] args)
        => CommandLineApplication.Execute<Program>(args);

    [Option(Description = "The subject")]
    public string Subject { get; }

    [Option(ShortName = "n")]
    public int Count { get; }

    private void OnExecute()
    {
        var subject = Subject ?? "world";
        for (var i = 0; i < Count; i++)
        {
            Console.WriteLine($"Hello {subject}!");
            Console.ReadLine();
        }
    }
}
```
And then i just got in the Powershell and type in :
`dotnet run Test`
But the only thing came out is that:

Specify --help for a list of available options and commands.
Unrecognized command or argument 'test'

Maybe that's simple mistake in my usage of the "dotnet run", but i cannot find any docs relevant.
Thanks in advance :)

**Comment by natemcmaster** [comment]
Checkout https://natemcmaster.github.io/CommandLineUtils/docs/options.html

Correct usage is `dotnet run --subject test`

**Comment by natemcmaster** [comment]
@JerryLeam did that answer your question?

**Comment by JerryLeam** [comment]
Neat! That Really helps. And I'm sorry to reply so late 'cause I don't have time to try it out until now LoL.

 
---Original---

**Comment by natemcmaster** [comment]
Ok, let me know if you have any other questions. Closing as I believe the question was answered, but feel free to continue discussion on this thread.
