### ISSUE TITLE
Specifying options to CommandLineApplication when using RunCommandLineApplicationAsync

### ISSUE THREAD

**Issue by peppy** [natemcmaster/CommandLineUtils#241]
Hi,

I'm looking to change the `AllowArgumentSeparator` option in my aplication but can't seem to figure how to specify this when using a `HostBuilder`.

```csharp
public static void Main(string[] args)
{
    ServicePointManager.DefaultConnectionLimit = 128;

    Console.CancelKeyPress += delegate
    {
        Console.WriteLine("Cancellation requested!");
        cts.Cancel();
    };

    GetHostBuilder().RunCommandLineApplicationAsync<Program>(args, cancellationToken: cts.Token).Wait(cts.Token);
}

public static IHostBuilder GetHostBuilder()
    => new HostBuilder().ConfigureServices((context, services) => { services.AddSingleton(cts); });
```

**Comment by natemcmaster** [comment]
Try this

https://github.com/natemcmaster/CommandLineUtils/blob/9dd8d80b5658345f74d00e2e7824d78dbd804215/docs/samples/passthru-args/attributes/Program.cs#L6-7

**Comment by peppy** [comment]
Thanks, this seems to work. Unfortunately I guess I misunderstood the scope of the argument separator as it still does not allow me to pass in arguments starting with -. Is there a specific way to escape these?

```chsarp
[Command("command", "l", Description = "Lookup a user.")]
public class UserCommand : CommandWithHelp
{
    [Required]
    [Argument(0, Name = "lookup", Description = "Username, user id or email to perform action on")]
    public string Lookup { get; set; }
}
```

works fine:

`
dotnet run -- command "argument"
`

hoping for this to also work:

`
dotnet run -- command "-argument-"
`

but get

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Unrecognized option '-a') ---> McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized option '-a'
```

(or missing argument with `ThrowOnUnexpectedArgument` disabled)

**Comment by natemcmaster** [comment]
You're hitting this problem because dotnet run also supports `--`. I think you'll see it's missing from `args` array in Program.Main. Try running `dotnet bin/Debug/netcoreapp2.1/yourApp.dll -- command -argument-`

**Comment by peppy** [comment]
I did try this (using two `--` and also the way you suggested but the closest I can get is `The lookup field is required.`. This would suggest that because I am tying to parse the argument after the `--` argument separator, it is being ignored.

**Comment by natemcmaster** [comment]
> I misunderstood the scope of the argument separator as it still does not allow me to pass in arguments starting with -. Is there a specific way to escape these?

The argument separator is typically used in combination with `RemainingArguments`, which allows you to capture an arbitrary list of unprocessed args, as this sample shows:
https://github.com/natemcmaster/CommandLineUtils/blob/9dd8d80b5658345f74d00e2e7824d78dbd804215/docs/samples/passthru-args/attributes/Program.cs#L6-L14

Positional arguments cannot start with `-`, and there isn't a way to escape it that is built-in to the library. You could try writing your own escaping logic like this:
```c#
    private string _lookup;

    [Required]
    [Argument(0, Name = "lookup", Description = "Username, user id or email to perform action on")]
    public string Lookup
    {
      get => _lookup;
      set => _lookup = value.TrimStart('\\');
    }
```

`dotnet run command '\-value'`

**Comment by peppy** [comment]
I see, that makes sense. One of these solutions will work fine, thanks!
