### ISSUE TITLE
Synchronizing between VersionAttribute and assembly version

### ISSUE THREAD

**Issue by itn3000** [natemcmaster/CommandLineUtils#243]
**Is your feature request related to a problem? Please describe.**

I created the app and add `VersionAttribute` to command.
Currently, `VersionAttribute` attribute takes only string argument.
So when I update the app version, it must be fixed manually.
I think it somtimes may cause the correction leak.

**Describe the solution you'd like**

Add constructor taking `Type` to `VersionAttribute`.
Version description will be taken from assembly info
(get `Type.Assembly.GetName()` and use `AssemblyName.Name` and `AssemblyName.Version`)

**Comment by natemcmaster** [comment]
Have you tried the VersionOptionFromMember API? Here's a sample:

https://github.com/natemcmaster/CommandLineUtils/blob/0d682afcb28503d9ad2f74e3dac59a6a7bc1d5f8/docs/samples/subcommands/inheritance/Program.cs#L16-L21
https://github.com/natemcmaster/CommandLineUtils/blob/0d682afcb28503d9ad2f74e3dac59a6a7bc1d5f8/docs/samples/subcommands/inheritance/Program.cs#L60-L61

**Comment by itn3000** [comment]
Thank you very much, this is what I wanted.
