### ISSUE TITLE
Customize truthy and falsy responses for Prompt.GetYesNo

### ISSUE THREAD

**Issue by diegobfernandez** [natemcmaster/CommandLineUtils#244]
**Is your feature request related to a problem? Please describe.**
Customize truthy and falsy values for Prompt.GetYesNo.

**Describe the solution you'd like**
Make it possible to configure truthy and falsy values as well as hints for Prompt.GetYesNo.

**Describe alternatives you've considered**
In order to prevent API breakage add Prompt.GetBoolean that accepts customization.

**Additional context**
I have made the needed changes on a [fork](https://github.com/diegobfernandez/CommandLineUtils). If it seems worth let me know so I can open a PR.

**Comment by natemcmaster** [comment]
I'd be okay with this, but let's explore some API options that don't require 6 arguments on a method...that just seems like two many. I usually try to keep method arguments to 1 or 2.

**Comment by diegobfernandez** [comment]
I could get rid of truthyHint and falsyHint parameters by always using the first item of truthyValues and falsyValues as hints. Another change is making truthyValues and falsyValues optionals and providing default values. What do you think?

**Comment by natemcmaster** [comment]
> I could get rid of truthyHint and falsyHint parameters by always using the first item of truthyValues and falsyValues as hints

I like that idea. One less thing to configure.

> Another change is making truthyValues and falsyValues optionals and providing default values. What do you think?

What do you think about an API like this?
```c#
bool Prompt.GetBoolean(BooleanPromptConfig promptConfig);

class BooleanPromptConfig
{
   // ctor requires a prompt string and default answer. Everything else is an optional override
  BooleanPromptConfig(string prompt);

  bool? DefaultAnswer { get; set; } // if unspecified, a user MUST select a truthy or falsy response

  string[] TruthyResponses { get; set; }
  string[] FalsyResponses { get; set; }
}
```

Example usage:
```csharp
Prompt.GetBoolean(
  new BooleanPromptConfig("Do you like this?") { TruthyResponses = new [] { "yes", "y", "+1" }));
```
