### ISSUE TITLE
Multi-line option descriptions do not indent correctly.

### ISSUE THREAD

**Issue by kyle-rader** [natemcmaster/CommandLineUtils#246]
Given the following Option snippet:
```csharp
    [Option("-g|--glob",
        CommandOptionType.NoValue,
        Description = "Treat patterns as glob patterns. Only works with patterns given as cli arguments. " +
                    "Globbing will start at the current directory. " +
                    "Available glob syntax: https://github.com/dazinator/DotNet.Glob#patterns. " +
                    "Example: To match *.cs files recursively use -g and pass **/*.cs")]
    public bool Glob { get; set; }
```

The generated help output doesn't wrap the text within the description column making the options list difficult/unpleasant to read as shown below. (The lines that should be indented to the description column underlined in red)
![image](https://user-images.githubusercontent.com/4755420/60196894-119f2400-97f3-11e9-8be0-62116d1eb9af.png)

This is a nice feature of [COmmandLineParser](https://github.com/commandlineparser/commandline). How easy would this be to add to CommandLineUtils?

**Comment by DoCode** [comment]
My memory very vague, but I can remember that some years ago I created a PR for exactly this issue... Nate merged this. I am on vacation.
Please try search for some topics in this direction.

**Comment by kyle-rader** [comment]
I do see code [this line specifically](https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/HelpText/DefaultHelpTextGenerator.cs#L165) that does some of this.

The description for an attribute however, must be a constant expression and currently this requires you to put in newlines yourself. That's nice for controlling where the padded line breaks are. However, I can't put in an `Enviornment.Newline` as that's dynamic and so I have to choose either `\n` or `\r\n` meaning that the help text is going to be wrong on either Mac or Windows (and in my case - I first tried adding no newlines expecting it to insert line breaks automatically as needed based on the console width like CommandLineParser does.

**Comment by natemcmaster** [comment]
I'm on vacation for 2 weeks without a laptop, so haven't looked at this closely. I'll take a closer look when I get home. In the meantime, if you come up with a good solution, feel free to make pull request.
