### ISSUE TITLE
Deprecate an option's name

### ISSUE THREAD

**Issue by dorfire** [natemcmaster/CommandLineUtils#247]
**Is your feature request related to a problem? Please describe.**
I want to change an option's name, from `--old-name` to `--new-name`.
Problem: my application has pre-existing users, who might rely on the old option name in their scripts.

**Describe the solution you'd like**
A couple of rough ideas:

1. Instead of just `ShortName` and `LongName`, an Option could also have `PrevShotName` and `PrevLongName`, in which the developer can specify the deprecated-but-still-working names for an option.
2. Allow more than one `Option` attribute on a member

**Comment by natemcmaster** [comment]
I'm not sure this is a common-enough scenario to justify adding library support, but here is how I would do this. Let me know if this works for you.

```csharp
public class Program
{
   private bool _oldNameWasSet;

   [Option]
   public string OldName 
   {
      get => NewName;
      set
      {
          NewName  = value;
          _oldNameWasSet = true;
       }
   }
   
    [Option]
    public string NewName  { get; set; }
    
    public void OnExecute()
    {
        if (_oldNameWasSet) Console.WriteLine("--old-name is deprecated.");
    }
}
```
