### ISSUE TITLE
Error in OptionType as an attribute

### ISSUE THREAD

**Issue by rasikas** [natemcmaster/CommandLineUtils#249]
**Describe the bug**
There is a compile error when using `OptionType` as an attribute

**To Reproduce**
1. Version 2.3.4
2. I have a subcommand/command with the following attribute

```
        [Command("manager", Description = "Execute job manager for pending jobs")]
        private class JobManager
        {
            [Option("--type", Description = "Job type", OptionType = CommandOptionType.SingleOrNoValue)]
            public string JobType { get; set; }

```

**Expected behavior**
There should be no compile errors, but I'm getting the error - `Error	CS0655	'OptionType' is not a valid named attribute argument because it is not a valid attribute parameter type`

**Screenshots**
![image](https://user-images.githubusercontent.com/1381205/60631162-72f17380-9e41-11e9-979b-ef8261602557.png)

**Additional context**
This is probably because OptionType is nullable and it is not allowed as attribute parameter

**Comment by natemcmaster** [comment]
This is a C# limitation that I can't fix. Use the attribute constructor instead like this:

```csharp
[Option("--type", CommandOptionType.SingleOrNoValue  Description = "Job type")]
            public string JobType { get; set; }
```

**Comment by rasikas** [comment]
Thanks
