### ISSUE TITLE
Option with no value parsed incorrectly when using CommandOptionType.SingleValue

### ISSUE THREAD

**Issue by joostas** [natemcmaster/CommandLineUtils#250]
## Describe the bug
When option with type `CommandOptionType.SingleValue` and missing value is parsed it is treated differently depending on option position.
 ## To reproduce
1. Version 2.3.4
2. App setup with two options: `SingleValue` and `SingleOrNoValue`
```c#
static void Main(string[] args)
{
    var app = new CommandLineApplication();
    app.Option("-s|--single", "Single value option", CommandOptionType.SingleValue);
    app.Option("-o|--other", "Single or no value option", CommandOptionType.SingleOrNoValue);
    app.OnParsingComplete((parsedArguments) => {
        var singleOption = parsedArguments.SelectedCommand.Options.Find(o => o.ShortName == "s");
        var otherOption = parsedArguments.SelectedCommand.Options.Find(o => o.ShortName == "o");
        Console.WriteLine($"Single option value(--single): {singleOption.Value()}");
        Console.WriteLine($"Other option value(--other):{otherOption.Value()}");
    });
    Console.WriteLine("Executing: --single --other");
    try
    {
        app.Execute("--single", "--other");
    }
    catch(Exception ex)
    {
        Console.WriteLine($"Got expected parsing error: {ex.Message}");
    }
    Console.WriteLine("Executing: --other --single");
    try
    {
        app.Execute("--other", "--single");
    }
    catch(Exception ex)
    {
        Console.WriteLine($"Got expected parsing error: {ex.Message}");
    }
}
```
3. Executing app with same options but in different order gives different parsing results
```
> dotnet run
Executing: --single --other
Single option value(--single): --other
Other option value(--other):

Executing: --other --single
Got expected parsing error: Missing value for option 'single'
```
## Expected behavior

Options parsed same not depending on position: Always throwing exception about missing option value.

**Comment by natemcmaster** [comment]
This is the expected behavior of `CommandOptionType.SingleValue`. Given `--single <something>`, the parser will always use `<something>` as the value for the single option, regardless of whether it starts with `--` or not.

> Options parsed same not depending on position

This is true if you are providing a value to `--single`. For example, these are equivalent.

```
--single xyz --other
--other --single xyz
```

Let me know if this has answered your question.

**Comment by joostas** [comment]
Thanks for replay.
In [documentation](https://github.com/natemcmaster/CommandLineUtils/blob/master/docs/docs/options.md) options are defined with these characteristics:
>By default, options are optional and order does not matter,  but they can be made mandatory.

Seems that this is not true with options of type `SingleValue`. In this case order matters.

From my point of view it would be more correct behavior that this king of option will act same as other options and parsing of its value won't depend on order.

And regarding special case with `--` value option could be passed using existing syntax either `--single:--value` or `--single=--value`

**Comment by natemcmaster** [comment]
> Seems that this is not true with options of type SingleValue. In this case order matters.

I can see why you might interpret that sentence like that; the order of "--name value" matters. What doesn't matter is the order in which the name+value pair of arguments appear. These would be equivalent.
```
app.exe --single xyz --other
app.exe --other --single xyz
```

> From my point of view it would be more correct behavior that this king of option will act same as other options and parsing of its value won't depend on order.

I believe I have answered your question, and I don't plan to change the current behavior. There has been talk in https://github.com/natemcmaster/CommandLineUtils/issues/233 to the option name/value separator characters configurable. The current default is `' ', ';', and '='`.  Would that address your concern? If so, we could add that option, but otherwise I don't have an action item for this issue.

**Comment by joostas** [comment]
Ok, understood.
I will use option of type `SingleOrNoValue` instead of `SingleValue` and will add additional validation check to prevent empty values.
This will workaround described case: incorrect command parameters will be handled in the same way and won't depend on order:
```
app.exe --single --other value
app.exe --other value --single
```

**Comment by natemcmaster** [comment]
Ok. Closing this in favor of https://github.com/natemcmaster/CommandLineUtils/issues/252. I've prototyped allowing you to configure the parser so only `--name=value` or `--name:value` are allowed, but it will take a bit more work and possible a breaking change or two to make this work well, so I've put this in the 3.0 milestone.
