### ISSUE TITLE
Dynamic extended help

### ISSUE THREAD

**Issue by richardschneider** [natemcmaster/CommandLineUtils#255]
I want to dynamically generate the `ExtendedHelpText`  for a Subcommand.  For example the command `repo migrate <version>`, I want to create the text that shows the allowable version numbers and their description.

Something like
```csharp
string ExtendendHelp()
{
   var s = new StringBuilder("Versions:\r\n"));
   foreach (var v in Migration.Versions)
   {
      s.Append(v.Number);
      s.Append(' ');
      s.AppendLine(v.Description)
   }
   return s;
}
````

**Comment by natemcmaster** [comment]
Have you seen https://natemcmaster.github.io/CommandLineUtils/docs/help-text.html? You should be able to completely customize the help text by implementing `IHelpTextGenerator`. If you inherit from [DefaultHelpTextGenerator](https://natemcmaster.github.io/CommandLineUtils/v2.3/api/McMaster.Extensions.CommandLineUtils.HelpText.DefaultHelpTextGenerator.html), you don't have to write the whole help txt generation from scratch.

By the way, are you using the attribute or builder API?

**Comment by richardschneider** [comment]
Thanks for the fast reply.  So if I change my subcommand class to inherhit from `DefaultHelpTextGenerator` and change my `ExtendendHelper` method to override `GenerateFooter` then all will work.  Thanks you.

I'm using the attributes.

**Comment by richardschneider** [comment]
I tried overriding `GenerateFooter` to print the versions and it is never called. Obviously I'm missing something.

 See what I did in https://github.com/richardschneider/net-ipfs-engine/pull/134

**Comment by natemcmaster** [comment]
Sorry my last comment was not clear enough. I would recommend reading the section in https://natemcmaster.github.io/CommandLineUtils/docs/help-text.html about "Custom help text". You will need to implement the `IHelpTextGenerator` on a separate class, not the command class. Super simplified example:

```c#
public class Program
{
   public static int Main(string[] args)
   {
 		var app = new CommandLineApplication<Program>();
		app.Conventions.UseDefaultConventions();
        app.HelpTextGenerator = new MyHelpTextGenerator();
        return app.Execute(args);
	}

	[Option]
	public string Name { get; set; }

	public void OnExecute() {  }
}

class MyHelpTextGenerator : DefaultHelpTextGenerator
{
	protected override void GenerateFooter(CommandLineApplication application, TextWriter output) { }
}
```

**Comment by richardschneider** [comment]
Thanks again for you reply.  My issue is that I want to only generate the extra help text when a specific subcommand is asking for help.

**Comment by natemcmaster** [comment]
You can do that using pattern matching.
```c#

class MyHelpTextGenerator : DefaultHelpTextGenerator
{
	protected override void GenerateFooter(CommandLineApplication application, TextWriter output)
	{
		if (application is TheSpecificCommandIWant cmd)
			output.Write(cmd.GetExtendedHelpText());
		else
			base.GenerateFooter(application, output);
	}
}
```

**Comment by richardschneider** [comment]
I changed Main to set the `app.HelpTextGenerator` to my own class that derives from DefaultHelpTextGenerator.  It is never being called. 

Do you have a test/example that works with Subcommand(string, Type) and generates specific help text for the Subcommand?

**Comment by natemcmaster** [comment]
Ah, you probably hit one of those goofy bugs this library has in subcommand inheritance. Try changing the order in which HelpTextGenerator is assigned.
```c#
var app = new CommandLineApplication<Program>
{
    HelpTextGenerator = new MyHelpTextGenerator()
};
app.Conventions.UseDefaultConventions();
```

Also, I thought about it more and I think your pattern matching needs to look for `CommandLineApplication<T>`, instead of `T`.

```diff
class MyHelpTextGenerator : DefaultHelpTextGenerator
{
	protected override void GenerateFooter(CommandLineApplication application, TextWriter output)
	{
-              if (application is TheSpecificCommandIWant cmd)
-			output.Write(cmd.GetExtendedHelpText());
+              if (application is CommandLineApplication<TheSpecificCommandIWant> cmd)
+			output.Write(cmd.Model.GetExtendedHelpText());
		else
			base.GenerateFooter(application, output);
	}
}
```

**Comment by richardschneider** [comment]
Thanks, setting the `HelpTextGenerator` before the `UseDefaultConventions()` works.  My help generator is now working.

**Comment by natemcmaster** [comment]
I think I'm going to leave this open. There is probably a more intuitive way to extend the generated help text. I'm open to suggestions on this one...
