### ISSUE TITLE
2.4.0-beta.81 throws an ObjectDisposedException sometimes

### ISSUE THREAD

**Issue by LordMike** [natemcmaster/CommandLineUtils#261]
**Describe the bug**

I needed Ctrl-C support, so I was happy to find that the latest beta had just gotten that feature. But now I'm seeing an ObjectDisposedException - but only when running without a debugger. While debugging, I see nothing.

**To Reproduce**
I've produced this program that exhibits the behavior.

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using McMaster.Extensions.CommandLineUtils;
using Microsoft.Extensions.Hosting;

namespace ConsoleApp1
{
    class Program
    {
        static async Task<int> Main(string[] args)
        {
            return await new HostBuilder()
                .RunCommandLineApplicationAsync<MyProgram>(args);
        }
    }

    class MyProgram
    {
        protected int OnExecute(CommandLineApplication app, CancellationToken cancellationToken)
        {
            Console.WriteLine("Entered. Waiting 10s");
            for (int i = 0; i < 100; i++)
            {
                Thread.Sleep(100);
                if (cancellationToken.IsCancellationRequested)
                {
                    Console.WriteLine("Cancelled");
                    break;
                }
            }

            Console.WriteLine("Finished");

            return 0;
        }
    }
}
```

**Expected behavior**
Program terminates without exception.

**Screenshots**
When cancelling
![image](https://user-images.githubusercontent.com/1027111/62765212-ea916e80-ba8f-11e9-843d-45e455724912.png)

When running till end
![image](https://user-images.githubusercontent.com/1027111/62765282-17de1c80-ba90-11e9-81e5-800736a4cdb2.png)

**Additional context**

Stacktrace thrown.
```
Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at McMaster.Extensions.Hosting.CommandLine.Internal.CommandLineLifetime.<>c__DisplayClass11_0.<WaitForStartAsync>b__1(Object _, EventArgs __)
```

**Comment by dtsao** [comment]
I'm seeing the same issue using McMaster.Extensions.Hosting.CommandLine Version="2.4.0-beta.81"

**Comment by natemcmaster** [comment]
Looks like a bug. I'll take a look before I release 2.4.0-rc. I have limited free time to work on this library, so if someone else is interested in taking a look, I would happy to review and merge a PR to fix this.

**Comment by natemcmaster** [comment]
Give 2.4.0-beta.94 a try and let me know if it doesn't resolve your issue.

https://www.myget.org/feed/natemcmaster/package/nuget/McMaster.Extensions.CommandLineUtils/2.4.0-beta.94
```
Install-Package McMaster.Extensions.CommandLineUtils -Version 2.4.0-beta.94 -Source https://www.myget.org/F/natemcmaster/api/v3/index.json
```

**Comment by Allann** [comment]
I attempted to install, but received the error:
PM> Install-Package McMaster.Extensions.CommandLineUtils -Version 2.4.0-beta.94 -Source https://www.myget.org/F/natemcmaster/api/v3/index.json
The 'Source' parameter is not respected for the transitive package management based project(s) src\CodeGen. The enabled sources in your NuGet configuration will be used. 
Restoring packages for E:\GitRepos\CodeGen\src\CodeGen\CodeGen.csproj...
  GET https://api.nuget.org/v3-flatcontainer/mcmaster.extensions.commandlineutils/index.json
  OK https://api.nuget.org/v3-flatcontainer/mcmaster.extensions.commandlineutils/index.json 934ms
Install-Package : NU1102: Unable to find package McMaster.Extensions.CommandLineUtils with version (>= 2.4.0-beta.94)
  - Found 29 version(s) in nuget.org [ Nearest version: 2.4.0-beta.81 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages

And with v81 the error still occurs.

**Comment by natemcmaster** [comment]
Try using the package manager UI instead:
https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources

**Comment by Allann** [comment]
Thanks, I ended up doing that and installed beta 99 and I no longer see the exception during shutdown.

**Comment by natemcmaster** [comment]
Thanks for confirming.
