### ISSUE TITLE
Usage generator error

### ISSUE THREAD

**Issue by franklupo** [natemcmaster/CommandLineUtils#266]
Hi,
on show **usage** the result are different for windows and linux.
The multi line description of option in linux are correctly printed with space before new line, in windows no.

Best regards

**Comment by natemcmaster** [comment]
Hi @franklupo, can you provide some steps to reproduce the problem you are seeing? I need more detail to be 100% of what it is you expecting. Here is an outline of the kind of information I need: https://raw.githubusercontent.com/natemcmaster/CommandLineUtils/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by franklupo** [comment]
Hi,
i create a option 

```
            var opt = command.VmIdOrNameOption();
            opt.Description = @"The id or name VM/CT comma separated (eg. 100,101,102,TestDebian)
-vmid or -name exclude (e.g. -200,-TestUbuntu)
'all-???' for all VM/CT in specific host (e.g. all-pve1, all-\$(hostname)),
'all' for all VM/CT in cluster";
```

The output usage in linux:
```
  --vmid        The id or name VM/CT comma separated (eg. 100,101,102,TestDebian)
                -vmid or -name exclude (e.g. -200,-TestUbuntu)
                'all-???' for all VM/CT in specific host (e.g. all-pve1, all-\$(hostname)),
                'all' for all VM/CT in cluster
```

in windows:
```
  --vmid        The id or name VM/CT comma separated (eg. 100,101,102,TestDebian)
-vmid or -name exclude (e.g. -200,-TestUbuntu)
'all-???' for all VM/CT in specific host (e.g. all-pve1, all-\$(hostname)),
'all' for all VM/CT in cluster
```

Best regards
