### ISSUE TITLE
Unescape parameters or have access to raw input

### ISSUE THREAD

**Issue by daneel3001** [natemcmaster/CommandLineUtils#268]
I would like to be able to pass JSON objects as parameters. Such an example would be:
 -m {"foo":{"bar":"baz"}}

Unfortunately what I do get is:
 {foo:{bar:baz}}

I appreciate it should be possible to do this as I have only discovered this library today after noticing that it's based on a now paused project so my apology if there is a simple way to achieve this.

**Comment by daneel3001** [comment]
I will reply to myself if I may.
It is possible to use single quote to defeat the double quote removal.
So there is a workaround though, such as:
 -m {foo:{bar:'baz'}}

**Comment by natemcmaster** [comment]
You already have access to raw input at the point where Program.Main receives `string[] args`. Try putting a debugger there before you pass the args to CommandLineApplication.Execute. I think what you'll see is that the raw args have the double quotes removed. This is what most command line shells (bash, command prompt, zsh) do with double quotes.

**Comment by kyle-rader** [comment]
Like Nate said, the Shell is removing your quotes. You have to pass them
escaped:
"{\"key\":\"value\"}"
To get a single string that is valid JSON.

**Comment by daneel3001** [comment]
Hello
Indeed that's the case and escaping or using single quotes etc is my best option.
I should have indeed checked raw parameters before posting this issue!
Thanks!

**Comment by natemcmaster** [comment]
Happy to help! I'm glad you found this project useful :)

**Comment by daneel3001** [comment]
And thanks for creating this fork!
I will need to look at your roadmap as I have some features I would have liked which made me to some workarounds.
