### ISSUE TITLE
Combine Builder and Attributes

### ISSUE THREAD

**Issue by cpneale** [natemcmaster/CommandLineUtils#272]
Hi,

Apologies if I have missed it, but is there a way to combine builder and attribute approaches?

e.g.

`public class Program
{
    public static int Main(string[] args)
    {
        var app = new CommandLineApplication<Program>();
        var i = app.Execute(args);
        Console.ReadKey();
        return i;
    }

    [Argument(0, Name = "Names", Description = "Some Names")]
    [Required]
    public string[] Names { get; }

    [Option(ShortName = "c"), AllowedValues("1", "2")]
    public int Count { get; }

    private void OnExecute()
    {
        for(var i = 0; i < Count; i++)
        {
            Console.WriteLine($"Hello {Names[0]}!");
            Console.WriteLine($"Hello {Names[1] ?? "null"}!");
        }
    }
}`
Cheers
Chris

**Comment by cpneale** [comment]
I think I can use injection for what I need...

**Comment by natemcmaster** [comment]
Yes. You can add attributes using the builder approach by calling
```
var app = new CommandLineApplication<Program>();
app.Conventions.UseDefaultConventions();
```
