### ISSUE TITLE
Prompt - Add support for other data types

### ISSUE THREAD

**Issue by rmszc81** [natemcmaster/CommandLineUtils#274]
Hi all,

I'm using CommandLineUtils and it's very interesting how makes life easier. BTW, I saw the source code and there's no support for some data types, such as floating point numbers (double, decimal, whatever) and datetime.

Is there any plan for including support for these data types? 

If I want to contribute, what are the requirements?

Thanks a lot!

Regards,

[],

@rmszc81

**Comment by natemcmaster** [comment]
I don't have any plans, but I'm open to contributions. If you have a specific API you want to add, let me know.

One suggestion - to make pull requests go smoother, is generally best to work backwards from the API. Before going to the trouble of implementing anything, write up a small sample of a hypothetical usage and share here and we can go from there once we have an API designed.
