### ISSUE TITLE
Ctrl-C handling support added in 2.4.1 hangs 

### ISSUE THREAD

**Issue by devhawk** [natemcmaster/CommandLineUtils#286]
My code (running fine on v2.3.4). `LongrunningOperationAsync` starts a threadpool thread that runs until `CancellationToken.WaitHandle` is signaled. 

``` csharp
private async Task<int> OnExecuteAsync(IConsole console)
{
    try 
    {
        using (var cts = new CancellationTokenSource()) 
        {
            console.CancelKeyPress += (sender, args) => cts.Cancel();

            await LongrunningOperationAsync(console.Out, cts.Token)
                .ConfigureAwait(false);
        }

        return 0;
    }
    catch (Exception ex)
    {
        console.WriteError(ex.Message);
        app.ShowHelp();
        return 1;
    }
}
```

When I moved v2.4.1, CTRL-C no longer had any affect. The app kept running and I had to kill it via task manager.

As per the [release notes](https://github.com/natemcmaster/CommandLineUtils/releases/tag/v2.4.0) I tried adding a `CancellationToken` parameter to my `OnExecuteAsync` function which then in turn is passed to `LongrunningOperationAsync`:

``` csharp
private async Task<int> OnExecuteAsync(IConsole console, CancellationToken token)
{
    try 
    {
        await LongrunningOperationAsync(console.Out, token)
            .ConfigureAwait(false);
        return 0;
    }
    catch (Exception ex)
    {
        console.WriteError(ex.Message);
        app.ShowHelp();
        return 1;
    }
}
```

Now the background thread stops, but the command line app is hung and still needs to be shut down via task manager.

**Comment by devhawk** [comment]
Standalone repro attached
[CLUtest.zip](https://github.com/natemcmaster/CommandLineUtils/files/3643932/CLUtest.zip)

**Comment by devhawk** [comment]
[CLUtest.zip](https://github.com/natemcmaster/CommandLineUtils/files/3643935/CLUtest.zip)

standalone repro attached

**Comment by yang-xiaodong** [comment]
I have the same issue , when started Task in OnExecuteAsync, the command line will be blocked after receiving the cancellation.

**Comment by natemcmaster** [comment]
Thanks for the simple repro! I think I know what's wrong and have staged a hotfix. Can you give this build a try? 

https://dev.azure.com/natemcmaster/github/_packaging?_a=package&feed=github%40Local&package=McMaster.Extensions.CommandLineUtils&protocolType=NuGet&version=2.4.2-build.154&view=overview

**Comment by yang-xiaodong** [comment]
@natemcmaster I have tested it with version  `2.4.2-build`, it works now, thanks.

**Comment by natemcmaster** [comment]
Fixed with https://github.com/natemcmaster/CommandLineUtils/commit/3a86cab578b2e49ece275b896897e6974834f640. This will be released to NuGet.org in a few minutes as 2.4.2.

**Comment by devhawk** [comment]
:+1:
