### ISSUE TITLE
Feature Request: using CommandLine parsing from within a custom attribute

### ISSUE THREAD

**Issue by 3GDXC** [natemcmaster/CommandLineUtils#289]
I have a use case where I would like to parse a textual value (connection string options) from a custom attribute; it would be good to be able to use the CommandLine parser from within the attribute to populate attribute properties and/or validate the attributes values.

Please provide guidance on how/if this may  be achieved.

**Comment by natemcmaster** [comment]
I'm not sure I completely understand your request. Can you share a code snippet that shows what it would look like to use this hypothetical new feature?
