### ISSUE TITLE
[QA] Why this project / what about MS CliCommandLineParser

### ISSUE THREAD

**Issue by DoCode** [natemcmaster/CommandLineUtils#29]
***Only a simple question:***  
Why this further project, when Microsoft continues with this [command line parser](https://github.com/dotnet/CliCommandLineParser) (of the second generation)?

**Comment by natemcmaster** [comment]
See https://github.com/natemcmaster/CommandLineUtils/issues/1

**Comment by natemcmaster** [comment]
Closing for now. I'm certainly glad the dotnet team is working towards supporting https://github.com/dotnet/CliCommandLineParser. But, I plan to keep working on this, mostly as a hobby project, but also to support all those who have already built apps using the Microsoft.Extensions.CommandLineUtils library.
