### ISSUE TITLE
Documentation is incomplete for CommandAttribute

### ISSUE THREAD

**Issue by MisinformedDNA** [natemcmaster/CommandLineUtils#290]
**Describe the bug**
Documentation is missing as to how the highest level CommandAttribute is being used.

**To Reproduce**
1. Clone code 
2. Notice that [this line](https://github.com/natemcmaster/CommandLineUtils/blob/b92f20ef3c9ef8627431fdee104c7b2aaade62ac/docs/samples/subcommands/nested-types/Program.cs#L13) mentions the command "fake-docker":

```csharp
    [Command(Name = "fake-docker", Description = "A self-sufficient runtime for containers"), ...]
```

3. Build all
4. Try to figure out how "fake-docker" is used.

**Expected behavior**

Not sure, is "fake-docker" supposed to be the app name? A sub-command? Or should it not be there?

**Actual behavior**

`.build` directory doesn't contain anything named `fake-docker`

`dotnet .\NestedTypeSubcommands.dll fake-docker` results in the error:

> Unrecognized command or argument 'fake-docker'

**Comment by natemcmaster** [comment]
It's used in help text generation. Try running the sample with `--help` and you should see it mentioned there. The value is meant to match the name of the .exe for your app. I suppose the samples should be updated to indicate this.
