### ISSUE TITLE
How to have subcommands share a baseclass with arguments?

### ISSUE THREAD

**Issue by ajmcateer** [natemcmaster/CommandLineUtils#293]
I am writing a diagnostic utility that will have 8 or 9 subcommands each with their own subcommands with 8 various tests

All of these sub-sub commands will require the same starting argument the path to the diagnostic logs. I was trying to create a Base class to hold all the argument.

```
    [Subcommand(
        typeof(diag1Command),
        typeof(diag2Command))]
    public class CommandBase
    {
        [Argument(0)]
        [Required]
        public string File { get; }
    }
```

```
    [Subcommand(
        typeof(test1Command))]
    public class diag1Command : CommandBase
    {
        [Option("--userName")]
        public string userName { get; }

        private void OnExecute()
        {
            Console.WriteLine($"User is {userName} and the File is {File}");
        }
    }
```

I am starting the program like so 

`public static int Main(string[] args) => CommandLineApplication.Execute<CommandBase>(args);`

I keep getting

> Subcommand cycle detected: trying to add command of model CommandLineUtilityTest.diag1Command as its own direct or indirect subcommand'

How can I structure the app this way?

I have also tried having Program.cs be the starting point with all the subcommands but it then doesn't seem to know what to do with the argument I specify that is supposed to be shared.

**Comment by natemcmaster** [comment]
Question 1:
> How can I structure the app this way?

Try this
```csharp
[Subcommand(typeof(diag1Command), typeof(diag2Command))]
class Program {
   public static int Main(string[] args) => CommandLineApplication.Execute<Program>(args);
}

class diag1Command : CommandBase {
  // ...
}
class diag2Command : CommandBase {
  // ...
}

class CommandBase {
   [Argument(0)]
   public string File { get;  }
}
```

Question 2:
> I have also tried having Program.cs be the starting point with all the subcommands but it then doesn't seem to know what to do with the argument I specify that is supposed to be shared.

Can you elaborate? Can you share what you are specifying and what you expect the result to be?

**Comment by ajmcateer** [comment]
Hi @natemcmaster, Thanks for the quick response Question 2 was basiclly saying I tried what you recommended and got a different error I should have been more clear. When I configure it the way you said to I get.

> Specify --help for a list of available options and commands.
> Unrecognized command or argument 'C:\test.zip'

When I launch with this arguments
> C:\test.zip diag2 --userName=TestUser

Also if I use the way you recommend I get a Subcommand cycle detected

> Subcommand cycle detected: trying to add command of model CommandLineUtilityTest.CheckUserExists as its own direct or indirect subcommand

```

[Subcommand(
        typeof(CheckUserExists))]
    public class diag2Command : CommandBase
    {
        [Option("--userName")]
        public string userName { get; }

        private void OnExecute()
        {
            Console.WriteLine($"userName is {userName}");
        }
    }
```

```
    public class CheckUserExists : LdapCommand
    {
        private void OnExecute()
        {

            Console.WriteLine($"User is {userName} and the File is {File}");
        }
    }
```

I am going to have a lot of commands that can be run and I am trying to structure the app in a way that keeps it logical and lets me add arguments or options that every sub or sub-sub command needs without changing many files. Right now every command needs the zip location and every diag2 command needs a username but I don't know how things could change in the future and wanted an easy way of expanding.

**Comment by natemcmaster** [comment]
You're getting the cycle because C# attributes are inherited by subtypes. So when the library is evaluating your code, it sees:

```
types = [
{
  name =  "diag2Command"
  subcommands = ["CheckUserExists"]
},
{
  name =  "CheckUserExists"
  subcommands = ["CheckUserExists"]
}]
```

**Comment by natemcmaster** [comment]
So, you're trying to implement file _before_ the subcommand name? e.g. `myprogram.exe <filepath> diag2`. That's not currently a supported usage, but you should be able to invoke the subcommand as `myprogram.exe diag2 <filepath>` (...i think, didn't test it)

**Comment by ajmcateer** [comment]
Oh I completely blanked on the position arguments had to be in. Thanks, I don't really care what position they are in.

Is there anyway to have a subcommand of a subcommand?

**Comment by natemcmaster** [comment]
Happy to help!

Yes, subcommands can have subcommands. Here's a sample in test code that might be helpful: https://github.com/natemcmaster/CommandLineUtils/blob/0615346771c12c85fc535f06000a7d0399b3d13c/test/CommandLineUtils.Tests/SubcommandAttributeTests.cs#L51-L91
