### ISSUE TITLE
Supporting netcoreapp3.0 with McMaster.Extensions.Hosting.CommandLine

### ISSUE THREAD

**Issue by cwoolum** [natemcmaster/CommandLineUtils#294]
I am trying to use this library with `netcoreapp3.0`. I get a failure whenever I try to launch the app.

```
'Method 'UseServiceProviderFactory' in type 'Microsoft.Extensions.Hosting.HostBuilder' from assembly 'Microsoft.Extensions.Hosting, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'
```

I think this is because `McMaster.Extensions.Hosting.CommandLine.csproj` refers to Microsoft.Extensions.Hosting@2.1.0.

My main method looks like 

```csharp
  private static async Task<int> Main(string[] args)
        {
            return await new HostBuilder()
                 .ConfigureAppConfiguration((hostContext, configApp) =>
                 {
                     var tokenProvider = new AzureServiceTokenProvider();
                     var kv = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(tokenProvider.KeyVaultTokenCallback));

                     configApp.SetBasePath(Directory.GetCurrentDirectory());
                     configApp.AddJsonFile("appsettings.json", optional: true);
                     configApp.AddJsonFile(
                         $"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json",
                         optional: true);
                     configApp.AddCommandLine(args);

                     configApp.AddAzureKeyVault(
                       $"https://{configApp.Build().GetValue<string>("Vault")}.vault.azure.net/",
                       kv,
                       new DefaultKeyVaultSecretManager());
                 })

               .ConfigureServices((context, services) =>
               {
                   var provider = services.BuildServiceProvider();                 

                   services.RegisterDbContext();
               })

           .RunCommandLineApplicationAsync<Program>(args);
        }
```

**Comment by ppadial** [comment]
Im using this Library in a project that uses netcoreapp3.0 https://github.com/ppadial/netcore3-cli-sample and is working fine.

**Comment by cwoolum** [comment]
I think the issue is with using HostBuilder and `RunCommandLineApplicationAsync` which I'm not seeing in sample app.

**Comment by ppadial** [comment]
Hey @cwoolum , yes, sorry.

I was taking a look to the test folder, it is a Hosting project that looks using netcoreapp3
https://github.com/natemcmaster/CommandLineUtils/blob/0615346771c12c85fc535f06000a7d0399b3d13c/test/Hosting.CommandLine.Tests/McMaster.Extensions.Hosting.CommandLine.Tests.csproj#L4 and it's using the hostbuilder: https://github.com/natemcmaster/CommandLineUtils/blob/0615346771c12c85fc535f06000a7d0399b3d13c/test/Hosting.CommandLine.Tests/HostBuilderExtensionsTests.cs#L41

Reading the doc here (https://natemcmaster.github.io/CommandLineUtils/docs/advanced/generic-host.html) i've created an small app to verify it and looks working, this is the code:

```c#
using System;
using System.Threading.Tasks;
using McMaster.Extensions.CommandLineUtils;
using Microsoft.Extensions.Hosting;

namespace hostingdemocli
{
    class Program
    {
        static Task<int> Main(string[] args)
            => new HostBuilder()
            .RunCommandLineApplicationAsync<Program>(args);

        [Option]
        public int Port { get; } = 8080;

        private IHostingEnvironment _env;

        public Program(IHostingEnvironment env)
        {
            _env = env;
        }

        private void OnExecute()
        {
            Console.WriteLine($"Starting on port {Port}, env = {_env.EnvironmentName}");
        }
    }
}
```

This is the csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="2.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />
    <PackageReference Include="McMaster.Extensions.Hosting.CommandLine" Version="2.4.2" />
  </ItemGroup>
</Project>
```

Is it possible that your error came from an issue with another dependency in your project and HostBuilder? or a dependency injection issue?

**Comment by cwoolum** [comment]
Aaah, I see the problem. It doesn't work unless 

```<PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />```

 is explicitly specified. I didn't have that because `McMaster.Extensions.Hosting.CommandLine` was bringing it in previously. I've added a PR that brings in the correct version depending on if you are NetStandard 2.0 or 2.1. I can add the package explicitly until it get's merged in.

**Comment by ppadial** [comment]
Cool :)

**Comment by natemcmaster** [comment]
@cwoolum can you share a standalone repro? I'd like to know what is actually causing the issue. UseServiceProviderFactory isn't used anywhere in this code base, so I suspect there is actually something else in your dependency graph causing this issue.

**Comment by cwoolum** [comment]
I figured out what the issue is. Looking down my dependency tree, I have a reference to `Microsoft.Extensions.Diagnostics.HealthChecks` which refers to `Microsoft.Extensions.Hosting.Abstractions@3.0.0`. If I remove that reference everything works fine.

Here is a repo with a repro: https://github.com/cwoolum/294-repro

**Comment by natemcmaster** [comment]
Thanks for the repro!

* M.E.Diagnostics.HealthChecks@3.0.0 -> M.E.Hosting.Abstractions@3.0.0
* M.E.CommandLineUtils.Hosting@2.4.2 -> M.E.Hosting@2.1.0 -> M.E.Hosting.Abstractions@3.0.0 (*)

(*) - hoisted from 2.1.0 to 3.0.0

Here is the problem: https://github.com/aspnet/Extensions/issues/612. Microsoft.Extensions.Hosting.Abstractions made a breaking change between 2.1 and 3.0....they added a new method to an interface. NuGet is hoisting the .Abstractions package to a new version because of your dependency on M.E.Diagnostics.HealthChecks. M.E.Hosting@2.1.0 does not implement the new interface method added in https://github.com/aspnet/Extensions/issues/612, so .NET cannot use `HostBuilder@2.1.0` as an implementation of the interface `IHostBuilder@3.0.0`.

### Solutions

1. As proposed in #296, upgrade command line utils to use hosting 3.0
2. As commented above, .NET Core 3.0 users need to add an explicit reference to `<PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />`
3. Simplify CommandLineUtils's dependency to only rely on M.E.Hosting.**Abstractions**.

**Comment by natemcmaster** [comment]
I'm currently favoring solution (3) - see draft commit in https://github.com/natemcmaster/CommandLineUtils/commit/494bbc848b0c020ffa13062838b98e13052ba243. The **advantage** is that it maximizes compatibility. CommandLineUtils would not need to multi-target to support both 2.1 and 3.0. (It also fits with my philosophy on dependencies is that class libraries --- that is, class libraries should minimize dependencies and use the lowest version possible to maximize compatibility.) The **disadvantage** is that it's a packaging breaking change; anyone using CommandLineUtils doesn't explicitly depend on Microsoft.Extensions.Hosting would need to add a new package reference.

Thoughts?

**Comment by cwoolum** [comment]
I like option 3 but don't like introducing a breaking change unless this package version is going to jump to 3.x.. 

Would it be better to go with option 1 for now and then implement option 3 when a new major version this package is released so consumers aren't surprised? I can also change the framework further to lessen any side-effects. Instead of `netstandard2.2`, I can target `netcoreapp3.0`.

**Comment by natemcmaster** [comment]
I’m hesitant on option 1 because it seems odd to me that the version of the dependency should vary based on target framework. Microsoft.Extensions.Hosting and CommandLineUtils are both netstandard2.0 libraries. If we go with option 1, netcoreapp3.0 users are forced into a higher version of Hosting, even if they were trying to use Hosting 2.1 on netcorapp3.0 (a perfectly valid use case, btw.)

I think I’d like to wait on this one (so, do option 2), and revisit this for the next major version of CommandLineUtils.
