### ISSUE TITLE
How to get the console/output inside a command

### ISSUE THREAD

**Issue by ppadial** [natemcmaster/CommandLineUtils#295]
Hi,

What im trying to do is when i test the execution of my application, verify if an output is recorded.

For this, im using the model you can find in this project: https://github.com/ppadial/dotnet/tree/master/src/dotnet.cli

Basically i have a Bootstrapper (https://github.com/ppadial/dotnet/blob/master/src/dotnet.cli/CliBootstrapper%7BT%7D.cs) class that initialises the commandline application and can receive an IConsole, and i have an "InMemory" IConsole implementation (https://github.com/ppadial/dotnet/blob/master/src/dotnet.cli/Support/ConsoleInMemory.cs).

As you can see in this test, it works fine when the output is generated by the library itself, like the "Version" or HelpText output: https://github.com/ppadial/dotnet/blob/278c3ebe0286476e086ec302357a1ca0c88f283b/src/dotnet.cli.Tests/CliBootstrapperTests.cs#L23

But, now, im trying to get the output from "inside a command OnExecute method" and then, the Console is the System.Console one, so the output is not recorded by the IConsole.

I've seen your dotnet-serve command test infrastructure, but looks a bit more complex from what im doing now. Do you think there's an easy way to hook the IConsole to the OnExecution methods ? is good idea to add an overridable method that allows us to use it inside your library?

The test im doing, which is in red right now, is: https://github.com/ppadial/netcore3-cli-sample/blob/b87ea5cc0c816ffb30a90f0596238fe874cfd43d/tests/cli.Tests/FactsAppTests.cs#L38

What do you think? any idea ?

**Comment by ppadial** [comment]
Forgot about it, my fault, an example to make it working in case it helps to someone

```c#
protected override async Task<int> OnExecuteAsync(CommandLineApplication app, CancellationToken cancellationToken = default)
        {
            try
            {
                // Create facts api client specifying the Api Url, this can be parametrized or retrieved from configuration
                // to connect to different environments, etc.
                var client = new CatFactsApiClientManager("https://cat-fact.herokuapp.com").getClient();

                // Retrieve a ramdon fact from service
                var fact = await client.GetRandomFactAsync();

               // THIS LINE 
               // Print Fact text into output
                app.Out.WriteLine($"The fact of the day is {fact.text}");

                // Set the command execution to OK
                return CliReturnCodes.OK.AsInt();
            }
            catch (Exception ex)
            {
                // do something with ex
                Console.WriteLine(ex.Message);
                // Set the command execution to KO
                return CliReturnCodes.ERR_COMMAND_EXECUTION_FAILED.AsInt();
            }
        }
```

Then i can read the console.In.ReadToEnd properly in my assert section.

**Comment by natemcmaster** [comment]
You can also just `IConsole` as a parameter to OnExecute.

```csharp
protected override async Task<int> OnExecuteAsync(IConsole console, CancellationToken cancellationToken = default)
```

**Comment by ppadial** [comment]
Thanks for the tip !
