### ISSUE TITLE
CommandLineApplication code smell - has too many APIs

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#298]
CommandLineApplication has grown into a god class. It has 116 APIs on it. I'd like to consider ways to refactor CommandLineApplication to simplify it.

The entire API as of 2.4: https://gist.github.com/natemcmaster/b524f050c7124fcf92011025a75243d3

### Ideas:

* Make breaking change to CommandLineApplication and move APIs into separate classes based on logical grouping
* Leave CommandLineApplication as-is, but implement a refactored API surface and shoe-horn CommandLineApplication into the new API. Update docs and samples to use the new API and consider deprecating CommandLineApplication in the long run

### Logical grouping
* parser configuration
    * AllowArgumentSeparator
    * ClusterOptions
    * MakeSuggestionsInErrorMessage
    * OptionsComparison
    * ResponseFileHandling
    * ThrowOnUnexpectedArgument
* handling the parsing result
    * Parse()
    * OnParsingComplete()
    * RemainingArguments
    * ValueParsers
* defining the structure of the commands and options/arguments
    * AddSubcommand()
    * Command()
    * Comamnds
    * Argument() and Argument<T>()
    * Arguments
    * Option() and Option<T>()
    * Options
    * GetOptions()
    * HelpOption()
    * OptionHelp
    * OptionVersion
    * VersionOption()
    * VersionOptionFromAssemblyAttributes()
    * Parent
    * Model 
    * ModelFactory
    * Conventions
* help text
    * ShowHelp()
    * ShowVersion()
    * ShowRootCommandFullNameAndVersion()
    * HelpTextGenerator
    * UsePagerForHelpText
    * LongVersionGetter
    * ShortVersionGetter
    * ShowInHelpText
    * ExtendedHelpText
    * FullName
    * Names
    * Name
    * AddName
    * Description
* validation
    * GetValidationResult()
    * OnValidationError()
    * ValidationErrorHandler
    * Validators
* app lifecycle and command execution context
    * IsShowingInformation
    * WorkingDirectory
    * Invoke
    * OnExecute() and OnExecuteAsync()
    * Execute() and ExecuteAsync()
    * Out
    * Error

**Comment by natemcmaster** [comment]
Ping! Anyone have thoughts on this one? Agree, disagree?

**Comment by Miista** [comment]
I think it would be a good idea to break up `CommandLineApplication`. 

With regards to the ideas you proposed I feel that leaving `CommandLineApplication` as-is and shoe-horning it into a refactored API surface is only going to postpone handling the actual problem which is that it is a god class. 
I would much rather we make a breaking change, introducing a clean API. 
How it should be grouped could be discussed further.

**Comment by natemcmaster** [comment]
Maybe I'm overly cautious as a result of starting my career on the .NET team at Microsoft, but I have a preference for minimizing breaking changes -- or at the very least, doing it gracefully. What do you think about a two-step breaking change?

Step 1 - design the new API and release it in 3.0. Mark CommandLineApplication with `[Obsolete("<INSERT REASON HERE>. See more details at <LINK>.")]`. This gives users compiler warnings and instructions how how to upgrade.
Step 2 - delete CommandLineApplication in release 4.0.

Here's an example of one place I've used this approach: https://github.com/natemcmaster/CommandLineUtils/blob/cf1947b2d22d3b9a6d16b1ea1f914bbb2886aa5a/src/CommandLineUtils/Attributes/SubcommandAttribute.cs#L18-L24

**Comment by Miista** [comment]
That seems like a good approach. My worry was that you would keep the shoe-horned `CommandLineApplication` alongside the new API.

**Comment by natemcmaster** [comment]
Closing as stale. At this point, I have no intention in addressing this problem.
