### ISSUE TITLE
Feature request: support different arg conventions (POSIX, CMD, Powershell)

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#3]
POSIX examples:
```
git clean -xfd --git-dir ./.git/
```

Windows CMD examples
```
taskkill /T /F /IM git.exe
```

PowerShell example
```
Remove-Item -Recurse -Force ./node_modules/
```

Currently, this library only supports parsing the POSIX

**Comment by bbrandt** [comment]
Assuming that you do not have unlimited time and resources, I feel it would be better to settle on POSIX as the standard for this library and do it really well.  There will be other libraries that do the others hopefully equally well.

**Comment by natemcmaster** [comment]
I haven't heard requests yet for windows or powershell style args. I just posted this as a possibility This library already does posix-style parsing, so I'm going to mark this as <kbd>help-wanted</kbd>. If someone really wants this, I'd be open to taking a PR for it.

**Comment by natemcmaster** [comment]
Closing for lack of interest.
