### ISSUE TITLE
Help option prints incorrect ShortName

### ISSUE THREAD

**Issue by borrrden** [natemcmaster/CommandLineUtils#30]
With the latest NuGet release, an option is available to set the short name of an option, but the help message outputs what seems like an autogenerated (incorrect) one.

```
[Option(CommandOptionType.SingleValue, Description = "...", ValueName = "...", ShortName = "c")]
public string ConfigPath { get; set; }

[Option(CommandOptionType.SingleValue, Description = "...", ValueName = "...", ShortName = "s")]
public string CSharpPath { get; set; }
```

The following is the output line from help:
> -c|--config-path ¥<CONFIG_PATH> ...
-c|--csharp-path ¥<CSHARP_PATH> ...

The options parses correctly when passed but the help text is misleading.

**Comment by natemcmaster** [comment]
@borrrden can you try https://myget.org/feed/natemcmaster/package/nuget/McMaster.Extensions.CommandLineUtils/2.1.1-alpha.125 to ensure it fixes your issue?

**Comment by borrrden** [comment]
Confirmed!  Thanks for the extremely fast response.
