### ISSUE TITLE
Usage help has wrong order of options and commands

### ISSUE THREAD

**Issue by AndreGleichner** [natemcmaster/CommandLineUtils#303]
**Describe the bug**
Generated usage help is e.g.
Usage: mytool [options] [command]
instead of:
Usage: mytool [command] [options]

**To Reproduce**
1. Using this version of the library '2.4.2'
2. Run code below
3. With these arguments '-h'
4. See wrong output "Usage: mytool [options] [command]"

**Expected behavior**
It should show "Usage: mytool [command] [options]"
Since having any options in front of the command verb fails.

**Additional context**
Repro code:
```
    [Command("mytool")]
    [Subcommand(typeof(MysubCommand))]
    class Program
    {
        static int Main(string[] args) => CommandLineApplication.Execute<Program>(args);
    }
    [Command]
    class MysubCommand { }
```
As a workaround I currently have a specialized DefaultHelpTextGenerator with overridden GenerateUsage().

**Comment by natemcmaster** [comment]
Seems like an easy one to fix if you're interested in contributing a change.

**Comment by AndreGleichner** [comment]
See https://github.com/natemcmaster/CommandLineUtils/pull/308
