### ISSUE TITLE
Help wrapped incorrectly when Console.BufferWidth is returned as 0

### ISSUE THREAD

**Issue by peppy** [natemcmaster/CommandLineUtils#306]
**Describe the bug**

I run a server-side utility which parses input from discord, then returns output to discord. It's running headless on a linux server, and was working fine until https://github.com/natemcmaster/CommandLineUtils/pull/248, which has regressed output of help text.

Investigating further, `Console.BufferWidth` is being returned as 0 in this environment, which makes output look something like this:

![image](https://user-images.githubusercontent.com/191335/68734119-8648f280-061c-11ea-96c8-5778abee0a7a.png)

I've attempted setting `Console.BufferWidth` back to a sane value, but that results in `Operation is not supported on this platform.`.

**To Reproduce**

I am running commands via

```csharp
await new HostBuilder()
      .ConfigureServices((context, services) =>
      {
          // ReSharper disable once AccessToDisposedClosure
          services.AddSingleton<IConsole>(logger);
      })
      .RunCommandLineApplicationAsync<Program.ExecuteLimitedCommands>(arguments.ToArray());
```

using a custom logger.

**Expected behavior**

I would expect in a headless scenario, either a custom width could be provided or it would default to a non-zero sane value.

**Comment by natemcmaster** [comment]
Should be an easy fix. Thanks for the thorough write up!

**Comment by natemcmaster** [comment]
If you want to try a prerelease with this fix, you can install it into your project from this feed:

https://dev.azure.com/natemcmaster/github/_packaging?_a=package&feed=github%40Local&package=McMaster.Extensions.CommandLineUtils&protocolType=NuGet&version=2.5.0-beta.183&view=overview

**Comment by peppy** [comment]
Tested, works perfectly. Thanks!
