### ISSUE TITLE
HelpOption display bug

### ISSUE THREAD

**Issue by tomrus88** [natemcmaster/CommandLineUtils#307]
**Describe the bug**
Help text is missing option name when using default short help template like this
```
[HelpOption("-h")]
abstract class SomeCommandBase
{
    protected virtual int OnExecute(CommandLineApplication app)
    {
        app.ShowHelp();
        return 1;
    }
}

[Command("somecmd")]
class MyApp : SomeCommandBase
{
}
```

You get following help texts:
> Run 'appname [command] --' for more information about a command.

instead of
> Run 'appname [command] -h' for more information about a command.

and
> Specify - for a list of available options and commands.

instead of
> Specify -h for a list of available options and commands.

Issue seems to be somewhere in those lines:
https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/HelpText/DefaultHelpTextGenerator.cs#L281
https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/CommandLineApplication.cs#L994

Also please consider making [CommandOption.UnderlyingType](https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/CommandOption.cs#L138) and [DefaultHelpTextGenerator.ExtractNamesFromEnum](https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/HelpText/DefaultHelpTextGenerator.cs#L368) protected to make creating custom help generators easier.

**Comment by natemcmaster** [comment]
Looks like a simple bug. I would be happy to accept a pull-request to fix the issue.

Re: CommandOption.UnderlyingType - this one is intentionally internal because I plan to refactor how it is used relatively soon. I don't want to risk someone taking a dependency on this API by making it accessible.
