### ISSUE TITLE
[Question] Chaining SubCommands

### ISSUE THREAD

**Issue by gandarez** [natemcmaster/CommandLineUtils#310]
Can I chain SubCommands over SubCommands?

```C#
Command("super-dupper", Description = "Some description..."),
Subcommand(typeof(Rollback))]
public class Root
{
    protected int OnExecute(CommandLineApplication app, IConsole console)
    {
        /* ... */
    }
}

Command("rollback", Description = "Some description..."),
Subcommand(typeof(RollbackAll), typeof(RollbackTo))]
public class Rollback
{
    protected int OnExecute(CommandLineApplication app, IConsole console)
    {
        /* ... */
    }
}

Command("all", Description = "Some description...")]
public class RollbackAll
{
    protected int OnExecute(CommandLineApplication app, IConsole console)
    {
        /* ... */
    }
}

Command("to", Description = "Some description...")]
public class RollbackTo
{
    protected int OnExecute(CommandLineApplication app, IConsole console)
    {
        /* ... */
    }
}
```

**Comment by natemcmaster** [comment]
Yes, this is supported.

**Comment by gandarez** [comment]
I have no idea why the commands implemented in the mentioned project (see above) is not working. Can you please take a look at the source code and point us any problem you see?

https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.DotNet.Cli/Commands/Root.cs

**Comment by natemcmaster** [comment]
I cloned your project and its work as I would have expected it do based on the code. Is "Unrecognized option '-p'" the problem you are trying to address when running `dotnet fm rollback all -p mysql...`? If so, the reason you get this error is that `-p` is not configured as an option in RollbackAll.cs or BaseCommand.cs. Did you mean for RollbackAll to inherit from ConnectionCommand?

**Comment by gandarez** [comment]
It could be the possible problem. I changed the inheritance from `BaseCommand` to `Rollback` and then I started getting a kind of inifite looping. When I run the command it does nothing. The `Rollback all` command has to have the same options as his parent. How to achieve that?
