### ISSUE TITLE
CommandLineApplication.Execute should handle CommandParsingException

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#35]
Currently this is thrown and unhandled. This requires users to implement their own catch. The library should instead catch this, print to stderr, and exit before calling OnExecute.

**Comment by WGroenestein** [comment]
This issue seems to still exist in 2.2.0-alpha. I have a repro repo [here](https://github.com/WGroenestein/cli-bug)

**Comment by natemcmaster** [comment]
This is expected behavior. This bug description wasn't super clear, but what I meant by it was that the _static_ version of .Execute should handle CommandParsingException. For example, this kind of code:

```c#
class Program
{
   public static int Main(string[] args) => CommandLineApplication.Execute<Program>(args);

  [Option]
  public string TestOption { get; }

  public void OnExecute() { }
}
```
