### ISSUE TITLE
Cannot adjust logging verbosity through HostBuilder

### ISSUE THREAD

**Issue by wasabii** [natemcmaster/CommandLineUtils#354]
Oversight. It is a common pattern to add an Option like -d or -v to the command line application in order to adjust logging level. However, since logging is configured up in the HostBuilder, before invoking RunCommandLineApplicationAsync, there is no way to obtain this parsed data in order to decide on the MinimumLogLevel set in AddConsole (or whatever).

Not sure on a solution to this. Chicken and egg problem.

**Comment by wasabii** [comment]
Thinking through solutions. It might make sense to not use the standard .NET Core Console Logger provider for this. But instead to provide a custom one that filters log level and allows adjustment of log level through a singleton instance provided to the `Command` classes. Might also make sense to not circumvent `CommandLineUtils` `IConsole` instance either, and run logging through that.

```
            return await new HostBuilder()
                .ConfigureLogging(o => /* no longer required */)
                .ConfigureServices((ctx, svc) => svc.AddSingleton(PhysicalConsole.Singleton))
                .RunCommandLineApplicationAsync<Program>(args);
```

Maybe `RunCommandLineApplicationAsync` could append additional logger outputs. One of this sends through `IConsole`. This eliminating the need for `AddConsole`. And also provide something like a `IConsoleLoggerConfiguration` that could be injected into a class, with a `MinimumLevel` property.

**Comment by natemcmaster** [comment]
I'm open to suggestions on how to implement this one. Adding the help-wanted label. I think you're right...it is sort of a chicken and egg problem in the code's current format.
