### ISSUE TITLE
[Question] how do I make an option mandatory?

### ISSUE THREAD

**Issue by mattfrear** [natemcmaster/CommandLineUtils#356]
The documentation says that options can be made mandatory, but I can't see an example of how to do that.

I thought that maybe `[Option(CommandOptionType.SingleValue)]` would do this, but it doesn't.

**Comment by natemcmaster** [comment]
Here is a sample. This should probably be explicitly called out in the docs, too. https://github.com/natemcmaster/CommandLineUtils/blob/7281ee9fef08286a3a0a4f72d04b1d234747b316/docs/samples/validation/attributes/Program.cs#L14-L16

**Comment by mattfrear** [comment]
Oh, that's easy! Thanks.
I even went searching in here for Required and couldn't see it, cos that's the wrong place.

https://natemcmaster.github.io/CommandLineUtils/v2.5/api/McMaster.Extensions.CommandLineUtils.OptionAttribute.html
