### ISSUE TITLE
Support for service scopes with generic host integration

### ISSUE THREAD

**Issue by poke** [natemcmaster/CommandLineUtils#358]
I am building a command line application that reuses a larger set of service registrations from a different app. Since that other app uses service scopes (e.g. for handling web requests), I have quite a few services that are registered as a scoped dependency. These dependencies cannot be resolved from the root service provider, so I have to create a service scope first.

Unfortunately, the generic host integration doesn’t work for this since it uses the service provider directly and doesn’t allow me to change this. So right now, I cannot use the integration and have to do something like this instead:

```c#
public static async Task<int> Main(string[] args)
{
    var host = CreateHostBuilder(args).Build();
    using var scope = host.Services.CreateScope();

    var app = new CommandLineApplication<App>();
    app.Conventions
        .UseDefaultConventions()
        .UseConstructorInjection(scope.ServiceProvider);
    return await app.ExecuteAsync(args);
}
```

It would be nice if I could pass something to `RunCommandLineApplicationAsync`, or even register some “service resolver” type that would be used by the constructor injection convention to resolve the services where I could then use a scoped service provider.

**Comment by natemcmaster** [comment]
I wouldn't make this the default behavior, but I'm open to added a way to make this happen. I think it could be done by extracting some of the code from https://github.com/natemcmaster/CommandLineUtils/blob/7281ee9fef08286a3a0a4f72d04b1d234747b316/src/Hosting.CommandLine/Internal/CommandLineService%7BT%7D.cs into a separate class that can be overridden/replaced via DI.

Marking as help-wanted. I'm open to suggestions and contributions on how to implement this.

**Comment by poke** [comment]
Hm, I’m not sure if that would be the right approach. Ideally, you would probably want the scope to be around the `ExecuteAsync` but to implement it in the service, you would really have to open the scope in the constructor, and dispose it in the Dispose method. So basically you would be replacing the `CommandLineService` which I guess would be totally fine if the `ICommandLineService` was public so that you could inject your own implementation. That’s actually also how I was attempting to solve this originally.

Imo, an ideal solution would involve modifying the [ConstructorInjectionConvention](https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/Conventions/ConstructorInjectionConvention.cs) so that it would take some custom factory that one could have some control over how dependencies are created.

I actually also tried to replace those [`AdditionalServices`](https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/Conventions/ConstructorInjectionConvention.cs#L39) with a custom convention that would run afterwards but that failed because that service provider is unfortunately internal. – And I don’t understand enough about those conventions yet :D

Btw. somewhat unrelated: couldn’t the constructor injection logic be simplified by delegating the object construction over to [ActivatorUtilities](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.activatorutilities?view=dotnet-plat-ext-3.1)?

**Comment by natemcmaster** [comment]
> Hm, I’m not sure if that would be the right approach. 

I'm open to suggestions. I was just shooting from the hip and hadn't thought through it. Feel free to explore the alternatives you mentioned.

> couldn’t the constructor injection logic be simplified by delegating the object construction over to ActivatorUtilities?

That requires taking a dependency on Microsoft.Extensions.DependencyInjection....so, no.

**Comment by poke** [comment]
> Feel free to explore the alternatives you mentioned.

Alright, I will give a few ideas a try then and see how they feel. Thanks for your input!

> That requires taking a dependency on Microsoft.Extensions.DependencyInjection....so, no.

Oh right, I forgot that `IServiceProvider` isn’t part of M.E.DI itself. Makes sense.

**Comment by scott-xu** [comment]
With my PR https://github.com/natemcmaster/CommandLineUtils/pull/363, you can use scope like this:
```C#
new HostBuilder()
        .RunCommandLineApplicationAsync<Program>(args, app =>
        {
            using var scope = app.CreateScope();
            app.Conventions.UseConstructorInjection(scope.ServiceProvider);
        });
```

**Comment by poke** [comment]
@scott-xu Not with a `using var` as that would dispose the scope immediately once the configuration completes. It would probably work when the scope is left open but then we still would need to be able to dispose the scope somewhere (unfortunately, disposing the service provider will not dispose all existing scopes).
But that is an interesting and useful approach nonetheless!

**Comment by scott-xu** [comment]
@poke yeah, it's probably not a good sample. Anyway you can assign the scope object to somewhere else where you controls it.

**Comment by daniel-lerch** [comment]
Thanks to @scott-xu's contribution it is possible to a service scope:
```csharp
IServiceScope? scope = null;
int result = await CreateHostBuilder().RunCommandLineApplicationAsync<MainCommand>(args, app =>
{
    scope = app.CreateScope();
    app.Conventions.UseConstructorInjection(scope.ServiceProvider);
});
scope?.Dispose();
return result;
```

However, I would prefer to have a more elegant way to do this. The `McMaster.Extensions.Hosting.CommandLine` package does already have a reference on `Microsoft.Extensions.DependencyInjection`. If @natemcmaster does not want to make creating a scope the default behavior we could at least make it an optional behavior. The easiest way would be to add an overload:

```csharp
return await CreateHostBuilder().RunCommandLineApplicationAsync<MainCommand>(args, createScope: true);
```

If you would like to have a more extensible solution we could create a new class `CommandLineHostOptions`:

```csharp
var options = new CommandLineHostOptions { CreateScope = true };
return await CreateHostBuilder().RunCommandLineApplicationAsync<MainCommand>(args, options);
```

**Comment by scott-xu** [comment]
@daniel-lerch with your proposed API, where can user dispose the scope?

**Comment by daniel-lerch** [comment]
My idea was that the scope is created for command execution and disposed automatically once the command returns. I wanted to create a similar behavior like in ASP.NET Core where scopes are created automatically for each request and get disposed once the request is finished.

The user won't be able to dispose the scope. Maybe `useScope` would be a better name than `createScope` to clarify that a scope is not only created, but also disposed.

**Comment by scott-xu** [comment]
But the command execution is per process.

**Comment by daniel-lerch** [comment]
You're right. My proposal addresses projects that use `Microsoft.Extensions.Hosting` for production (most of them are ASP.NET Core projects) and need a CLI to run database migrations and other jobs. Such projects have many scoped services like EF Core's `DbContext`. For these services it doesn't matter whether a scope lives just for one request or for the entire process lifetime.
