### ISSUE TITLE
Unable to start Subcommands example

### ISSUE THREAD

**Issue by ninjaboy** [natemcmaster/CommandLineUtils#36]
When Subcommands project is being started it prompts to choose for one of 3 options.
When the option 3 is chosen - the app just exits without allowing to interact with fake-npm command.

**Comment by natemcmaster** [comment]
How's this? https://github.com/natemcmaster/CommandLineUtils/commit/5849b59f369f36a863eecefbce0aa731c394d944

**Comment by ninjaboy** [comment]
@natemcmaster , thanks that helped to proceed further, although the app still exits, when choosing some npm options. Ideally I think it should have gone to the main menu by default. However, this was enough for my debugging purposes, so closing this one for now. Thanks
