### ISSUE TITLE
[Question] Define SubCommands on Runtime

### ISSUE THREAD

**Issue by ghost** [natemcmaster/CommandLineUtils#360]
Hi, I am currently trying to make a plugin based system using the CommandLineUtils and DI. In the host application, I tried to prepare the app using the BuilderAPI, but in the plugin library I would like to use the nested api for ease of use. Is this possible?

**Comment by alpite-limited** [comment]
I just found out there is a AddSubcommand. Can you show me how it works? What I have done so far is

`            foreach(var type in types)
            {
                Console.WriteLine(type);
                var subcommand = (CommandLineApplication)Activator.CreateInstance(type);
                Console.WriteLine(subcommand.Name);
                app.AddSubcommand(subcommand);
            }
`

An example of the type is 

`{

    [
        Command("plugins", Description = "Plugin Administration"),
        Subcommand(typeof(SearchCommand), typeof(InstallCommand), typeof(DeleteCommand))
    ]
    public class PluginRootCommand : IProvideRootCommand
    {
        public void OnExecute(CommandLineApplication app)
        {
            app.ShowHelp();
        }
    }
}`

`    public class IProvideRootCommand : CommandLineApplication, IProvideCommands
    {
         
    }`
