### ISSUE TITLE
New way to execute with Model without async, reflection/invoke, try/catch

### ISSUE THREAD

**Issue by michkot** [natemcmaster/CommandLineUtils#362]
**Is your feature request related to a problem? Please describe.**
I was debugging my app logic now being invoked through `CLA.Execute<Model>(args)` and found very annoying that the reflection .Invoke together with try/catch blocks and async blows away the stack info for debugger. I am not sure if the problem is the reflection invocation, the try/catch blocks or the async-ity. I guess combination fo all?

**Describe the solution you'd like**
This works only when command and all subcomands can be cast to BaseCmd (might be an interface, a second parametr to some ExecuteSync<Cmd,BaseCmd> method?
I am aware that I am loosing the ctrl+c feature to terminate the command in this. 
Maybe compiling an expression into a delegate and running that, instead of reflection invoke, would make the problem better?
```cs
var console = PhysicalConsole.Singleton;
//context = new DefaultCommandLineContext(console, Directory.GetCurrentDirectory(), args);
var app = new CommandLineApplication<Cmd>();
app.Conventions.UseDefaultConventions();
BaseCmd cmdModel = null; // all my model-classes implement BaseCmd
try
{
    var result = app.Parse(args);
    var command = result.SelectedCommand;
    var validationResult = command.GetValidationResult();
    if (validationResult != ValidationResult.Success)
    {
        //return command.ValidationErrorHandler(validationResult);
    }
}
catch (CommandParsingException ex)
{
    console.Error.WriteLine(ex.Message);

    if (ex is UnrecognizedCommandParsingException uex && uex.NearestMatches.Any())
    {
        console.Error.WriteLine();
        console.Error.WriteLine("Did you mean this?");
        console.Error.WriteLine("    " + uex.NearestMatches.First());
    }

    //return ValidationErrorExitCode;
}
if (!(cmdModel is null))
    app.Model.OnExecute(app, PhysicalConsole.Singleton);
```

**Additional context**
Might be nice to put IModelAccessor somewhere into documentation.

**Comment by natemcmaster** [comment]
I'm not sure how to address this. If there is a way to make this work without regression on existing functionality, please let me know.

Marking with the 'help wanted' label as this is something I'm not planning to address immediately, but I'm open to suggestion on how to do this and/or a pull-request to fix it.

**Comment by michkot** [comment]
So... Some time has passed and I can "procrastinate" on this feature again. The posted "semi-solution" that cicrumvents the built-in Invoke/async/try-catch machinery is 

1. probably skipping some features I did not use (I was stepping trough the sub-command invocation path in debugger and I don't remember all of the functionality)
2. forcing user to implement a specific interface or subclass a specific class in all-submodules, which definitely falls under "regression on existing functionality"

I have recently read (and implemented some of it) a lot of articles on System.Linq.Expressions (and other alternatives that allow to create strongly-typed delegates for run-time created code) and that could definitely be used to eliminate reflection invocation used in the (sub-)command invocation code. I would like to look into that over the weekend. However, I am not sure if the "stack-being-blown-away when exception is raised from withing the invoked command problem" will be resolved by that, but it seems that it's worth a try.
