### ISSUE TITLE
My code signing cert expires soon, planning to drop code signatures on NuGet package

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#365]
Hey all,

I used to get code-signing certs for free (perk of being a Microsoft employee.) I've lost that perk, so no more freebies. My current code-signing certificate expires in a few months. Once it does, I'm not planning to renew as [renewal is not cheap](https://www.digicert.com/code-signing/).

If this is a concern for you, we have until July 2020 to change course. As far as I can tell, though, no one really cares about code-signed NuGet packages (except the NuGet team and Microsoft.)

Alternatives to dropping code signing:
* help [sponsor](https://github.com/sponsors/natemcmaster) this project. I need a few sponsors to get enough to fund yearly renewals of the cert.
* help me find a code signing CA for free.
* if you are a CA reading this, consider being generous to open-source contributors like myself.

Please comment if you have concerns or suggestions.

**Comment by vcsjones** [comment]
For what it's worth, DigiCert seems to have gone off the deep-end with their Code Signing cert prices. You could consider a certificate from Comodo / Sectigo that is about $70 / year. 

https://comodosslstore.com/code-signing

There is no reason not to use Comodo. Their certs are fine and just as trustworthy.

**Comment by natemcmaster** [comment]
Thanks for the suggestion, @vcsjones! I think I'll look into that.

Out of curiosity, if I stopped code signing this package, would it impact you at all?

**Comment by SimonCropp** [comment]
i currently maintain ~150 packages with 21mil downloads. so far no one has asked for signed packages. So IMO i dont think it is worth the effort or the cost

**Comment by webprofusion-chrisc** [comment]
It's maybe more of an issue when users are installing a desktop app (as administrator even) than when they're using a NuGet package in their build, I've not really noticed signed nuget packages before.

**Comment by Drawaes** [comment]
I have never seen a dev shop of which I have worked are many, and large financials and package signing is not something that has ever been mentioned...

**Comment by vcsjones** [comment]
> Out of curiosity, if I stopped code signing this package, would it impact you at all?

Frankly, no. Though I am a tool / package author myself, perhaps someone upstream might care, I don't believe anything would change for me.

**Comment by natemcmaster** [comment]
> I have never seen a dev shop of which I have worked are many, and large financials and package signing is not something that has ever been mentioned...

That's basically what I suspected. Seems like code signing is most commonly useful if 

* you want your downloaded Windows installer to pass the SmartScreen (doesn't apply to nuget packages)
* Or you are working at a company that has heavy restrictions on open source usage and requires you to enforce NuGet package security rules on download. 

For the latter, I've never seen anyone outside of Microsoft doing this, so figured dropping the code signing is unlikely to impact anyone.
