### ISSUE TITLE
[Question] How to setup an options menu  

### ISSUE THREAD

**Issue by karthikchintala1** [natemcmaster/CommandLineUtils#366]
Thanks for creating this awesome project.

How to create an options menu in the CLI? The user should be able to choose from the given options provided by scrolling through options with (up/down keys).

**Comment by natemcmaster** [comment]
This feature doesn't exist. Someone started working on it a few years ago https://github.com/natemcmaster/CommandLineUtils/issues/41, but never finished it. I closed as stale after interest dried up.

If you are interested in implementing this, let me know.

**Comment by drewkill32** [comment]
@natemcmaster I would be interested in picking this up.  I reviewed #42 the branch *feature/checkbox* doesn't anymore. Should I cherry-pick redbaty's changes and submit a new pull request?

**Comment by natemcmaster** [comment]
Sorry for delayed response @drewkill32. 

I think what I would rather do is restore that branch into the repository, and have a new pull request targeting that branch. That way we don't have to re-review work already done by redbaty@.

I've restored the branch here: https://github.com/natemcmaster/CommandLineUtils/tree/feature/checkbox

**Comment by drewkill32** [comment]
@natemcmaster  no problem, I and work on that branch and submit a pull request when done.

**Comment by natemcmaster** [comment]
Yes
