### ISSUE TITLE
Add CommandLineState to the HostBuilder.Properties dictionary

### ISSUE THREAD

**Issue by danielmeza** [natemcmaster/CommandLineUtils#367]
Provide access to the CommandLineState  throw the Properties on a HostBuilder will allow us to access it in scenarios where there are not DI yet, like in the ConfigureService or ConfigureAppConfiguration methods. 

Solution:
Add (https://github.com/natemcmaster/CommandLineUtils/blob/6e919b63e3b10d4e23910365acc2a471b18c15f7/src/Hosting.CommandLine/HostBuilderExtensions.cs#L38) tot he Properties at HostBuilder like this.

`hostBuilder.Properties[typeof(CommandLineState)] = state`

We can also create extension methods to get the CommandLineState on the IHostBuild and on HostBuilderContext .

**Comment by natemcmaster** [comment]
Sounds good to me. Thanks for opening a PR!
