### ISSUE TITLE
Is there an example where subcommands get processed based on the input obtained from the user when prompted?

### ISSUE THREAD

**Issue by hiadusum** [natemcmaster/CommandLineUtils#374]
I am trying to build a interactive command line tool where I first ask for the arguments that are common for all the commands. Following that, I will ask the customer to choose the command. Once the customer chooses the command, I would like to prompt for the arguments that it takes.

Is there a sample that is close to what I am looking for?

**Comment by natemcmaster** [comment]
> Is there a sample that is close to what I am looking for?

Not really. This has been asked before. See https://github.com/natemcmaster/CommandLineUtils/issues/152. If you want to build something and contribute it, let me know.
