### ISSUE TITLE
Dependency Injection example?

### ISSUE THREAD

**Issue by dotnetshadow** [natemcmaster/CommandLineUtils#38]
Hi there I was wondering if you have a dependency injection example?

Usually I would use something like below but I'm not sure how I would call your code?
```
 class Program
    {
        static int Main(string[] args)
        {          
            //  setup our DI
            var services = new ServiceCollection();            
            services.AddTransient<IHelloService, HelloService>();      
            var serviceProvider = services.BuildServiceProvider();
           
            // ---------------------------------------------------
           // Not sure how to use this ??? 
            var app = serviceProvider.GetService<Calculator>();
            //app.Run(args);
            ///------------------------------------------------

      
        }
    }
```

**Comment by natemcmaster** [comment]
This library doesn't support anything special for dependency injection. 

Put your CI setup code inside  the `OnExecute` method, for example: https://github.com/natemcmaster/CommandLineUtils/blob/master/samples/HelloWorld.Attributes/Program.cs#L20. Or, if you wanted to setup DI before you parse CLI options, you can use the builder API.

IMO command-line parsing should happen before you setup DI.

**Comment by dotnetshadow** [comment]
Ahh thank you for the explanation, that makes sense.

**Comment by natemcmaster** [comment]
No problem. Happy to help.

**Comment by dotnetshadow** [comment]
Perhaps it could be worth creating a small example for others, if the question ever arises again, just a thought
