### ISSUE TITLE
[Question] Is there a way to run multiple subcommands?

### ISSUE THREAD

**Issue by theRoughCode** [natemcmaster/CommandLineUtils#381]
I want to run a command like `dotnet run [subcommand1] [args1] [subcommand2] [args2]`.
Is there a way to do this or maybe using a delimiter to differentiate between subcommands?

**Comment by natemcmaster** [comment]
Nope, not currently possible. To achieve this usage, you would need to make `[subcommand2]` a subcommand of `[subcommand1]`.

Closing as I believe the question is answered.
