### ISSUE TITLE
[Question] Handle UnrecognizedCommandParsingException with Generic Host

### ISSUE THREAD

**Issue by jachin84** [natemcmaster/CommandLineUtils#382]
I am trying to work out the best way to catch UnrecognizedCommandParsingException and just show the app usage when using RunCommandLineApplicationAsync with generic host.

Below is my main method.

```csharp
public static async Task<int> Main(string[] args)
{
    return await new HostBuilder()
        .ConfigureLogging((context, builder) =>
        {
            builder.ClearProviders();
            builder.AddConsole();
        })
        .ConfigureServices((context, services) =>
        {
            services.AddTransient<Dependency>();
        }).RunCommandLineApplicationAsync<AppCommand>(args);
    
}
```

I can easily surround the call to `RunCommandLineApplicationAsync ` in a try/catch but how would I generate usage in the catch block??

**Comment by scott-xu** [comment]
From reading the code,
https://github.com/natemcmaster/CommandLineUtils/blob/main/src/Hosting.CommandLine/Internal/CommandLineLifetime.cs#L68
I think you can implement your customized ErrorHandler. Try inject your CommandLineApplication to your ErrorHandler and show help. (I haven't tested)
```C#
.ConfigureServices((context, services) =>
{
    services.AddSingleton<IUnhandledExceptionHandler, YourErrorHandler>();
})
```

**Comment by jachin84** [comment]
I tried this out but couldn't figure out how to inject `CommandLineApplication` into my `IUnhandledExceptionHandler`.
