### ISSUE TITLE
how to keep the tool running?

### ISSUE THREAD

**Issue by wangshuai-007** [natemcmaster/CommandLineUtils#383]
I use `Serilog` and `EFCore` in my `CommandLineUtils`.
It cause every command I run will cost several seconds.I think it is because every command I run will reinitialize `CommandLineUtils`.
So,Is there a way to hold `CommandLineUtils` running in backgrand?

**Comment by drewkill32** [comment]
Are you looking to do a [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop)? You can create a loop with `Console.ReadLine()` , break the line up by spaces, and send the string array into `CommandLineApplication.Execute<Program>(args);`

**Comment by natemcmaster** [comment]
Closing as I believe the question was answered by @drewkill32 (thanks!)
