### ISSUE TITLE
Sub-command multi-character short name options not always supported by default

### ISSUE THREAD

**Issue by jlkelly48** [natemcmaster/CommandLineUtils#387]
**Describe the bug**
If a sub-command has options that have been defined with more than 1 character, a CommandParsingException is thrown when the multicharacter short name is specified. For example, if the option short name is specified as 'sn',  when -sn is specified the CommandParsingException message 'Unrecognized option '-s' is returned. 

**To Reproduce**
1. Using v3.0,0 of the CommandLineUtils library
2. Run this code:
            try
            {
                CommandLineApplication testApp = new CommandLineApplication();
                testApp.Name = "App";

                CommandLineApplication subCommand = new CommandLineApplication();
                subCommand.Name = "subcommand";
                subCommand.Option("-sn|--serialnumber", "unique id", CommandOptionType.SingleValue);
                testApp.AddSubcommand(subCommand);

                testApp.Execute(args);
            }
            catch (CommandParsingException e)
            {
                Console.WriteLine(e.Message);
            }

3. With these arguments 'subcommand -sn 123'
4. See error " Unrecognized option '-s' "

**Expected behavior**
Since the short name of the subcommand option had been specified as multi-character '-sn', I expected -sn to be accepted.

**Additional context**
I was able to get the expected behavior by adding the line:
                 subCommand.ClusterOptions = false;
However, I didn't think this would be needed and the 'option' documentation does not indicate this should be necessary (though multi-character short names are not spelled out either).
When looking at the source code the CommandLineProcessor:CheckForShortOptionClustering is being passed in the main command when I think it needs the sub-command passed in.

**Comment by natemcmaster** [comment]
Sounds like you might have identified the problem. If so, feel free to send a pull-request :)

**Comment by scott-xu** [comment]
@jlkelly48 I believe the recommended way is to call `Command` method to add sub command:
```C#
CommandLineApplication testApp = new CommandLineApplication();
testApp.Name = "App";
testApp.Command("subcommand", subCommand =>
{
    subCommand.Option("-sn|--serialnumber", "unique id", CommandOptionType.SingleValue);
}

testApp.Execute(args);
```

**Comment by scott-xu** [comment]
@natemcmaster A simple fix is to set Parent when call `AddSubcommand`, However, user can still add sub command by calling `Commands` property's `Add` method.
```C#
public void AddSubcommand(CommandLineApplication subcommand)
{
    if (subcommand == null)
    {
        throw new ArgumentNullException(nameof(subcommand));
    }

    foreach (var name in subcommand.Names)
    {
        AssertCommandNameIsUnique(name, null);
    }

    subcommand.Parent = this; // <- set parent here.

    Commands.Add(subcommand);
}
```

**Comment by natemcmaster** [comment]
Good suggestion @scott-xu. I've done that here: https://github.com/natemcmaster/CommandLineUtils/pull/393

> However, user can still add sub command by calling Commands property's Add method.

Yes, that's one of the unfortunate API choices this library inherited from the Microsoft original source. :-/
