### ISSUE TITLE
Show Help for subcommand

### ISSUE THREAD

**Issue by dotnetshadow** [natemcmaster/CommandLineUtils#39]
Hi there

In your sample:  **CommandLineUtils/samples/Subcommands/Inheritance.cs**

How would you go about showing app.ShowHelp() so that if you typed 
**dotnet run add** it will show the help for the **Files** command

I tried the following:
```
protected override int OnExecute(CommandLineApplication app)
        {
            if (Files.Length == 0)
            {
                // this shows help even if the --help option isn't specified
                app.ShowHelp();
                return 1;
            }

            return 0;
        }
```

This seemed to work, but when I actually passed arguments it still kept showing the help
`dotnet run add files test1,test2' still showed help?

**Comment by natemcmaster** [comment]
The snippet you showed looks right. Does `Files` have `ArgumentAttribute` on it?

**Comment by dotnetshadow** [comment]
Yes it does `[Argument(0)]`, I pretty much used your code:
https://github.com/natemcmaster/CommandLineUtils/blob/f3f268bd5d43495c70802e004547e3a7c7a1ca04/samples/Subcommands/Inheritance.cs#L46

**Comment by natemcmaster** [comment]
🤷‍♂️  not sure. Doesn't repro for me.

```
samples/Subcommands $ dotnet run 1 add file1 file2 
Result = git add file1 file2
```

**Comment by dotnetshadow** [comment]
Ahhh my bad I was running as

`dotnet run add files test1, test2`

Sorry about that

**Comment by natemcmaster** [comment]
> I just tried it but now I'm getting a blank instead of executing the OnExecute when I use

The behavior of the library looks correct to me. I think what you're expecting is `Result = git add file1 file2`. For that, you need to add `base.OnExecute()` since you've overridden GitCommandBase.OnExecute in AddCommand. 

```
        protected override int OnExecute(CommandLineApplication app)
        {
            if (Files.Length == 0)
            {
                app.ShowHelp();
                return 1;
            }

            return base.OnExecute(app);
        }
```

**Comment by dotnetshadow** [comment]
@natemcmaster ahh yes that's correct, I forgot about calling the base thanks for that

**Comment by natemcmaster** [comment]
Sounds like you figured things out then. Closing for now as it doesn't appear there is anything that needs to change in the library. Let me know if you think otherwise.
