### ISSUE TITLE
GetPassword is broken

### ISSUE THREAD

**Issue by ZacharyPatten** [natemcmaster/CommandLineUtils#392]
### `GetPassword` is broken

1. Writing `"\b \b"` will not move up lines in the console, so if the input currently spans multiple lines your backspace breaks (will not back space to previous lines in the console).
2. It doesn't support `Delete`, `Left`/`Right` Arrow, `Home`, or `End`. Or the `CTRL` modifier.
3. When pressing keys such as those mentioned in `2.` and keys like `F1` through `F12` it is adding `'\0'` `char`s to the resulting `string`.
4. The display character should be an optional parameter so the user can choose alternatives to the hard coded `'*'` character.
5. Why have `ConsoleColor` parameters or a prompt on the method? Let other code handle that.
6. The `SecureString` is obsolete in `.NET Core`, so you should probably not include that in packages that target frameworks other than `.NET Framework`.

### Example fixes

I have written my own version of this method that fixes topics`1.-5.` from above:
[Source Code](https://github.com/ZacharyPatten/Towel/blob/91068e48e5502be570e0a3aeb92aa1306a4dab97/Sources/Towel/ConsoleHelper.cs#L120)
[Example Code](https://github.com/ZacharyPatten/Towel/blob/91068e48e5502be570e0a3aeb92aa1306a4dab97/Examples/ConsoleHelpers/Program.cs#L89)

Also, I mentioned that topic `5.` from above should be handled by other means than optional parameters on every relevant method; here is an example of a better approach in my opinion:
[Source Code](https://github.com/ZacharyPatten/Towel/blob/91068e48e5502be570e0a3aeb92aa1306a4dab97/Examples/ConsoleHelpers/Program.cs#L150)
_There are example usages in the same file as the source code._

**Comment by natemcmaster** [comment]
It seems you know what needs to be fixed. Would you mind raising a pull request?

**Comment by natemcmaster** [comment]
Re:

> The SecureString is obsolete in .NET Core, so you should probably not include that in packages that target frameworks other than .NET Framework.

I'd rather keep the API until .NET actually deprecates. I know there has been discussion about doing so, but as of .NET 5 this API is still not officially marked as `[Obsolete]`.

**Comment by ZacharyPatten** [comment]
Sorry for the late response, yes I do know the fix (the example I linked fixes it). But it is a different approach and I would recommend someone test both approaches to see if there are any negatives of my approach in comparison. Although my version fixes this issue, I'm not sure if it introduces any other issues.

**Comment by natemcmaster** [comment]
My stance on this is here https://github.com/natemcmaster/CommandLineUtils/issues/485. I can reopen the issue, but the bot will just close again in a year if no one comes forward to implement a fix.
