### ISSUE TITLE
If the option type is Nullable<T>, return CommandOptionType.SingleOrNoValue if T is CommandOptionType.SingleValue

### ISSUE THREAD

**Issue by scott-xu** [natemcmaster/CommandLineUtils#394]
**Is your feature request related to a problem? Please describe.**
If the option type is `Nullable<SomeEnum>`, I have to specify `CommandOptionType.SingleOrNoValue`. Otherwise, the help text would be
```
  -enumOpt3|--verb3 <VERB3>         nullable enum option desc.
                                    Allowed values are: None, Normal, Extreme.
```
rather than
```
  -enumOpt3|--verb3[:<VERB3>]       nullable enum option desc.
                                    Allowed values are: None, Normal, Extreme.
```
**Describe the solution you'd like**
 - [ ] return `CommandOptionType.SingleOrNoValue` if `T` is `CommandOptionType.SingleValue`
 - [ ] improve the parser to support `--a value` for `SingleOrNoValue` to **keep backwards compatibility**

**Comment by natemcmaster** [comment]
Thanks for writing this up. As long as we can preserve backwards compat, I'm okay accepting a PR to implement these features.

**Comment by scott-xu** [comment]
spec about SingleOrNoValue:

> Single or no value - a special case of "no value" options where an value may or may not be specified. They can be specified as --name (no value) or --name:value or --name=value. Unlike "single value", these cannot be specified as --name value because the space causes ambiguous usage.

**Comment by natemcmaster** [comment]
> ambiguous usage

```csharp
var app  = new CommandLIneApplication();

var optFoo = app.Option("--foo[:name]", CommandOptionType.SingleOrNoValue);
var argBar = app.Argument("bar");

app.OnExecute(() => {
   var foo = optFoo.Value() ?? "none";
   var bar = argBar.Value ?? "none";

   Console.WriteLine($"foo={foo}, bar={bar}");
});

app.Execute("--foo", "HELLO")
```

What does the user expect here ^ ? Should it print `foo=HELLO, bar=none` or `foo=none, bar=HELLO`
