### ISSUE TITLE
[Question] Makes sense an overridable Task<T> OnExecuteAsync ?

### ISSUE THREAD

**Issue by ghost** [natemcmaster/CommandLineUtils#395]
Hi all,

today i was wondering if for other people an 
```csharp
public static async Task<T> ExecuteAsync<TApp>(CommandLineContext context, CancellationToken cancellationToken = default)
``` 
method will be useful. Something i feel like returning an object with more information would be useful.

What do you think?

P.S: Maybe it can be done already, in that case if you can point me to an example or doc that would be awesome.

Thanks in advance

**Comment by natemcmaster** [comment]
Can you clarify what this method returns? What is `T`?

As an experiment, see if you can implement this on your own. It should be possible by wrapping `new CommandLineApplication`. That's all the existing static helper methods are doing anyways....https://github.com/natemcmaster/CommandLineUtils/blob/21a73b3d262ac9ef5e89be0428ecaa5b6faead77/src/CommandLineUtils/CommandLineApplication.Execute.cs#L50-L94

**Comment by ppadial** [comment]
True, i was thinking that adding an extension method would work, but, i was thking more on adding this to the library, as example, i would want to return instead of an int:

```csharp
class MyAppReturns
   public int StatusCode
   public string Info <--- it could contains additional information
   public Exception innerException <-- can be null in case of no exception
```

It's just an idea, not sure if it could help to more people.

**Comment by natemcmaster** [comment]
I'll leave this open for more discussion to see if there is interest in this API. Also, I'm not sure what `string Info` would contain, so please elaborate so others can understand what that API means :)
