### ISSUE TITLE
Adding color to help text

### ISSUE THREAD

**Issue by mikegoatly** [natemcmaster/CommandLineUtils#399]
**Is your feature request related to a problem? Please describe.**
I like to make my console applications as pretty as possible, and part of that is to use a splash of color in them to differentiate text from information. This makes the help output of my applications stand out as it lacks this same differentiation.

**Describe the solution you'd like**
When writing out help text, help text should have the following colored differently from the surrounding text:

* command names
* parameters 

For example:

![image](https://user-images.githubusercontent.com/4577868/96137318-6ee14c00-0ef4-11eb-8e40-2154c499731e.png)

This could be an opt-in feature, controlled by an option on the `HelpOptionAttribute`, e.g.: `[HelpOption(ColorOutput=true)]`

**Comment by mikegoatly** [comment]
I should add that I'd be happy to take a look at this if it's deemed a suitable enhancement.

**Comment by mzorec** [comment]
@natemcmaster  Could we get an answer about this feature please?

**Comment by natemcmaster** [comment]
I'm okay if you want to build this as a new implementation of help text generation, but I probably wouldn't enable it by default for all users. As I learned with Pager (#347), a cool feature that occasionally breaks is worse than plain-old text out that always works. Color can 'break' depending on your terminal preferences, OS type, accessibility settings, etc., so I'd rather leave it opt-in.

**Comment by mikegoatly** [comment]
@natemcmaster I'll look into this as I have time - thanks!

**Comment by mikegoatly** [comment]
Right, I've had a bit of a play with this. We can't use Console.ForegroundColor and the like because we're often just building strings and writing them out at a later date.

This means to get this working we'll need to rely on [ANSI escape codes](https://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html) to apply colors. There are drawbacks to this, such as it's not supported in all terminals, most notably CMD in Windows 10 less than 1511 (and we'll need to use some interop code to enable it even then).

I've put something rough to do the coloring on a [branch over here](https://github.com/mikegoatly/CommandLineUtils/commits/color-help-text). When `ColorText.Enabled` is `false` (the default) then any calls to ColorText are effectively a no-op.

Still to do:

- Provide a convenient way to enable color text (Attribute and associated convention?)
- Is ColorText useful beyond just this help text implementation? I could see it being useful for other messages I would emit when writing console text out, so should it become part of the public API?

**Comment by natemcmaster** [comment]
I'd like to see if we can avoid using ANSI escape codes. I've been down that path before and it usually leads to color bugs and system compat issues, and I'm concerned about adding code to P/Invoking kernel32. 

Why can't we use Console.ForegroundColor? I believe in the simple case, the TextWriter we're operating on is the same as `System.Console.Out`, so using `System.Console.ForegroundColor` should be okay.

> Provide a convenient way to enable color text

What about something like this? Presumably, the IHelpTextGenerator API allows you to implement this on your own already.

```txt
var app = new CommandLineApplication
{
    HelpTextGenerator = new ColorHelpTextGenerator(),
};

**Comment by mikegoatly** [comment]
Understood - I'd not considered that it was `Console.Out` just being passed around - I'll have a look when I next have some time. If I recall, there were a couple of points where text was first emitted to a `StringBuilder`, which might need a bit more work to unpick.

Perhaps I was just having too much fun :smile:
