### ISSUE TITLE
Generated help output formats (markdown, man page, html) 

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#4]
Keeping docs in sync with code is a pain. Let's automate this, if we can. We already have a generate which produces console output. Would be awesome if it could produce that output in a format that could be piped to a file.
```
tool --help:man > tool.1.man
tool --help:html > tool-help.html
```

**Comment by natemcmaster** [comment]
Labeling as help-wanted. Let me know if you want to tackle this one and let's create a design together.

**Comment by jhitchcock** [comment]
I started on something, it's pretty rough but I'm using it to output an MD file into the repository root, so you get a readmefile covering the methods and params

https://gist.github.com/jhitchcock/bf25c999a38ba24b2df06abba9e374d6

Let me know if its of interest, and I can tidy it up a bit and PR

**Comment by natemcmaster** [comment]
Yes, I'd be interested in adding a class for this. If you can make it implement [IHelpTextGenerator](https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/HelpText/IHelpTextGenerator.cs), that would be great.
