### ISSUE TITLE
[Feature Request] Option.IsSpecified

### ISSUE THREAD

**Issue by khionu** [natemcmaster/CommandLineUtils#40]
Flags are one of the most common kinds of options in CLIs, but as is, there is no way to tell if an Optional is called without values or not called at all.

**Comment by khionu** [comment]
Nvm. Might have a few libraries going out after [this](https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine) releases

**Comment by natemcmaster** [comment]
You can call `.HasValue()` to determine if a `NoValue` flag was specified. It may not be the most obvious name, but its the API we inherited from Microsoft.Extensions.CommandLineUtils. I'm open to proposals for a better name.
