### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by AldeRoberge** [natemcmaster/CommandLineUtils#400]
Prompt.GetYesNo("Do you want to proceed?");

should be

Prompt.GetYesNo("Do you want to proceed?", true);

As 'defaultAnswer' is a required param

**Comment by AldeRoberge** [comment]
https://github.com/natemcmaster/CommandLineUtils/blob/main/README.md

**Comment by natemcmaster** [comment]
Pull requests to fix docs are welcome
