### ISSUE TITLE
Prompt checkbox support

### ISSUE THREAD

**Issue by redbaty** [natemcmaster/CommandLineUtils#41]
It would be nice if this supported checkboxes like this: https://www.npmjs.com/package/prompt-checkbox
If possible I'll try to implement in during my free time this week.

**Comment by natemcmaster** [comment]
I'd take a PR for this. Before you get too far on implementing it, can you post here what the usage would look like in C#?

**Comment by redbaty** [comment]
@natemcmaster Yup, just got home, I`ll post a preview in a few

**Comment by redbaty** [comment]
@natemcmaster Hey, I`ve made a simple demo here: https://github.com/redbaty/CommandLineUtils
Just run the hello world sample and you`ll see it, I won`t create a pull request yet cause its still early days

**Comment by natemcmaster** [comment]
I think I'd prefer the main usage to be named `Prompt.GetOption` to fit with other methods on Prompt, like GetPassword, GetString, GetInt, etc.

Do you plan to also implement radio vs checkbox, allowing multiple responses, nested sections of options, custom response values, etc? The NPM library you linked to is pretty extensive.

**Comment by redbaty** [comment]
> I think I'd prefer the main usage to be named Prompt.GetOption to fit with other methods on Prompt, like GetPassword, GetString, GetInt, etc.

@natemcmaster Thanks for the name, I couldn't get my head around one that would fit the naming scheme 😄 

> Do you plan to also implement radio vs checkbox, allowing multiple responses, nested sections of options, custom response values, etc? The NPM library you linked to is pretty extensive.

Yes I do, there's currently the radio option, but I have no tested it yet. I'll get to implement the other features today as well, and try to write some tests

**Comment by redbaty** [comment]
I've created the pull request: https://github.com/natemcmaster/CommandLineUtils/pull/42
