### ISSUE TITLE
Make HelpOption discovery work same as for any other option

### ISSUE THREAD

**Issue by lGSMl** [natemcmaster/CommandLineUtils#410]
At the moment custom command options are searched inside command instance and any parent up the inheritance chain

```
        public IEnumerable<CommandOption> GetOptions()
        {
            var expr = Options.AsEnumerable();
            var rootNode = this;
            while (rootNode.Parent != null)
            {
                rootNode = rootNode.Parent;
                expr = expr.Concat(rootNode.Options.Where(o => o.Inherited));
            }

            return expr;
        }
```

But for HelpOption search stops if parent does not have it, even though it may be set further up the chain
```
 public CommandOption? OptionHelp
        {
            get
            {
                if (_optionHelp != null)
                {
                    return _optionHelp;
                }
                return Parent?.OptionHelp?.Inherited == true
                    ? Parent.OptionHelp
                    : null;
            }
            internal set => _optionHelp = value;
        }
```
It would be more clear, as for me, if OptionHelp would follow same discovery logic as  used for other options.

I have hit some inconvenience working with this when trying to create extension method for CommandLineApplication that would clear duplicate options from subcommands if any.

**Comment by natemcmaster** [comment]
I would be open to a pull request that implements this. I've marked as <kbd>help-wanted</kbd> as I'm not planning to implement on my own, but this seems like a valuable enhancement.
