### ISSUE TITLE
[Question] How can I prevent the output of "version" in the regular help-text?

### ISSUE THREAD

**Issue by buehler** [natemcmaster/CommandLineUtils#413]
Dear @natemcmaster 
First of all; thanks for this package! It's a breeze!
And I use it a lot.

One thing that I stumbled across is the fact that the output of the version option
is always added to the helptext. I have a usecase where I don't want the helptext
to show the version information.

Is this possible via configuration and I just did not find the documentation?

Regards
Chris

**Comment by natemcmaster** [comment]
@buehler you should be able to suppress this be changing the implementation of https://natemcmaster.github.io/CommandLineUtils/docs/help-text.html#custom-help-text. Something I'll add to the docs is that often the easiest way to do this is to inherit from DefaultHelpTextGenerator and override the parts you want to change. Look here for starters

https://github.com/natemcmaster/CommandLineUtils/blob/9f57dfecb4486f718866cd2bed4e2e7f70b21a9c/src/CommandLineUtils/HelpText/DefaultHelpTextGenerator.cs#L76-L92

**Comment by buehler** [comment]
Perfect thank you @natemcmaster !
