### ISSUE TITLE
Roadmap for 2021

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#418]
## 2020 Review
2020 was a good year for this library! In the last 12 months, this project...

* Almost hit **3 million downloads** on [NuGet.org](https://www.nuget.org/packages/McMaster.Extensions.CommandLineUtils/)! (Increase of about 1.8 million downloads)  🎉 
* Received [48 pull requests](https://github.com/natemcmaster/CommandLineUtils/pulls?q=is%3Apr+created%3A2020-01-01..2020-12-31+-author%3Anatemcmaster+-author%3Aapp%2Fdependabot-preview+) from external contributors (up from 41 in 2019). 👍 
* And released versions 3.0 with bug fixes and a few small features. ✨ 

## 2021 Roadmap

In 2021, I plan to continue this project. This project is open for contributions. Consider the issue list the authoritative source of release planning and feature design. 

### 4.0 Release

As of writing, I have one project milestone open -- [**Release 4.0**](https://github.com/natemcmaster/CommandLineUtils/milestone/29). This new major version is primarily about cleanup of some API choices made a long time ago which required a breaking change to support a few ease-of-use features like [default values](https://github.com/natemcmaster/CommandLineUtils/issues/82) on options.

As always, feel free to open issues if there is something you'd like addressed. Use https://github.com/natemcmaster/CommandLineUtils/issues/404 to discuss this release further.

### Interested in becoming an official contributor?

I spend only an hour or two every month checking in on GitHub. Reach out to me at open-source@natemcmaster.com to discuss becoming an official contributor if you'd like to drive improvements, merge pull requests, and have more access to the issue tracker.

Happy New Year!
Nate

**Comment by meisenring** [comment]
This project is great! 👍
Looking forward to a similar post with perhaps an updated Roadmap for 2022? 😃
Happy holidays!

**Comment by natemcmaster** [comment]
Yes, here is the latest roadmap for 2022 and beyond - https://github.com/natemcmaster/CommandLineUtils/issues/485
