### ISSUE TITLE
[Question] Can I print Enum in help text lowercased?

### ISSUE THREAD

**Issue by stefanjarina** [natemcmaster/CommandLineUtils#430]
Hello,

I would like to ask if there is a way to print Enum based option all lowercased in help text?

e.g. I have:

```
public enum Repos
{
    [Description("azure")]   <--  usually can be achieved with description annotation, but it does not work
    Azure,
    [Display(Name = "bitbucket")]   <-- does not work as well
    Bitbucket,
    Github,
    Gitlab
}
```
and
```
[Required]
[Option(Description = "Required. Specify repository (case-insensitive)", Inherited = true)]
public Repos Repo { get; set; }
```
with above options I get printed:
```
Options:
  -?|-h|--help      Show help information
  -r|--repo <REPO>  Required. Specify repository (case-insensitive)
                    Allowed values are: Azure, Bitbucket, Github, Gitlab    <--- want this to be lowercased
```

so far the only possibility I can think of (without rewriting the entire help text generator) is to name enum with lowercase:
```
public enum Repos {
  azure,
  github,
  ...
}
```

or is there a better way how to achieve it?

Thank you,
Stefan

**Comment by natemcmaster** [comment]
Not possible, but should be possible to implement by updated this code to recognize attributes on enum values. https://github.com/natemcmaster/CommandLineUtils/blob/1d6e1a5f04e1effc06e09d70ee89e810df7d715b/src/CommandLineUtils/HelpText/DefaultHelpTextGenerator.cs#L412-L435
