### ISSUE TITLE
[Question] Complex types and attributes

### ISSUE THREAD

**Issue by CrispyDrone** [natemcmaster/CommandLineUtils#432]
Hi,

I was looking through the documentation but was unable to find any related to my problem.

I would like to be able to capture related options or arguments into a complex type, simply for maintainability reasons. Is this possible while using the attribute conventions? I briefly explored the code base, and looking at how `TypeConverter`s and the value parsers are used I would say no, but I might be wrong.

```csharp
using McMaster.Extensions.CommandLineUtils;
using McMaster.Extensions.CommandLineUtils;
using System;
using System.Threading.Tasks;

namespace Test
{

    [Command(Name = "myapp")]
    [Subcommand(typeof(TestCommand))]
    public class Program
    {
        public static async Task<int> Main()
        {
            var app = new CommandLineApplication<Program> { UnrecognizedArgumentHandling = UnrecognizedArgumentHandling.StopParsingAndCollect };
            app.Conventions.UseDefaultConventions();

            string[] myargs = new string[] { "test", "--hello", "there", "-v", "detailed", "--logdestionation", "file", "logfile", "~/Desktop/logging.txt" };
            return await app.ExecuteAsync(myargs);
        }

        protected int OnExecute(CommandLineApplication app)
        {
            app.ShowHelp();
            return 1;
        }
    }

    [Command(Name = "test")]
    public class TestCommand
    {
        public LoggingOptions Logging { get; set; }
        [Option(CommandOptionType.SingleValue, ShortName = "h", LongName = "hello")]
        public string Hello { get; set; }

        public int OnExecute(CommandLineApplication app)
        {
            Console.WriteLine(Hello);
            Console.WriteLine(Logging);
            return 0;
        }
    }

    public class LoggingOptions
    {
        [Option(CommandOptionType.SingleValue, ShortName = "v", LongName = "verbosity", Description = "Sets the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed].")]
        public string Verbosity { get; set; }

        [Option(CommandOptionType.SingleValue, ShortName = "", LongName = "logdestination", Description = "Destination for logging.")]
        public string LogDestination { get; set; }

        [Option(CommandOptionType.SingleValue, ShortName = "", LongName = "logfile", Description = "Log to the named file.")]
        public string LogFile { get; set; }

        public override string ToString()
        {
            return $"verbosity: {Verbosity} destination: {LogDestination} file {LogFile}";
        }
    }
}
```

I don't want to use inheritance to share these properties between different classes as C# is limited by single inheritance and I think in a complex application inheritance quickly makes the commands hard to maintain.

To be entirely truthful, I wouldn't care much about having to duplicate properties among different commands but I am trying to propose a refactoring in a particular codebase that's suffering from inheritance issues between commands (imo), and I'm pretty sure a counter argument they could raise would be the duplication of shared options/values between different commands.

Using the builder API I think this problem could partially be solved as I would be able to simply put the `AddOption` (or argument) statements behind some method I can easily invoke from the configuration of the multiple subcommands, but I guess I lose the ability to use these complex types at all?

Thanks!

**Comment by natemcmaster** [comment]
You could try implementing your own convention. That’s really the best way to customize behaviors like this.

Here are some examples of conventions -https://github.com/natemcmaster/CommandLineUtils/blob/main/docs/samples/custom-attribute/Program.cs

https://github.com/natemcmaster/CommandLineUtils/blob/main/docs/samples/custom-conventions/Program.cs

**Comment by CrispyDrone** [comment]
Thanks for the swift reply @natemcmaster 

I'll check out the custom conventions and share an update once I manage to get it all to work. If I'm successful, I'll try to create a pull request for the website documentation as well.
