### ISSUE TITLE
[Question] Is it possible to return a value from a Command OnExecute ?

### ISSUE THREAD

**Issue by fededim** [natemcmaster/CommandLineUtils#433]
I have the following code, is it possible somehow to return an int value on OnExecute of a Command ? Unluckily the method takes an Action instead of a Func\<Int\> as parameter.

```
var app = new CommandLineApplication { Name = "SincroADR_Batches", Description = "A console application to start batches" };

app.HelpOption(inherited: true);
app.Command("hashingplates", hashingCmd =>
{
	hashingCmd.OnExecute(async () =>
	{
		var hashing = services.GetRequiredService<HashingBatch>();
		await hashing.Run();
	});
});

// shown when no command is passed
app.OnExecute(() =>
{
	Console.WriteLine("Specify a subcommand");
	app.ShowHelp();
	return 1;
});

return await app.ExecuteAsync(args);
```

**Comment by lGSMl** [comment]
both sync and async `OnExecute` accept `Func<int>`, specifically to return int for exit code, and you already returning int in your example, so more context needed.

**Comment by natemcmaster** [comment]
@lGSMl  is correct. See the [API Reference here](https://natemcmaster.github.io/CommandLineUtils/v3.0/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html#McMaster_Extensions_CommandLineUtils_CommandLineApplication_OnExecuteAsync_System_Func_System_Threading_CancellationToken_System_Threading_Tasks_Task_System_Int32___) for more overloads and [extension methods](https://natemcmaster.github.io/CommandLineUtils/v3.0/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html#extensionmethods).

**Comment by fededim** [comment]
Ok sorry I had to use OnExecuteAsync, it was returning an error on the following code

```
hashingCmd.OnExecute(async () =>
	{
		var hashing = services.GetRequiredService<HashingBatch>();
		return await hashing.Run();
	});
```
