### ISSUE TITLE
Support TAB completion providers

### ISSUE THREAD

**Issue by ChristophLindemann** [natemcmaster/CommandLineUtils#438]
When you make your own CLI, it would be realy nice to be able have `TAB` completion in the shell. So that you could tab through the available commands, subcommands and arguments.
The same way you can do with PowerShell command-lets

`CommandLineUtils` could provide an extension, that would allow users to easily install `TAB` completion from the current shell. 

This could be done by providing 2 commands out of the (CommandLineUtils) box.

1) `install-autocomplete` command, which installs the autocompletion in the current shell, or via an optional `-shell` parameter
2) `query-autocomplete` command (hidden), which is called by the shells autocomplete function

More reading:
- [Microsoft Docs: How to enable TAB completion for the .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete)
- [Command-line tab completion for Octopus CLI (how it was implemented)](https://octopus.com/blog/tab-completion-for-the-octopus-cli)
- [`dotnet` CLI scripts for registering tab completion](https://github.com/dotnet/cli/tree/master/scripts)

**Comment by natemcmaster** [comment]
If System.CommandLine has the features you want, I would recommend using that. At one point I considered re-implementing this project as a wrapper around System.CommandLine, but lost interest in doing so myself.

Marking this as help-wanted. If anyone is interested in implementing this and wants to help design the feature, comment on this issue so you can be marked as the assignee.
