### ISSUE TITLE
Report missing value for option not only when option is the last in the arguments array

### ISSUE THREAD

**Issue by lGSMl** [natemcmaster/CommandLineUtils#439]
Currently if option requires value, and it is not provided, it will report this properly only in case option was given as the last argument:

```
mycommand --requiredOptionA "a" --requiredOptionB
Missing value for option 'requiredOptionB'
```

but if value is omitted for the option in the middle of args - parser will just grab next option and treat it as a value, effectively fubar rest of arguments

```
mycommand --requiredOptionA --requiredOptionB "b"
Unrecognized command or argument 'b'
```
With couple of options it is still more or less understandable where the problem is, but in a complex use case with few options and arguments (which are in addition usually expanded from shell variables) error may be really confusing.

-----

I can see two ways of dealing with this:
 - add extra logic around unexpected argument parsing or suggestion generator that should scan args for this particular case and append additional info to error message
 - add option for parser to treat every argument starting with single or double dash as option name

**Comment by natemcmaster** [comment]
You're right -- the current parser naively just grabs the next string value. To make this error message better, I imagine we would need think of a safe way for the parser to recognize that `--option1 --option2` is a mistake. This gets a little tricky if you consider this example:
```
Usage: join [--join-str <VALUE>] [-v|--verbose]  arg1 arg2
```
As I user, I would expect this behavior
```
$ join --join-str / foo bar
foo/bar

$ join --join-str -s- foo bar
foo-s-bar

$ join --join-str -s- -v  foo bar
verbose-log: Joining strings
foo-s-bar
```
But what should happen for
```
$ join --join-str -v  foo bar
```
Should this print `foo-vbar`? or is this usage is an error?

**Comment by lGSMl** [comment]
I thought the last comment ended with a rhetorical question - but due to no other activity - I start to suspect it was not  : D

That will fall under my 2nd suggestion to make optional reservation of any command argument starting with `-` or `--`, so in this case your last example should result in error `ERROR: --join-str value required` or smth if the option is enabled, otherwise it should behave as it is now. That way if developer knows there is a requirement for arguments starting with dash - he can omit the option, otherwise he may enable it and have more safe and friendly UX
