### ISSUE TITLE
Support inheritance for help option

### ISSUE THREAD

**Issue by rmcc13** [natemcmaster/CommandLineUtils#44]
Neither of the `HelpOption` methods in the builder API provide the ability to specify that the option should be inherited. It is common to use the same help option for subcommands, so it would be nice to specify the option once on the root `CommandLineApplication` instance and not have to do it for every subcommand.

I also think since this is such a common practice for CLI tools (see git or dotnet), the help option should be inherited by default, but this could be considered a breaking change.

In the event that this feature is rejected, I would like to point out that the generated help from calling the `.ShowHelp` method suggests the help option for subcommands even if there is no help option specified on them.

**Comment by rmcc13** [comment]
I opened a PR with my initial changes for this. Currently the default behavior is to set inheritance to false to be consistent with existing behavior, however I can easily change this if you think it makes sense to default to true.

**Comment by natemcmaster** [comment]
I'm okay with adding this feature as an overload of `HelpOption()`.
