### ISSUE TITLE
[Question] Integration with ASP NET Core 5

### ISSUE THREAD

**Issue by jose2k72** [natemcmaster/CommandLineUtils#441]
Hello I am something new in this of Hosted Services and although I have read and tried something I have the following doubt.

Is there a way to use CommandLineUtils in an ASP.NET (Net 5) project.

I know that both CommandLineUtils and ASP use Hosted Services, but what I don't see is how to mix the two so they can work together.

**Comment by natemcmaster** [comment]
I've never tried. If you find a good minimal sample, mind sharing what you figured out?
