### ISSUE TITLE
Inheritance and Options are broken

### ISSUE THREAD

**Issue by peter-shinydocs** [natemcmaster/CommandLineUtils#447]
**Describe the bug**

- Somewhere between 2.4.4 and 2.5.0 something changed that breaks inheritance with the options.
- Getting 

> System.InvalidOperationException : Ambiguous option name. Both Shinydocs.CognitiveToolkit.Tests.UI.CommandLine.Commands.BaseCommand.Test and Shinydocs.CognitiveToolkit.Tests.UI.CommandLine.Commands.DerivedCommand.Test produce a CommandOption with the name 't'.

- Suspected change .. https://github.com/natemcmaster/CommandLineUtils/pull/288

**To Reproduce**

1. Set up Classes

```
public abstract class BaseCommand { 	
[Option(Description = "Example (Required)")] 	[Required] 	
public string? Test { get; set; } }  

[Command(Name = "CognitiveToolkit Test")] 
public class DerivedCommand : BaseCommand { 	
[Option(Description = "I actually want this description  (Required)")] 	[Required] 	
public new string? Test { get; set; } }
```

2. Run cli.Conventions.UseDefaultConventions();

**Expected behavior**
I get the description of the derived class (like it was in 2.4.4

**Screenshots**

**Additional context**

**Comment by natemcmaster** [comment]
I'm not sure if there is a way at runtime to handle this, but if you can figure it out, feel free to propose a pull-request to fix.

Marking this as help-wanted.
