### ISSUE TITLE
Ctrl+C does not stop synchronous Execute when called from the HostBuilder.RunCommandLineApplicationAsync

### ISSUE THREAD

**Issue by lucastheisen** [natemcmaster/CommandLineUtils#449]
**Describe the bug**
Our application has  many subcommands, some of which are synch, some async.  We use the HostBuilder to initialize all the DI objects and as such, `RunCommandLineApplicationAsync` appears to be running the application async regardless of whether or not the _eventual commmand_ is sync or async.  From what i have gathered on other related issues [if run async, then application shutdown is waited on before exit after `Ctrl+C`](https://github.com/natemcmaster/CommandLineUtils/issues/292#issuecomment-548601040).  I am not explicitly supplying a cancellation token, but the [`CommandLineLifetime` appears to prevent immediate shutdown, regardless](https://github.com/natemcmaster/CommandLineUtils/blob/main/src/Hosting.CommandLine/Internal/CommandLineLifetime.cs#L86)

**To Reproduce**
Use `HostBuilder`

```csharp
        public static async Task<int> Main(string[] args)
            => return await new HostBuilder()
                // more initialization here
                .RunCommandLineApplicationAsync<Program>(args)
                .ConfigureAwait(false);
```

With a synch subcommand

```csharp
        protected int OnExecute(CommandLineApplication app)
            => longRunningSynchronousWork();
```

Start, then press `Ctrl+C`

**Expected behavior**
`Ctrl+C` immediately stops application

**Additional context**
This can be worked around with:

```csharp
        protected int OnExecute(CommandLineApplication app)
        {
            Console.CancelKeyPress += (_, e) => e.Cancel = false;

            return longRunningSynchronousTask();
        }
```

**Comment by natemcmaster** [comment]
Marking as help-wanted. If you have good way to fix this, feel free to send a pull request.
