### ISSUE TITLE
How to define behavior that is executed in case of a command-parsing error? [Question] 

### ISSUE THREAD

**Issue by janca777** [natemcmaster/CommandLineUtils#450]
On execution, my program takes two arguments it needs to run:
```
static Task<int> Main(string[] args)
{
   return CommandLineApplication.ExecuteAsync<MyUpdateService>(args);
}

[Argument(0, Description = "Filepath")]
     
private string Filepath { get; }

[Argument(1, Description = "UpdateMode")]

private int Mode { get; }
```
I want to show a messagebox in case the program is run with **too few/ too many arguments**, or the **arguments don't match the required types** (1: string, 2: int).

Since this cannot be achieved by simply wrapping a try/catch-block around it: Can this be done?

**Comment by natemcmaster** [comment]
Did you try adding `[Required]` to both arguments?

```csharp
[Required, Argument(0, Description = "Filepath")]
private string Filepath { get; }
```

If that still isn't giving you the error you want, try adding an "OnValidationError" method ([example](https://github.com/natemcmaster/CommandLineUtils/blob/e0b6a2cde6bbda2004e113aa2499548a2e51f39e/test/CommandLineUtils.Tests/ValidationTests.cs#L168-L177)) or using `new CommandLineApplication` instead ([example](https://github.com/natemcmaster/CommandLineUtils/blob/e67be508c60a20918f04992bb7cb9e476a2ed246/src/CommandLineUtils/CommandLineApplication.Execute.cs#L74-L94))

**Comment by janca777** [comment]
> Did you try adding `[Required]` to both arguments?
> 
> ```cs
> [Required, Argument(0, Description = "Filepath")]
> private string Filepath { get; }
> ```
> 
> If that still isn't giving you the error you want, try adding an "OnValidationError" method ([example](https://github.com/natemcmaster/CommandLineUtils/blob/e0b6a2cde6bbda2004e113aa2499548a2e51f39e/test/CommandLineUtils.Tests/ValidationTests.cs#L168-L177)) or using `new CommandLineApplication` instead ([example](https://github.com/natemcmaster/CommandLineUtils/blob/e67be508c60a20918f04992bb7cb9e476a2ed246/src/CommandLineUtils/CommandLineApplication.Execute.cs#L74-L94))

**Comment by janca777** [comment]
Thanks for your help.
Eventhough ([example](https://github.com/natemcmaster/CommandLineUtils/blob/e67be508c60a20918f04992bb7cb9e476a2ed246/src/CommandLineUtils/CommandLineApplication.Execute.cs#L74-L94)) seems like the way to go, I have no idea how to implement this in my code. 

However, I was able to solve this myself, and you can close this issue.
