### ISSUE TITLE
Option attribute doesn't support property overrides

### ISSUE THREAD

**Issue by d1820** [natemcmaster/CommandLineUtils#454]
**Describe the bug**
If a property is marked as virtual and in a base class with the options attribute applied. When an override of that property is the implemented the option attribute complains for duplicate names.

**To Reproduce**

Base class 
```csharp
[Option(CommandOptionType.SingleValue, LongName = "folder", ShortName = "f", Description = "The folder to execute actions in. This could be where to read from or where to output to")]
        public virtual string WorkingFolder { get; set; }
```

Override Class
```csharp
[Option(CommandOptionType.SingleValue, LongName = "folder", ShortName = "f", Description = "Override Description")]
        public override string WorkingFolder { get; set; }
```

**Expected behavior**
The option attribute of the override should be applied.

**Error**

```
Ambiguous option name. Both CLI.CliBase.WorkingFolder and CLI.Infra.PullCmd.WorkingFolder produce a CommandOption with the name 'f'.
```

**Comment by natemcmaster** [comment]
Seems like the override option should win. This fix is probably a matter of improving the reflection to recognize overrides. Marking as help-wanted as I would accept a pull request to fix this behavior.
