### ISSUE TITLE
[Question] Include IUnhandledExceptionHandler into the docs

### ISSUE THREAD

**Issue by vany0114** [natemcmaster/CommandLineUtils#456]
Hey guys, is there any reason why the usage of `IUnhandledExceptionHandler` is not documented? I think that would be nice to include in the documentation the usage of `IUnhandledExceptionHandler` (maybe under Advanced concepts?) I figured it out the hard way by looking into the source code because I needed a global way to manage unhandled exceptions. I can help if you guys consider it makes sense.

**Comment by natemcmaster** [comment]
Well, there is https://natemcmaster.github.io/CommandLineUtils/v3.0/api/McMaster.Extensions.Hosting.CommandLine.IUnhandledExceptionHandler.html, but I supposed you mean more than auto-generated API ref docs? Feel free to proposed new docs as a pull request :)
