### ISSUE TITLE
Difficult to omit short names using attributes

### ISSUE THREAD

**Issue by atruskie** [natemcmaster/CommandLineUtils#48]
Hi, I'm using this library for a pretty large CLI application. One command, in particular, has many options with similar names, for example:

```
            [Option(Description = "...")]
            public string AnalysisIdentifier { get; set; }

            [Option(Description = "...")]
            public TimeAlignment AlignToMinute { get; set; } = TimeAlignment.None;

            [Option(Description = "...")]
            public bool WhenExitCopyLog { get; set; }

            [Option(Description = "...")]
            public bool WhenExitCopyConfig { get; set; }
```

The automatic short name generator complains if two short names are the same (fair enough) but what I'd like to do is disable short names for lesser-used options. I've tried:

- Setting `ShortName` to `null` but that doesn't work because of https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/Attributes/OptionAttributeBase.cs#L60
- Setting `ShortName` to `""` (empty string) but it considers empty strings to be duplicate names (https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/Internal/ReflectionAppBuilder.cs#L270)

I realise I could use the template string form and omit the short name part, but I've got a couple hundred options over a dozen subcommands and I don't want to maintain a separate string for all of those options (the auto kebab casing for full names is a great help!).

What do you think?

I've got three ideas:

- Consider using `""` to represent a not having short name
- Adding a `bool NoShortName`  property to `OptionAttribute` (eww)
- Or, I could implement my own `LongOptionAttribute` class which will not set `ShortName` because it won't have the `Configure` method from `OptionAttribute`
  - It seems the extensibility options of `OptionAttributeBase` are limited however

**Comment by natemcmaster** [comment]
Seems like `string.Empty` is the easiest solution, but still a pain for you because you'd need to write `ShortName = ""` on your hundreds of options.

The idea I like best is the on you proposed: make it possible for you to write your own attribute. I started playing with supporting a feature I'm calling "conventions" which would enable you to do exactly list. See #31 and the features/conventions branch

**Comment by atruskie** [comment]
I'm pretty keen for the convention API (and, as an aside, for registering custom value converters as well).

However, I had a brief look at the branch and I don't believe I have the time/mental capacity to implement what I need. I'd be happy to contribute in the future though.

For now, I've made this patch: https://github.com/atruskie/CommandLineUtils/commit/56a54c17ab502892cbf41d8da2c5d64bc8514f83
While annoying to edit a few hundred things, I can at least do it with Find-Replace/Copy-Paste and it'll keep me going. If you think it's useful I'll submit a PR.
