### ISSUE TITLE
Custom IHelpTextGenerator not loaded when using builder.RunCommandLineApplicationAsync extension method

### ISSUE THREAD

**Issue by d1820** [natemcmaster/CommandLineUtils#487]
Adding a custom IHelpTextGenerator  is not honored when using the McMaster.Extensions.Hosting.CommandLine extensions. The default help generator is still used.

The breakpoint is hit to set the custom generator but the output is still for the default help generator. Also no breakpoints are hit in the custom generator aside from the constuctor

```
 var result = await builder.RunCommandLineApplicationAsync<KbxtCliCmd>(args, app => { 
                    app.HelpTextGenerator = new HelpGeneratorAscii();
                });
```

Versions

```
<PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="3.1.0" />
    <PackageReference Include="McMaster.Extensions.Hosting.CommandLine" Version="3.1.0" />
```

also tried latest version
```
<PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="4.0.0" />
    <PackageReference Include="McMaster.Extensions.Hosting.CommandLine" Version="4.0.0" />
```

**Expected behavior**
The custom HelpGenerator should be used

**Screenshots**
Standard Output
![image](https://user-images.githubusercontent.com/377631/148245278-b5acd95a-2fb8-42b9-9f4f-96b951ee3c98.png)

Expected ascii table pipes at the beginning and end of each line

**Comment by natemcmaster** [comment]
Marking as “help wanted”. I would accept a pull request to fix this.
