### ISSUE TITLE
Allow supply a custom help generator to Execute<T> methods

### ISSUE THREAD

**Issue by atruskie** [natemcmaster/CommandLineUtils#52]
Presently I believe it is not possible to provide an IHelpGenerator to the `CommandLineApplication.ExecuteAsync<MainArgs>()` method.

It would be good to add support for this: As a use case, I'd like to inject extra metadata (outside the scope of this tool) into help messages

A simple solution is to add another overload to `ExecuteAsync`.

A more interesting idea might be to allow for creating a `CommandLineApplication` instance, which can then be modified, and to add an instance method version of `Execute<T>` and `ExecuteAsync<T>` which builds off the existing CommandLineApplication instance. This approach might prove more general (fewer ways to configure the same thing, allows access to other functionality like `ValidationErrorHandler`) and allow for other interesting things (like mixed builder and reflection generation).

I'm happy to make a contribution but would appreciate guidance on public APIs.

**Comment by natemcmaster** [comment]
> A more interesting idea might be to allow for creating a CommandLineApplication instance

For other reasons, this is kind of the approach I took. It's a little more verbose, but you will be able to do this in the latest 2.2.0 daily builds like this. 

```c#
public static int Main(string[] args)
{
  var app = new CommandLineApplication<MainArgs>
  {
     HelpTextGenerator = new MyHelpTextGenerator()
  };
  app.Conventions.UseDefaultConventions();
  return app.Execute(args);
}
```

If you still think CommandLineApplication.ExecuteAsync that takes an IHelpTextGenerator is useful, I'd take a PR for it. But closing for now as I'm not planning on adding it.
