### ISSUE TITLE
Nullable boolean Options aren't supported

### ISSUE THREAD

**Issue by goncalo-oliveira** [natemcmaster/CommandLineUtils#530]
**Describe the bug**

When using a nullable boolean with an option of type `CommandOptionType.SingleOrNoValue`, the argument value isn't binded. It only works if the property isn't nullable.

**To Reproduce**

Using version 4.0.2 of the library. To reproduce, add a property with a nullable boolean

```csharp
public class InstallCommand
{
    [Option( "--install-proxy", CommandOptionType.SingleOrNoValue )]
    public bool? InstallProxy { get; set; }

    protected Task<int> OnExecute( CommandLineApplication app )
    {
        Console.WriteLine( $"install proxy: {InstallProxy}" );

        return Task.FromResult( 0 );
    }
}
```

Execute with the argument `--install-proxy` or `--install-proxy=true` or `--install-proxy=false`.

The `InstallProperty` value will still be set to null.

The output

```bash
$ dotnet run -- install --install-proxy
install proxy: 
```

**Expected behavior**

I would expect the argument value to be binded to the property value.

**Screenshots**

![image](https://user-images.githubusercontent.com/2210485/222205526-10095c99-756a-4292-903b-4c0b553ea18f.png)

**Comment by natemcmaster** [comment]
Did you try this instead? https://github.com/natemcmaster/CommandLineUtils/blob/81199c7ec68367ea9612be55719dc1fe08f658da/docs/docs/options.md?plain=1#L73-L76
