### ISSUE TITLE
Nuget package System.ComponentModel.Annotations V5.0.0 is deprecated

### ISSUE THREAD

**Issue by Bertk** [natemcmaster/CommandLineUtils#533]
**Describe the bug**
_McMaster.Extensions.CommandLineUtils.csproj_ uses **deprecated** nuget package System.ComponentModel.Annotations.

**To Reproduce**
Check nuget.org status => https://www.nuget.org/packages/System.ComponentModel.Annotations/5.0.0

**Expected behavior**
No deprecated package is used.

**Screenshots**
![image](https://github.com/natemcmaster/CommandLineUtils/assets/2315215/7f0b3d54-3452-4f3b-98d7-15d5cd0098c3)

**Comment by natemcmaster** [comment]
I'm not seeing that guidance anymore on nuget.org. I'm guessing Microsoft reversed course once they realized just exactly how many people are using this package?

<img width="903" alt="Screen Shot 2023-06-25 at 2 34 06 AM" src="https://github.com/natemcmaster/CommandLineUtils/assets/2696087/7080ee81-e607-4734-aae3-18778ab3a106">

**Comment by Bertk** [comment]
Yep, this package is not deprecated anymore.
