### ISSUE TITLE
VersionOptionFromAssemblyAttributes - no documentation for template

### ISSUE THREAD

**Issue by digitaldias** [natemcmaster/CommandLineUtils#535]
I'm setting up a small app and wanted to customize the version string returned by `--version.`
I need help finding where in the documentation the template argument's content should look like. 
Currently, I have this: 

```csharp
app.VersionOptionFromAssemblyAttributes("", Assembly.GetExecutingAssembly());
```
Which, of course, won't work! :)

Can someone please advise?

**Comment by natemcmaster** [comment]
Checkout how `app.VersionOptionFromAssemblyAttributes` is implemented. It's a helper method that just calls `.VersionOption`. If you want to customize things, use `.VersionOption` instead https://github.com/natemcmaster/CommandLineUtils/blob/81199c7ec68367ea9612be55719dc1fe08f658da/src/CommandLineUtils/CommandLineApplicationExtensions.cs#L145-L182
