### ISSUE TITLE
[Question] Syntax of templates

### ISSUE THREAD

**Issue by vmelamed** [natemcmaster/CommandLineUtils#537]
I could not find it so far but is there something more to templates' syntax than just: `<short option>|<long option> {<value>}`. For example, can I specify `<short option>|<long option> [<value1>|<value2>|<value3>]` (specify the three possible values for the option), or `<short option>|<long option> <key>=<value>}` (specify a tuple or if multiple - a dictionary), etc.

**Comment by natemcmaster** [comment]
This is something the documentation could clarify. But in the absence of that, here are the test cases which demonstrate currently supported syntax:

https://github.com/natemcmaster/CommandLineUtils/blob/81199c7ec68367ea9612be55719dc1fe08f658da/test/CommandLineUtils.Tests/CommandOptionTests.cs#L12-L31
