### ISSUE TITLE
Can I specify hidden options

### ISSUE THREAD

**Issue by vmelamed** [natemcmaster/CommandLineUtils#538]
**Describe the solution you'd like**
E.g. `[Option("-d|--debug", CommandOptionType.NoValue, Hidden = true)]`

To be honest, I really don't like "easter eggs" but sometimes life is stronger than you...

**Comment by natemcmaster** [comment]
Already possible - https://natemcmaster.github.io/CommandLineUtils/v3.0/api/McMaster.Extensions.CommandLineUtils.OptionAttributeBase.html#McMaster_Extensions_CommandLineUtils_OptionAttributeBase_ShowInHelpText
