### ISSUE TITLE
Dependencies on .NET 5.0

### ISSUE THREAD

**Issue by Arithmeticus** [natemcmaster/CommandLineUtils#546]
The dependency upon System.ComponentModel.Annotations is itself dependent upon .NET frameworks 5.0 and earlier. As a result a C# solution I'm writing that is dependent upon McMaster.Extensions.CommandLineUtils does not pass security checks in our business unit, which requires no pre-.NET 7.0 dependencies. Which is a shame, because I've gotten tremendous mileage from the package. Is there any way to circumvent these dependencies? 

I see that 4.1.1 explicitly attempts to apply to .NET 7.0, but in Visual Studio 2022, the NuGet package manager invokes transitive package System.ComponentModel.Annotations 5.0.0.

Related: #533 

It may be that this is not considered a bug, but rather a nontrivial feature request. But I thought it worthwhile trying, since the alternative means dropping the McMaster package and developing my own alternative from scratch.

**Comment by natemcmaster** [comment]
It may be time to cut a new version of this library which drops outdated dependencies. .NET has evolved quite a bit since this code was originally written.

**Comment by natemcmaster** [comment]
https://github.com/natemcmaster/CommandLineUtils/pull/547
