### ISSUE TITLE
CommandParsingException: Missing value for option 'opt'

### ISSUE THREAD

**Issue by quwtalre** [natemcmaster/CommandLineUtils#55]
Exception throws when user leaves option values blank.

```
Unhandled Exception: McMaster.Extensions.CommandLineUtils.CommandParsingException: Missing value for option 'opt'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.ReflectionAppBuilder`1.Bind(IConsole console, String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at Program.Main(String[] args)
```

Is there any possibility to control this exception with a more global like solution? It is currently a blocker for my requirements, because it cannot be controlled. The property 'ThrowOnUnexpectedArgument' does not affect the behavior. A similar way would be awesome. Maybe the property can be considered in the function.

Within [CommandLineProcessor.cs](https://github.com/natemcmaster/CommandLineUtils/blob/abc6b9d74b658e62fb25fa54b4d75a63c852d986/src/CommandLineUtils/Internal/CommandLineProcessor.cs#L193) the exception simply throws. In my opinion, there must be a more sensitive solution. I tried to implement an validation attribute with the latest release to check whether the value is set or not. It does not work. The exception has been thrown before. Maybe it would be better to output (custom) error message without having the problem, that the application crashed before. 

I've seen there are new values for CommandOptionTypes. Is the desired solution to set the value 'SingleOrNoValue' to prevent the exception?

Thanks for the clarification.

**Comment by natemcmaster** [comment]
Some clarification questions:

What kind of input scenarios are you trying to support? CommandOptionType.SingleOrNoValue was added to support scenarios in which a command line parameter could be a flag `--trace` or a flag with a value `--trace:verbose`.  Its use doesn't ensure an option is set or not.

> to check whether the value is set or not

Are you trying to indicate a option is required? You can use [`[Required]`](https://github.com/natemcmaster/CommandLineUtils/blob/abc6b9d74b658e62fb25fa54b4d75a63c852d986/samples/Validation/Attributes.cs#L14) for that.

Which "latest release" version are you using? I'm guessing your using 2.1.1. In 2.2.0-alpha, I improved the attribute binding API to not throw CommandParsingException anymore (#35).  That said, this error would still cause the app to exit before validation attributes are evaluated.

**Comment by quwtalre** [comment]
I've used version [2.1.1](https://github.com/natemcmaster/CommandLineUtils/releases/tag/v2.1.1) over NuGet, which is currently marked as latest release on GitHub. As it turned out now, the behavior no longer occurs with [v2.2.0-alpha](https://github.com/natemcmaster/CommandLineUtils/releases/tag/v2.2.0-alpha). If the value for required and optional options left empty, the message `Missing value for option 'opt'` is now outputed and the exception does not throw anymore. So the solution is to use the latest pre-release.

Thanks for the help.

**Comment by natemcmaster** [comment]
Great, glad we figured it out. :)
