### ISSUE TITLE
Optional argument for the option

### ISSUE THREAD

**Issue by Demarsch** [natemcmaster/CommandLineUtils#58]
Is it possible to implement the following logic:
`--option mandatory_value [optional_value1] [optional_value2]`
without making to specify `--option` flag multiple times?

**Comment by natemcmaster** [comment]
Nope, sorry. That's not something the parser can support. That syntax would be ambiguous.

You could, however, use an argument that accepts multiple values by setting [CommandArgument.MultipleValues](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandArgument.html?q=MultipleValues#McMaster_Extensions_CommandLineUtils_CommandArgument_MultipleValues) to true. This would allow you to implement `mandatory_value [optional_value1] [optional_value2]`

**Comment by natemcmaster** [comment]
Closing as I can't think of a way to support this.
