### ISSUE TITLE
Sample: `RemainingArgs` should be `RemainingArguments`

### ISSUE THREAD

**Issue by marcrocny** [natemcmaster/CommandLineUtils#61]
https://github.com/natemcmaster/CommandLineUtils/blob/d6ce61da88b72f0ed3677d55d060b602dff2ac98/samples/Subcommands/Program.cs#L22

**Comment by natemcmaster** [comment]
No plans to change this. Both RemainingArgs and RemainingArguments are supported conventions.

https://github.com/natemcmaster/CommandLineUtils/blob/d6ce61da88b72f0ed3677d55d060b602dff2ac98/src/CommandLineUtils/Conventions/RemainingArgsPropertyConvention.cs#L10-L15

**Comment by marcrocny** [comment]
Okay, couldn't figure out why the sample code wasn't working for my project. Thought the docs may have been the issue, but I just fell in the gap between stable and pre-release. Specifically, commit [1f2a851]( https://github.com/natemcmaster/CommandLineUtils/commit/1f2a851e224adc9cd2d9f8313def5c97f7726f01) where the "RemainingArgs" convention was added.

**Comment by natemcmaster** [comment]
Ah I see. Sorry for the confusion.
