### ISSUE TITLE
Calling validators for missing arguments/options

### ISSUE THREAD

**Issue by fubar-coder** [natemcmaster/CommandLineUtils#65]
Currently, it's not possible to write your own `RequiredAttribute`, because the validators are called once for every given value.

**Comment by natemcmaster** [comment]
What are you trying to do? Can you share a snippet? I’m not sure I understand what the issue is.

**Comment by fubar-coder** [comment]
See [my comment in issue #66](https://github.com/natemcmaster/CommandLineUtils/issues/66#issuecomment-375687017).
