### ISSUE TITLE
Support command validators

### ISSUE THREAD

**Issue by fubar-coder** [natemcmaster/CommandLineUtils#66]
This would allow more complex validation scenarios.

**Comment by natemcmaster** [comment]
Can you give a specific example of a kind of validator you would like to run on a command?

**Comment by fubar-coder** [comment]
I try to implement something like `Required`, but only when a given value in the parent model isn't set. My goal is to have an option that is optional - except when a given sub command is issued. It's some kind of guard against user errors.

Acceptable command line examples:

```bash
fluentmigrator migrate --connection "asdasd" --provider "sqlserver"

# same as above
fluentmigrator migrate --connection "asdasd" --provider "sqlserver" up

# both should be acceptable
fluentmigrator migrate --connection "asdasd" --provider "sqlserver" --version 10 up
fluentmigrator migrate --connection "asdasd" --provider "sqlserver" up --version 10

# both should be acceptable
fluentmigrator migrate --connection "asdasd" --provider "sqlserver" --version 10 down
fluentmigrator migrate --connection "asdasd" --provider "sqlserver" down --version 10
```

Not acceptable:
```bash
fluentmigrator migrate --connection "asdasd" --provider "sqlserver" down
```

On a `migrate down`, the `--version` option should be required.

**Comment by natemcmaster** [comment]
That should be pretty easy to add. There is already internal API that you could plug in to. I have no problem making it public. I guess this also depends on how you're implementing this. Are you using the attribute API or the builder API?

Option 1: make this method protected virtual so you could inherit from CommandLineApplication and override
https://github.com/natemcmaster/CommandLineUtils/blob/6230ee0f838f9822daaa13557cb7f2b7e40cf008/src/CommandLineUtils/CommandLineApplication.Validation.cs#L23-L27

Option 2: add a method to add a callback that executes during validation `OnValidation(Func<ValidationResult> callback)`

Option 3: for usage with the attribute API, add a convention that invokes a method called "OnValidation" on the command class

Option 4: is there another API think would be easier?

**Comment by fubar-coder** [comment]
Option 1 would require an additional function to create the derived `CommandLineApplication` for every (sub-)command.

Option 2+3 sounds good

Option 4 ... no idea

**Comment by atruskie** [comment]
Just a drive-by comment: I too have has the use case for complex validation. I just rely on remembering to call my validate method which is not ideal but sufficient enough that I haven't needed to file an issue. I like option 2 (which could be adapted to attributes if needed, right?).
