### ISSUE TITLE
File path argument with leading/trailing quotes throwing Exception

### ISSUE THREAD

**Issue by billpratt** [natemcmaster/CommandLineUtils#68]
First off, thank you for forking this and continuing to work on it!

Many CLI apps let you pass in a file path argument as such ```--filepath="C:\Users\foo\file"``` (Windows) and ```--filepath="/home/foo/file"``` (Linux). When trying to do this with a C# Console app, the quotes are escaped as ```"\"C:\\Users\\foo\\file\""``` and ```"\"/home/foo/file\""```. This causes an exception to be thrown when using [LegalFilePathAttribute](https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/Attributes/LegalFilePathAttribute.cs#L32) because ```new FileInfo(path)``` throws a System.NotSupportedException with message "The given path's format is not supported.". I understand that this is not a bug from this library. I'd like to open a conversation about supporting this type of argument behavior.

**Comment by natemcmaster** [comment]
Interesting, which shell are you using? And what do you see as the output of a simple app like this?
```c#
    class Program
    {
        static void Main(string[] args)
        {
            foreach(var a in args)
                Console.WriteLine(a);
        }
    }
```
Seems like quoting of args may be a separate issue, but just happened to be uncovered via the LegalFilePath check

**Comment by billpratt** [comment]
Upon further investigation, this is only happening when reading input from Console.ReadLine(). 
Passing in "C:\Temp\test.txt" as an argument on startup works fine. It appears that Console.ReadLine() escapes " with \". This could affect [Prompt.cs](https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/Utilities/Prompt.cs). I first ran into this issue while using this [sample](https://github.com/natemcmaster/CommandLineUtils/blob/master/samples/Subcommands/Program.cs#L38)

**Comment by natemcmaster** [comment]
Ok, it sounds to me like this is the expected behavior then. Normally when using bash/powershell, the shell will remove quotes before passing it into the program. Console.ReadLine doesn't do, but that's something for the caller of Prompt.GetString or Console.ReadLine to handle.
