### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jerriep** [natemcmaster/CommandLineUtils#70]
Hi Nate,

I just started using this library and there are so many good things in here (for example the dependency injection and conventions). But sadly it is not very easy to get to grips with all of the concepts, or even know of their existence unless you work through the sample apps and answers for previous Issues. Also, the API reference in the docs is good for reference, but not very helpful to explain the concepts.

I'd love to help you sort out the docs, but I don't just want to jump in without checking with you first.

I blog regularly and worked for Auth0 on their docs, so I am comfortable with writing and doing this for you. I am also familiar with using DocFx, as I have used it for some of the Auth0 libraries I wrote.

So before I just start hammering away, do you have any ideas in your mind with regards to the outline for the docs of the various parts needing to be addressed?

**Comment by natemcmaster** [comment]
Thanks for making this offer. I'd love to help writing docs and samples. Off the top of my head, here are some ideas areas I think could need more docs:

 - Concept: convention API (new in 2.2.0).
    - What are the default conventions provided by the library?
    - How do you write your own convention?
  - Concept: validation
    - What kinds of validators can be used?
    - How do you write your own validation?
 - Concept: lifecycle. There are several phases in the app. Most samples show using .Execute(), but you can tap in to different phases. in order, they are,
   1. Model building (apply conventions and build up a CommandLineApplication object)
   2. Parsing (apply args[] to the app object)
   3. Validation (check all requirements are met)
   4. Execution (run the OnExecute handler on the selected subcommand)
 - Dependency injection - how to use it
 - Response file parsing

There are probably more, so feel free to suggest topics. I certainly don't expect you to write all of these topics, so let me know which ones you'd like to tackle. Thanks in advance!

**Comment by jerriep** [comment]
Ok great. Think I'll start with the dependency injection and can also look into the conventions and validation (I actually just had to do an `OnValidate` method with the unreleased bits).

The lifecycle I am definitely unfamiliar with atm, as well as response file parsing.

**Comment by natemcmaster** [comment]
> I actually just had to do an OnValidate method with the unreleased bits

FYI - I'm planning on releasing 2.2.0 this weekend :)

**Comment by jerriep** [comment]
This will be useful for helping write the docs:
https://docs.microsoft.com/en-us/teamblog/docs-extension

**Comment by natemcmaster** [comment]
I made improvements to docs generate. It runs automatically when changes are merged, so the only thing in the master branch is the markdown. Generated HTML is kept in the gh-pages branch.

I'm open to more subjects for documentation and would be happy to take more PRs for this. I'm closing for now as I'm not planning to write more docs anytime soon.

**Comment by jerriep** [comment]
Yeah, that is a good change, Nate. I noticed those commits a while back.

I will help you with more Docs, but the rest of this month is taken up by a bunch of personal projects I want to release. I think in June I will concentrate on writing again, as I want to release OAuth 2 and OIDC guides for my blog. So I will then be able to help you with this again.

**Comment by natemcmaster** [comment]
Awesome, thanks in advance.
