### ISSUE TITLE
How to preserve  newlines in option text ?

### ISSUE THREAD

**Issue by tooh** [natemcmaster/CommandLineUtils#73]
In my console application I have an option -n to pass text to be used as notes.

This argument can contain spaces and newlines.

I notice that newlines are not preserved. 

I found 
```
ArgumentEscaper.EscapeAndConcatenate(args);
```
but this does not give me the wanted result.

Please advice

**Comment by DoCode** [comment]
@tooh - I send in a [PR](https://github.com/natemcmaster/CommandLineUtils/pull/56) that preserve line breaks.  
Is this what you are looking for?

**Comment by tooh** [comment]
@DoCode thx for your reaction. To clarify my question. I mean the value of the option.

```
optionNotes.Value()
```
This is an option that can contain several lines of text

**Comment by DoCode** [comment]
@tooh ok. I understand.  
My PR does only address the help output...
Hm...

**Comment by natemcmaster** [comment]
.Value() will contain the raw value you pass in. So, it's really a matter of which shell you are using.
```
$ myprogram --notes 'You can usually enter
line breaks by pressing ENTER after starting a quoted string.
Most shells handle it just fine.

Unless you have command prompt.'
```
IIRC command prompt requires you add an ^ before each new line, but I don't use command prompt, so not sure

**Comment by tooh** [comment]
I'm not there yet.
The context of the program is a console app that calls a SOAP webservice.
This is the code that handles the XML for the SOAP call.

```
supportCallData.SupportCallEvent[0].Notes = notes + Environment.NewLine;
supportCallData.SupportCallEvent[0].NotesHTML = notes + "<br/>" + Environment.NewLine;
```

Any newlines I feed to the -n option are stripped.

**Comment by natemcmaster** [comment]
> Any newlines I feed to the -n option are stripped.

This library doesn't trim whitespace from inputs, so my guess is this library isn't the problem. Can you verify this by first inspecting the raw `string[]` input before you pass it to CommandLineApplication?
```c#
public static void Main(string[] args)
{
   for (var i = 0; i < args.Length; i++) Console.WriteLine($"{i} = '{args[i]}'");
   // ...proceed with your app
}
```

**Comment by natemcmaster** [comment]
@tooh closing as I don't _think_ there is anything wrong with the library. If you find something, let me know. If you're still having trouble passing new-lines to a command line app, you may also have success with StackOverflow, which has a much wider audience than this repo.

**Comment by tooh** [comment]
Turned out that I overlooked that the application had 2 methods to pass the notes.

The following was the solution:

```
supportCallData.SupportCallEvent[0].Notes = notes + Environment.NewLine;
supportCallData.SupportCallEvent[0].NotesHTML = **notes.Replace(Environment.NewLine,"<br/>")** + "<br/>" + Environment.NewLine;
```
