### ISSUE TITLE
Show help if all options are required but no options are specified

### ISSUE THREAD

**Issue by rowandh** [natemcmaster/CommandLineUtils#74]
If all the options in an application are defined with the `[Required]` attribute, and no options are specified when invoking the command, is there a way to show the help text?

Currently the application will show the first validation error.

**Comment by natemcmaster** [comment]
Yes, you could add your own validation error handler and show help text when errors happen. If you are using the attribute api, you should be able to handle validation errors on your own by adding a method named "OnValidationError" to your application type. If you are using the builder API, you can set a handler via `CommandLineApplication. OnValidationError`.

See https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.Conventions.ValidationErrorMethodConvention.html?q=ValidationErrorMethodConvention and https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.html?q=CommandLineApplicationExtensions#McMaster_Extensions_CommandLineUtils_CommandLineApplicationExtensions_OnValidationError_McMaster_Extensions_CommandLineUtils_CommandLineApplication_System_Action_System_ComponentModel_DataAnnotations_ValidationResult__

**Comment by rowandh** [comment]
I only want to show the help if no options at all were provided, regardless of their validation state. OnValidationError does not receive any contextual information, so there's no way to know whether one required option failed validation (in which case, display the validation error), or if all required options were missing (in which case, display the help). Or am I missing something?

**Comment by natemcmaster** [comment]
Maybe i didn't understand the question. I was thinking you could do this. Would this work? 
```c#
var app = new CommandLineApplication();
app.OnValidationError(r =>
{
  if (app.GetOptions().All(o => !o.HasValue()))
  {
    app.ShowHelp();
  }
  else
  {
    Console.Error.WriteLine(r.Message);
  }
});
```

**Comment by natemcmaster** [comment]
Closing for now as this issue appears to have gone stale. Feel free to continue the conversation. We can reopen it if needed.
