### ISSUE TITLE
Feature request: provide default value for option (and show it in the help)

### ISSUE THREAD

**Issue by voltagex** [natemcmaster/CommandLineUtils#82]
Apologies if I've missed this one. I see in the examples you're using conditionals to set default values, but what about providing something like

`[Option(Description = "Verbosity",DefaultValue = 5)]` so when an option is not required a default value is supplied - this could also be reflected in the help text so we're following the Principle of Least Astonishment.

**Comment by voltagex** [comment]
I found https://github.com/natemcmaster/CommandLineUtils/blob/master/samples/Attributes/Program.cs#L19 which is pretty much what I want. I guess the help text can't be easily generated from there.

**Comment by liamdawson** [comment]
That being said, I would like it if it could _infer_ the default value from the target property, as sometimes I want default values that can be statically set, but can't be set as a constant (e.g. a path that is in the user's home directory).

For example:

```csharp
[Option("--data-directory")]
public string DataDirectory { get; set; } = Path.Combine(Environment.GetSpecialDirectoryPath(Environment.SpecialDirectories.UserProfile), ".cache/app");
```

(typed from memory, may not compile)

**Comment by dbogatov** [comment]
Could we reopen this?
I'm glad the original author has found his workaround, but I would indeed ask that the default value is printed.

**Comment by natemcmaster** [comment]
Marking this as up-for grabs. I would be okay adding logic to print the default CLR value in the help. I'm not sure yet about adding new properties to `OptionAttribute` -- I think default property values are a more natural way to express this in C# -- but I would be okay if we added `string DefaulValue { get; set; }` to `CommandOption` for the builder API users.

**Comment by SeriousM** [comment]
My current workaround is to set the default value on the property, don't mark it with Required (as this would stop the execution because the option was not set in the command line) and call `Validator.Validate(this, new ValidationContext(this))` at the beginning of `OnExecuteAsync` to ensure that all the other attrubutes are checked, like FileExists or Url.

**Comment by EajksEajks** [comment]
And how would you set the default value using the builder API?

**Comment by scott-xu** [comment]
I made a PR https://github.com/natemcmaster/CommandLineUtils/pull/369 about showing allowed values in help text which is somewhat similar with this issue.

**Comment by scott-xu** [comment]
Here's my proposal
API:
```C#
public class CommandOption
{
   public Func<object> DefaultValueFactory { get; set; }
}
```
Usage
builder:
```C#
var app = new CommandLineApplication();
app.Option("--opt", "desc.", CommandOptionType.SingleValue, o => o.DefaultValueFactory = () => "foo");
```
attribute:
```C#
class Program
{
    [Option("--opt")]
    public string? Option { get; } = "foo";
}
```

**Comment by scott-xu** [comment]
We may need re-consider about the below implementation, or leave it as is:
```C#
public class CommandOption
{
   // other members

   public bool HasValue()
   {
       return Values.Any();
   }

   public string? Value()
   {
       return HasValue() ? Values[0] : null;
   }
}
```

**Comment by scott-xu** [comment]
Do you have any comments? @natemcmaster

**Comment by natemcmaster** [comment]
I prefer to avoid using `object` in API. I think its too ambiguous. What about this instead?
```csharp
public class CommandOption
{
   // other members

       public string? DefaultValue { get; set; }
}

public class CommandOption<T>
{
        private T _defaultValue;

        public new T DefaultValue
        {
            get => _defaultValue;
            set
            {
                _defaultValue = value;
                base.DefaultValue = value?.ToString();
            }
        }
}
```

**Comment by scott-xu** [comment]
I proposed object instead of string because I wanted to avoid converting, especially for attribute API. The most institute way to populate a default value is
```C#
    [Option("-o|--opt", "Some description.", CommandOptionType.SingleValue)]
    public SomeType? Option { get; } = SomeExpressionToBuildSomeType;
```
I’ll rethink about it.

**Comment by scott-xu** [comment]
The problem here is the logic about Value() and HasValue()
```C#
/// <summary>
/// True when <see cref="Values"/> is not empty.
/// </summary>
/// <returns></returns>
public bool HasValue()
{
    return Values.Any(); // Should we continue checking if the default value is set?
}

/// <summary>
/// Returns the first element of <see cref="Values"/>, if any.
/// </summary>
/// <returns></returns>
public string? Value()
{
    return HasValue() ? Values[0] : this.Default; // Sure we can return the first element of values, if any, and fall back to default value, if it has.
}

public string? DefaultValue { get; set; }
```

**Comment by scott-xu** [comment]
- I didn't change any logic about `Value()` and `HasValue()`
- Should we do the same for `CommandArgument`?

**Comment by scott-xu** [comment]
Default value for `CommandArgument` is added.

**Comment by natemcmaster** [comment]
> The problem here is the logic about Value() and HasValue()

I think the least-surprising behavior here would be to update Value and HasValue. 

For CommandOption:
* If DefaultValue is provided, HasValue is always true.
* Value returns what the user specified, or DefaultValue if nothing was given.

For CommandArgument:
* If DefaultValue is provided, `arg.Values` returns what the user specified, or `new List<string> { DefaultValue }`.
* arg.Value code remains the same as it's just sugar for getting the first item from arg.Values

**Comment by scott-xu** [comment]
I checked the code and I think we can share the same logic:
If DefaultValue is provided, add the default value to the Values list.

**Comment by natemcmaster** [comment]
This issue is resolved and available now in this beta: https://www.nuget.org/packages/McMaster.Extensions.CommandLineUtils/4.0.0-beta.56. Please take a look and let me know if you have feedback on its behavior.

**Comment by meywd** [comment]
@natemcmaster  First thank you for this library, its really helpful.

Regarding Default values, since this is in beta, I think the sample code at the front page shouldn't include `DefaultValue` or at least add a comment saying that its in beta, to not confuse users.
