### ISSUE TITLE
Feature request: options that are for display in help only, e.g. to document environment variables 

### ISSUE THREAD

**Issue by voltagex** [natemcmaster/CommandLineUtils#83]
Absolutely fine if this one gets closed as out of scope, but here's the scenario:

I've got an app that accepts some command line arguments but also reads environment variables, for example AWS's `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`

It'd be nice to have those turn up in the help text, I'm just not sure how to do it neatly.

**Comment by atruskie** [comment]
So I added my own `IHelpTextGenerator` (which was largely a copy of the default one) that was modified to add an environment variables section. Maybe that would work for you?

**Comment by voltagex** [comment]
Would you be willing to post the code for this? I wonder if the HelpTextGenerator can be extended to avoid the code duplication.

**Comment by atruskie** [comment]
Here you go https://github.com/QutEcoacoustics/audio-analysis/blob/master/src/AnalysisPrograms/Production/CustomHelpTextGenerator.cs

All I really did was add a EnvironmentOptions dictionary and print them out before the normal sections.

**Comment by voltagex** [comment]
Many thanks - I guess I can close this.

**Comment by natemcmaster** [comment]
You can also use the ExtendedHelpText property. Example: https://github.com/aspnet/DotNetTools/blob/dev/src/dotnet-watch/CommandLineOptions.cs
