### ISSUE TITLE
How I configure a option to expect a value with spaces and special characters?

### ISSUE THREAD

**Issue by jchannon** [natemcmaster/CommandLineUtils#87]
I want to do something like `myapp -ae <Foo Name="foo" Value="bar" />`

This causes issues with zsh for example so I have to escape some characters but once it enters my app this lib errors I think because it thinks `Name` is another command or argument

Is there a way to tell it that the value will need some escaping?

**Comment by jchannon** [comment]
Answer : Add Quotes

`myapp -ae "<foo name=\"foo\" value=\"bar\" />" `

**Comment by AldeRoberge** [comment]
Is this still the case? I tried today and it doesn't seem to work.

![image](https://user-images.githubusercontent.com/4276275/97789264-76138580-1b95-11eb-932b-10374de08fd0.png)

```

 [Option(ShortName = "k",
            Description = "Key to add.")]
        public string Key { get; }

        [Option(
            ShortName = "v",
            Description = "English value of the key."
        )]
        public string Value { get; }
```
