### ISSUE TITLE
Builder API example

### ISSUE THREAD

**Issue by TechieJones** [natemcmaster/CommandLineUtils#89]
The options work good, but could someone expand the Builder API example to demonstrate capturing arguments as a comma separated list?

**Comment by natemcmaster** [comment]
Sorry this fell off my radar. Comma separated lists aren't a first-class feature of this library, but you could implement it on your own. The simplest way to do a comma separated list is like this:
```csharp
    public static int Main(string[] args)
    {
        var app = new CommandLineApplication();
        var myArg = app.Argument("list of stuff", "A comma-separated list of things");

        app.OnExecute(() =>
        {
            string[] items = myArg.Value.Split(',');
        });
        return app.OnExecute(args);
    }
```
A word of caution: before .NET even runs, the shell will split input on handle spaces. For example, 

input | raw value of `string[] args`
---|---
`myapp.exe a,b,c` | `["a,b,c"]`
`myapp.exe a, b, c` | `["a,", "b,", "c"]`
`myapp.exe a , b , c` | `["a", ",", "b", ",", "c"]`

This splitting happens before .NET even runs, which is one of the reasons comma-separated lists isn't a first class feature.

Let me know if that helps. Feel free to continue discussion.
