### ISSUE TITLE
features from POSIX conventions

### ISSUE THREAD

**Issue by rotanov** [natemcmaster/CommandLineUtils#93]
1. I couldn't find how to enable support of `-tls` equivalence to `-l -s -t`. i.e. grouping of flags after a hyphen.
2. How to specify parsing of `[FILE]` part in example below? Or should I parse it from args before passing args to CommandLineUtils?

```
$>ls --help
Usage: ls [OPTION]... [FILE]...
List information about the FILEs (the current directory by default).
Sort entries alphabetically if none of -cftuvSUX nor --sort is specified.

Mandatory arguments to long options are mandatory for short options too.
  -a, --all                  do not ignore entries starting with .
  -A, --almost-all           do not list implied . and ..
      --author               with -l, print the author of each file
  -b, --escape               print C-style escapes for nongraphic characters
```

So if points above are not possible now, please consider implementing them.

See [POSIX Conventions for Command Line Arguments ](http://mat.unicam.it/piergallini/home/materiale/gc/java/essential/attributes/_posix.html)

**Comment by natemcmaster** [comment]
> I couldn't find how to enable support of -tls equivalence to -l -s -t. i.e. grouping of flags after a hyphen.

Not something currently supported, but I am opening to add this.

> How to specify parsing of [FILE] part in example below?

If I understand correctly, you're asking for positional arguments. You could do it like this:
```c#
var app = new CommandLineApplication();
var fileArg = app.Argument("FILE", "List of files", multipleValues: true)
    .IsRequired()
    .Accepts(a => a.LegalFilePath());
```
Or, if using attributes,
```c#
[Argument(0, "FILE", "List of files")]
[Required]
[LegalFilePath]
public string[] Files { get; }
```

**Comment by natemcmaster** [comment]
I've put this in the 2.3.0 milestone. Let me know if you are interested in helping implement it.

**Comment by natemcmaster** [comment]
Implemented in f00244246a3323743440119cabd521c5fae9e00c. You can try nightlies by using this feed: https://www.myget.org/gallery/natemcmaster/. This behavior will be enabled by default in 2.3.0 unless we detect there would be issues due to the app having short options with multiple characters. In 3.0, I'll make short options with multiple characters an error unless you disable clustering explicitly.

**Comment by atruskie** [comment]
Hi @natemcmaster - just to clarify, are multi-character short options supported with clustered groups?

An except from my app:
```
-ip|--index-properties-config <INDEX_PROPERTIES_CONFIG>                   User specified file containing a list of indices and their properties.
-fcs|--false-colour-spectrogram-config <FALSE_COLOUR_SPECTROGRAM_CONFIG>  Config file for drawing the false colour spectrograms.
 -v                                              Set the logging to be verbose. 
 -vv                                            Set the logging to very verbose. 
 -vvv                                           Set the logging to very very verbose.
```

- Which option is selected when `-vvv` is specified?
- I assume that `-ipfcs somefile.config` would throw an error?

Sorry for the comment on a closed issue... I will at some point bump the CLU library and test these cases myself.

**Comment by natemcmaster** [comment]
Multi-character short options are not supported in clustered groups. POSIX clustering requires single letter options only. By default (i.e. you haven't called `ParserSettings.ClusterOptions = true`), clustering is will be enabled if and only if there are no multi-character short option name. If you've explicitly enabled clustering and add a multi-character option, the library with throw an error.

Re: the `-v`, `-vv`, `-vvv` options. CLU will keep track of how many times NoValue options are specified. If you wanted to take advantage of clustering, you could do this instead:
```
var optVerbose = app.Option("-v", "Set the logging to verbose. Specify `-v` multiple times for even more verbosity", CommandOptionType.NoValue);
app.OnExecute(() => 
{
   var verboseLevel = optVerbose.HasValue()
      ? optVerbose.Values.Count
      : 0;
});
```

**Comment by atruskie** [comment]
@natemcmaster thanks for the response! Throwing an error is ideal, and being able to turn off the feature is great. The value counting option is super useful.
