### ISSUE TITLE
Support passing Uri values

### ISSUE THREAD

**Issue by liamdawson** [natemcmaster/CommandLineUtils#97]
**Is your feature request related to a problem? Please describe.**
I would like to set `System.Uri` values from options, but the library "Could not automatically determine how to convert string values into System.Uri on property"

**Describe the solution you'd like**
I would like an automatic conversion for strings to `System.Uri` values when the property is of type Uri.

**Describe alternatives you've considered**
I can apply a getter that makes a Uri of the given value, but that's extra boilerplate.

**Comment by liamdawson** [comment]
Here's what I was able to do as a boilerplate workaround:

```csharp
        [Option("-A|--api-base-url", "Base URL for API", CommandOptionType.SingleValue)]
        [Url]
        public string ApiBaseUrlString { get; set; } = "http://localhost:5000/api/";
        public Uri ApiBaseUrl => new Uri(ApiBaseUrlString, UriKind.RelativeOrAbsolute);
```

but it'd be nice to have it natively supported. I might make a PR for this when I'm off the clock.

**Comment by natemcmaster** [comment]
I'd take a PR for this. Add an implementation of IValueParser for System.uri, and add it to the default value parser provider: https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/Abstractions/ValueParserProvider.cs#L19-L36

**Comment by natemcmaster** [comment]
Also, maybe we should document custom value parsers better (cc @atruskie), but you can write your own parsers and add them to CommandLineApplication.ValueParsers.

Example in test code:
https://github.com/natemcmaster/CommandLineUtils/blob/a7814e79c9e30aa6ea8f638aee1df7517bdf3ab8/test/CommandLineUtils.Tests/ValueParserProviderCustomTests.cs#L60-L112

**Comment by natemcmaster** [comment]
Done in #98. This will be in 2.2.4 when that's released. In the meantime, you can get nightly builds here: https://www.myget.org/gallery/natemcmaster
